import { useState } from "react";
import { TxIconFilled } from "../assets/icons/filled";

const TxIconFilledStory = {
  title: "tx-design-ui/Foundation/TxIcon/TxIconFilled",
  component: "TxIcon",
  parameters: {
    layout: "fullscreen",
  },
};
export default TxIconFilledStory;

const iconData = [
  {
    name: "Add",
    file: TxIconFilled.IconAdd,
    description: "Add",
    category: "Filled",
  },
  {
    name: "AddressBook",
    file: TxIconFilled.IconAddressBook,
    description: "AddressBook",
    category: "Filled",
  },
  {
    name: "AlarmClock",
    file: TxIconFilled.IconAlarmClock,
    description: "AlarmClock",
    category: "Filled",
  },
  {
    name: "AlignCenter",
    file: TxIconFilled.IconAlignCenter,
    description: "AlignCenter",
    category: "Filled",
  },
  {
    name: "AlignJustify",
    file: TxIconFilled.IconAlignJustify,
    description: "AlignJustify",
    category: "Filled",
  },
  {
    name: "AlignLeft",
    file: TxIconFilled.IconAlignLeft,
    description: "AlignLeft",
    category: "Filled",
  },
  {
    name: "AlignRight",
    file: TxIconFilled.IconAlignRight,
    description: "AlignRight",
    category: "Filled",
  },
  {
    name: "Ambulance",
    file: TxIconFilled.IconAmbulance,
    description: "Ambulance",
    category: "Filled",
  },
  {
    name: "AngleDoubleLeft",
    file: TxIconFilled.IconAngleDoubleLeft,
    description: "AngleDoubleLeft",
    category: "Filled",
  },
  {
    name: "AngleDoubleRight",
    file: TxIconFilled.IconAngleDoubleRight,
    description: "AngleDoubleRight",
    category: "Filled",
  },
  {
    name: "AngleDoubleSmallLeft",
    file: TxIconFilled.IconAngleDoubleSmallLeft,
    description: "AngleDoubleSmallLeft",
    category: "Filled",
  },
  {
    name: "AngleDoubleSmallRight",
    file: TxIconFilled.IconAngleDoubleSmallRight,
    description: "AngleDoubleSmallRight",
    category: "Filled",
  },
  {
    name: "AngleDown",
    file: TxIconFilled.IconAngleDown,
    description: "AngleDown",
    category: "Filled",
  },
  {
    name: "AngleLeft",
    file: TxIconFilled.IconAngleLeft,
    description: "AngleLeft",
    category: "Filled",
  },
  {
    name: "AngleRight",
    file: TxIconFilled.IconAngleRight,
    description: "AngleRight",
    category: "Filled",
  },
  {
    name: "AngleSmallDown",
    file: TxIconFilled.IconAngleSmallDown,
    description: "AngleSmallDown",
    category: "Filled",
  },
  {
    name: "AngleSmallLeft",
    file: TxIconFilled.IconAngleSmallLeft,
    description: "AngleSmallLeft",
    category: "Filled",
  },
  {
    name: "AngleSmallRight",
    file: TxIconFilled.IconAngleSmallRight,
    description: "AngleSmallRight",
    category: "Filled",
  },
  {
    name: "AngleSmallUp",
    file: TxIconFilled.IconAngleSmallUp,
    description: "AngleSmallUp",
    category: "Filled",
  },
  {
    name: "AngleUp",
    file: TxIconFilled.IconAngleUp,
    description: "AngleUp",
    category: "Filled",
  },
  {
    name: "Apple",
    file: TxIconFilled.IconApple,
    description: "Apple",
    category: "Filled",
  },
  {
    name: "AppsAdd",
    file: TxIconFilled.IconAppsAdd,
    description: "AppsAdd",
    category: "Filled",
  },
  {
    name: "AppsDelete",
    file: TxIconFilled.IconAppsDelete,
    description: "AppsDelete",
    category: "Filled",
  },
  {
    name: "AppsSort",
    file: TxIconFilled.IconAppsSort,
    description: "AppsSort",
    category: "Filled",
  },
  {
    name: "Apps",
    file: TxIconFilled.IconApps,
    description: "Apps",
    category: "Filled",
  },
  {
    name: "Archive",
    file: TxIconFilled.IconArchive,
    description: "Archive",
    category: "Filled",
  },
  {
    name: "ArrowDown",
    file: TxIconFilled.IconArrowDown,
    description: "ArrowDown",
    category: "Filled",
  },
  {
    name: "ArrowFromBottom",
    file: TxIconFilled.IconArrowFromBottom,
    description: "ArrowFromBottom",
    category: "Filled",
  },
  {
    name: "ArrowLeft",
    file: TxIconFilled.IconArrowLeft,
    description: "ArrowLeft",
    category: "Filled",
  },
  {
    name: "ArrowRight",
    file: TxIconFilled.IconArrowRight,
    description: "ArrowRight",
    category: "Filled",
  },
  {
    name: "ArrowSmallDown",
    file: TxIconFilled.IconArrowSmallDown,
    description: "ArrowSmallDown",
    category: "Filled",
  },
  {
    name: "ArrowSmallLeft",
    file: TxIconFilled.IconArrowSmallLeft,
    description: "ArrowSmallLeft",
    category: "Filled",
  },
  {
    name: "ArrowSmallRight",
    file: TxIconFilled.IconArrowSmallRight,
    description: "ArrowSmallRight",
    category: "Filled",
  },
  {
    name: "ArrowSmallUp",
    file: TxIconFilled.IconArrowSmallUp,
    description: "ArrowSmallUp",
    category: "Filled",
  },
  {
    name: "ArrowUp",
    file: TxIconFilled.IconArrowUp,
    description: "ArrowUp",
    category: "Filled",
  },
  {
    name: "Asterik",
    file: TxIconFilled.IconAsterik,
    description: "Asterik",
    category: "Filled",
  },
  {
    name: "At",
    file: TxIconFilled.IconAt,
    description: "At",
    category: "Filled",
  },
  {
    name: "Backpack",
    file: TxIconFilled.IconBackpack,
    description: "Backpack",
    category: "Filled",
  },
  {
    name: "Badge",
    file: TxIconFilled.IconBadge,
    description: "Badge",
    category: "Filled",
  },
  {
    name: "Balloons",
    file: TxIconFilled.IconBalloons,
    description: "Balloons",
    category: "Filled",
  },
  {
    name: "Ban",
    file: TxIconFilled.IconBan,
    description: "Ban",
    category: "Filled",
  },
  {
    name: "BandAid",
    file: TxIconFilled.IconBandAid,
    description: "BandAid",
    category: "Filled",
  },
  {
    name: "Bank",
    file: TxIconFilled.IconBank,
    description: "Bank",
    category: "Filled",
  },
  {
    name: "BarberShop",
    file: TxIconFilled.IconBarberShop,
    description: "BarberShop",
    category: "Filled",
  },
  {
    name: "Baseball",
    file: TxIconFilled.IconBaseball,
    description: "Baseball",
    category: "Filled",
  },
  {
    name: "Basketball",
    file: TxIconFilled.IconBasketball,
    description: "Basketball",
    category: "Filled",
  },
  {
    name: "Bed",
    file: TxIconFilled.IconBed,
    description: "Bed",
    category: "Filled",
  },
  {
    name: "Beer",
    file: TxIconFilled.IconBeer,
    description: "Beer",
    category: "Filled",
  },
  {
    name: "BellRing",
    file: TxIconFilled.IconBellRing,
    description: "BellRing",
    category: "Filled",
  },
  {
    name: "BellSchool",
    file: TxIconFilled.IconBellSchool,
    description: "BellSchool",
    category: "Filled",
  },
  {
    name: "Bell",
    file: TxIconFilled.IconBell,
    description: "Bell",
    category: "Filled",
  },
  {
    name: "Bike",
    file: TxIconFilled.IconBike,
    description: "Bike",
    category: "Filled",
  },
  {
    name: "Billiard",
    file: TxIconFilled.IconBilliard,
    description: "Billiard",
    category: "Filled",
  },
  {
    name: "Bold",
    file: TxIconFilled.IconBold,
    description: "Bold",
    category: "Filled",
  },
  {
    name: "BookAlt",
    file: TxIconFilled.IconBookAlt,
    description: "BookAlt",
    category: "Filled",
  },
  {
    name: "Book",
    file: TxIconFilled.IconBook,
    description: "Book",
    category: "Filled",
  },
  {
    name: "Bookmark",
    file: TxIconFilled.IconBookmark,
    description: "Bookmark",
    category: "Filled",
  },
  {
    name: "Bowling",
    file: TxIconFilled.IconBowling,
    description: "Bowling",
    category: "Filled",
  },
  {
    name: "BoxAlt",
    file: TxIconFilled.IconBoxAlt,
    description: "BoxAlt",
    category: "Filled",
  },
  {
    name: "Box",
    file: TxIconFilled.IconBox,
    description: "Box",
    category: "Filled",
  },
  {
    name: "BreadSlice",
    file: TxIconFilled.IconBreadSlice,
    description: "BreadSlice",
    category: "Filled",
  },
  {
    name: "Briefcase",
    file: TxIconFilled.IconBriefcase,
    description: "Briefcase",
    category: "Filled",
  },
  {
    name: "Broom",
    file: TxIconFilled.IconBroom,
    description: "Broom",
    category: "Filled",
  },
  {
    name: "Browser",
    file: TxIconFilled.IconBrowser,
    description: "Browser",
    category: "Filled",
  },
  {
    name: "Brush",
    file: TxIconFilled.IconBrush,
    description: "Brush",
    category: "Filled",
  },
  {
    name: "Bug",
    file: TxIconFilled.IconBug,
    description: "Bug",
    category: "Filled",
  },
  {
    name: "Building",
    file: TxIconFilled.IconBuilding,
    description: "Building",
    category: "Filled",
  },
  {
    name: "Bulb",
    file: TxIconFilled.IconBulb,
    description: "Bulb",
    category: "Filled",
  },
  {
    name: "Butterfly",
    file: TxIconFilled.IconButterfly,
    description: "Butterfly",
    category: "Filled",
  },
  {
    name: "CakeBirthday",
    file: TxIconFilled.IconCakeBirthday,
    description: "CakeBirthday",
    category: "Filled",
  },
  {
    name: "CakeWedding",
    file: TxIconFilled.IconCakeWedding,
    description: "CakeWedding",
    category: "Filled",
  },
  {
    name: "Calculator",
    file: TxIconFilled.IconCalculator,
    description: "Calculator",
    category: "Filled",
  },
  {
    name: "Calendar",
    file: TxIconFilled.IconCalendar,
    description: "Calendar",
    category: "Filled",
  },
  {
    name: "CallHistory",
    file: TxIconFilled.IconCallHistory,
    description: "CallHistory",
    category: "Filled",
  },
  {
    name: "CallIncoming",
    file: TxIconFilled.IconCallIncoming,
    description: "CallIncoming",
    category: "Filled",
  },
  {
    name: "CallMissed",
    file: TxIconFilled.IconCallMissed,
    description: "CallMissed",
    category: "Filled",
  },
  {
    name: "CallOutgoing",
    file: TxIconFilled.IconCallOutgoing,
    description: "CallOutgoing",
    category: "Filled",
  },
  {
    name: "Camera",
    file: TxIconFilled.IconCamera,
    description: "Camera",
    category: "Filled",
  },
  {
    name: "Camping",
    file: TxIconFilled.IconCamping,
    description: "Camping",
    category: "Filled",
  },
  {
    name: "Car",
    file: TxIconFilled.IconCar,
    description: "Car",
    category: "Filled",
  },
  {
    name: "CaretDown",
    file: TxIconFilled.IconCaretDown,
    description: "CaretDown",
    category: "Filled",
  },
  {
    name: "CaretLeft",
    file: TxIconFilled.IconCaretLeft,
    description: "CaretLeft",
    category: "Filled",
  },
  {
    name: "CaretRight",
    file: TxIconFilled.IconCaretRight,
    description: "CaretRight",
    category: "Filled",
  },
  {
    name: "CaretUp",
    file: TxIconFilled.IconCaretUp,
    description: "CaretUp",
    category: "Filled",
  },
  {
    name: "Carrot",
    file: TxIconFilled.IconCarrot,
    description: "Carrot",
    category: "Filled",
  },
  {
    name: "ChartConnected",
    file: TxIconFilled.IconChartConnected,
    description: "ChartConnected",
    category: "Filled",
  },
  {
    name: "ChartHistogram",
    file: TxIconFilled.IconChartHistogram,
    description: "ChartHistogram",
    category: "Filled",
  },
  {
    name: "ChartNetwork",
    file: TxIconFilled.IconChartNetwork,
    description: "ChartNetwork",
    category: "Filled",
  },
  {
    name: "ChartPieAlt",
    file: TxIconFilled.IconChartPieAlt,
    description: "ChartPieAlt",
    category: "Filled",
  },
  {
    name: "ChartPie",
    file: TxIconFilled.IconChartPie,
    description: "ChartPie",
    category: "Filled",
  },
  {
    name: "ChartPyramid",
    file: TxIconFilled.IconChartPyramid,
    description: "ChartPyramid",
    category: "Filled",
  },
  {
    name: "ChartSetTheory",
    file: TxIconFilled.IconChartSetTheory,
    description: "ChartSetTheory",
    category: "Filled",
  },
  {
    name: "ChartTree",
    file: TxIconFilled.IconChartTree,
    description: "ChartTree",
    category: "Filled",
  },
  {
    name: "ChatArrowDown",
    file: TxIconFilled.IconChatArrowDown,
    description: "ChatArrowDown",
    category: "Filled",
  },
  {
    name: "ChatArrowGrow",
    file: TxIconFilled.IconChatArrowGrow,
    description: "ChatArrowGrow",
    category: "Filled",
  },
  {
    name: "Check",
    file: TxIconFilled.IconCheck,
    description: "Check",
    category: "Filled",
  },
  {
    name: "Checkbox",
    file: TxIconFilled.IconCheckbox,
    description: "Checkbox",
    category: "Filled",
  },
  {
    name: "Cheese",
    file: TxIconFilled.IconCheese,
    description: "Cheese",
    category: "Filled",
  },
  {
    name: "ChessPiece",
    file: TxIconFilled.IconChessPiece,
    description: "ChessPiece",
    category: "Filled",
  },
  {
    name: "ChildHead",
    file: TxIconFilled.IconChildHead,
    description: "ChildHead",
    category: "Filled",
  },
  {
    name: "CircleSmall",
    file: TxIconFilled.IconCircleSmall,
    description: "CircleSmall",
    category: "Filled",
  },
  {
    name: "Circle",
    file: TxIconFilled.IconCircle,
    description: "Circle",
    category: "Filled",
  },
  {
    name: "Clip",
    file: TxIconFilled.IconClip,
    description: "Clip",
    category: "Filled",
  },
  {
    name: "Clock",
    file: TxIconFilled.IconClock,
    description: "Clock",
    category: "Filled",
  },
  {
    name: "CloudCheck",
    file: TxIconFilled.IconCloudCheck,
    description: "CloudCheck",
    category: "Filled",
  },
  {
    name: "CloudDisabled",
    file: TxIconFilled.IconCloudDisabled,
    description: "CloudDisabled",
    category: "Filled",
  },
  {
    name: "CloudDownload",
    file: TxIconFilled.IconCloudDownload,
    description: "CloudDownload",
    category: "Filled",
  },
  {
    name: "CloudShare",
    file: TxIconFilled.IconCloudShare,
    description: "CloudShare",
    category: "Filled",
  },
  {
    name: "CloudUpload",
    file: TxIconFilled.IconCloudUpload,
    description: "CloudUpload",
    category: "Filled",
  },
  {
    name: "Cloud",
    file: TxIconFilled.IconCloud,
    description: "Cloud",
    category: "Filled",
  },
  {
    name: "Clouds",
    file: TxIconFilled.IconClouds,
    description: "Clouds",
    category: "Filled",
  },
  {
    name: "Cocktail",
    file: TxIconFilled.IconCocktail,
    description: "Cocktail",
    category: "Filled",
  },
  {
    name: "Coffee",
    file: TxIconFilled.IconCoffee,
    description: "Coffee",
    category: "Filled",
  },
  {
    name: "CommentAlt",
    file: TxIconFilled.IconCommentAlt,
    description: "CommentAlt",
    category: "Filled",
  },
  {
    name: "CommentCheck",
    file: TxIconFilled.IconCommentCheck,
    description: "CommentCheck",
    category: "Filled",
  },
  {
    name: "CommentHeart",
    file: TxIconFilled.IconCommentHeart,
    description: "CommentHeart",
    category: "Filled",
  },
  {
    name: "CommentInfo",
    file: TxIconFilled.IconCommentInfo,
    description: "CommentInfo",
    category: "Filled",
  },
  {
    name: "CommentUser",
    file: TxIconFilled.IconCommentUser,
    description: "CommentUser",
    category: "Filled",
  },
  {
    name: "Comment",
    file: TxIconFilled.IconComment,
    description: "Comment",
    category: "Filled",
  },
  {
    name: "Comments",
    file: TxIconFilled.IconComments,
    description: "Comments",
    category: "Filled",
  },
  {
    name: "CompressAlt",
    file: TxIconFilled.IconCompressAlt,
    description: "CompressAlt",
    category: "Filled",
  },
  {
    name: "Compress",
    file: TxIconFilled.IconCompress,
    description: "Compress",
    category: "Filled",
  },
  {
    name: "Computer",
    file: TxIconFilled.IconComputer,
    description: "Computer",
    category: "Filled",
  },
  {
    name: "Confetti",
    file: TxIconFilled.IconConfetti,
    description: "Confetti",
    category: "Filled",
  },
  {
    name: "Cookie",
    file: TxIconFilled.IconCookie,
    description: "Cookie",
    category: "Filled",
  },
  {
    name: "CopyAlt",
    file: TxIconFilled.IconCopyAlt,
    description: "CopyAlt",
    category: "Filled",
  },
  {
    name: "Copy",
    file: TxIconFilled.IconCopy,
    description: "Copy",
    category: "Filled",
  },
  {
    name: "Copyright",
    file: TxIconFilled.IconCopyright,
    description: "Copyright",
    category: "Filled",
  },
  {
    name: "Cow",
    file: TxIconFilled.IconCow,
    description: "Cow",
    category: "Filled",
  },
  {
    name: "Cream",
    file: TxIconFilled.IconCream,
    description: "Cream",
    category: "Filled",
  },
  {
    name: "CreditCard",
    file: TxIconFilled.IconCreditCard,
    description: "CreditCard",
    category: "Filled",
  },
  {
    name: "Croissant",
    file: TxIconFilled.IconCroissant,
    description: "Croissant",
    category: "Filled",
  },
  {
    name: "CrossCircle",
    file: TxIconFilled.IconCrossCircle,
    description: "CrossCircle",
    category: "Filled",
  },
  {
    name: "CrossSmall",
    file: TxIconFilled.IconCrossSmall,
    description: "CrossSmall",
    category: "Filled",
  },
  {
    name: "Cross",
    file: TxIconFilled.IconCross,
    description: "Cross",
    category: "Filled",
  },
  {
    name: "Crown",
    file: TxIconFilled.IconCrown,
    description: "Crown",
    category: "Filled",
  },
  {
    name: "Cube",
    file: TxIconFilled.IconCube,
    description: "Cube",
    category: "Filled",
  },
  {
    name: "Cupcake",
    file: TxIconFilled.IconCupcake,
    description: "Cupcake",
    category: "Filled",
  },
  {
    name: "CursorFinger",
    file: TxIconFilled.IconCursorFinger,
    description: "CursorFinger",
    category: "Filled",
  },
  {
    name: "CursorPlus",
    file: TxIconFilled.IconCursorPlus,
    description: "CursorPlus",
    category: "Filled",
  },
  {
    name: "CursorTextAlt",
    file: TxIconFilled.IconCursorTextAlt,
    description: "CursorTextAlt",
    category: "Filled",
  },
  {
    name: "CursorText",
    file: TxIconFilled.IconCursorText,
    description: "CursorText",
    category: "Filled",
  },
  {
    name: "Cursor",
    file: TxIconFilled.IconCursor,
    description: "Cursor",
    category: "Filled",
  },
  {
    name: "Dart",
    file: TxIconFilled.IconDart,
    description: "Dart",
    category: "Filled",
  },
  {
    name: "Dashboard",
    file: TxIconFilled.IconDashboard,
    description: "Dashboard",
    category: "Filled",
  },
  {
    name: "DataTransfer",
    file: TxIconFilled.IconDataTransfer,
    description: "DataTransfer",
    category: "Filled",
  },
  {
    name: "Database",
    file: TxIconFilled.IconDatabase,
    description: "Database",
    category: "Filled",
  },
  {
    name: "Delete",
    file: TxIconFilled.IconDelete,
    description: "Delete",
    category: "Filled",
  },
  {
    name: "Diamond",
    file: TxIconFilled.IconDiamond,
    description: "Diamond",
    category: "Filled",
  },
  {
    name: "Dice",
    file: TxIconFilled.IconDice,
    description: "Dice",
    category: "Filled",
  },
  {
    name: "Diploma",
    file: TxIconFilled.IconDiploma,
    description: "Diploma",
    category: "Filled",
  },
  {
    name: "DiscoBall",
    file: TxIconFilled.IconDiscoBall,
    description: "DiscoBall",
    category: "Filled",
  },
  {
    name: "Disk",
    file: TxIconFilled.IconDisk,
    description: "Disk",
    category: "Filled",
  },
  {
    name: "Doctor",
    file: TxIconFilled.IconDoctor,
    description: "Doctor",
    category: "Filled",
  },
  {
    name: "DocumentSigned",
    file: TxIconFilled.IconDocumentSigned,
    description: "DocumentSigned",
    category: "Filled",
  },
  {
    name: "Document",
    file: TxIconFilled.IconDocument,
    description: "Document",
    category: "Filled",
  },
  {
    name: "Dollar",
    file: TxIconFilled.IconDollar,
    description: "Dollar",
    category: "Filled",
  },
  {
    name: "Download",
    file: TxIconFilled.IconDownload,
    description: "Download",
    category: "Filled",
  },
  {
    name: "DrinkAlt",
    file: TxIconFilled.IconDrinkAlt,
    description: "DrinkAlt",
    category: "Filled",
  },
  {
    name: "Drumstick",
    file: TxIconFilled.IconDrumstick,
    description: "Drumstick",
    category: "Filled",
  },
  {
    name: "Duplicate",
    file: TxIconFilled.IconDuplicate,
    description: "Duplicate",
    category: "Filled",
  },
  {
    name: "ELearning",
    file: TxIconFilled.IconELearning,
    description: "ELearning",
    category: "Filled",
  },
  {
    name: "Earnings",
    file: TxIconFilled.IconEarnings,
    description: "Earnings",
    category: "Filled",
  },
  {
    name: "EditAlt",
    file: TxIconFilled.IconEditAlt,
    description: "EditAlt",
    category: "Filled",
  },
  {
    name: "Edit",
    file: TxIconFilled.IconEdit,
    description: "Edit",
    category: "Filled",
  },
  {
    name: "EnvelopeBan",
    file: TxIconFilled.IconEnvelopeBan,
    description: "EnvelopeBan",
    category: "Filled",
  },
  {
    name: "EnvelopeDownload",
    file: TxIconFilled.IconEnvelopeDownload,
    description: "EnvelopeDownload",
    category: "Filled",
  },
  {
    name: "EnvelopeMarker",
    file: TxIconFilled.IconEnvelopeMarker,
    description: "EnvelopeMarker",
    category: "Filled",
  },
  {
    name: "EnvelopeOpen",
    file: TxIconFilled.IconEnvelopeOpen,
    description: "EnvelopeOpen",
    category: "Filled",
  },
  {
    name: "EnvelopePlus",
    file: TxIconFilled.IconEnvelopePlus,
    description: "EnvelopePlus",
    category: "Filled",
  },
  {
    name: "Envelope",
    file: TxIconFilled.IconEnvelope,
    description: "Envelope",
    category: "Filled",
  },
  {
    name: "Euro",
    file: TxIconFilled.IconEuro,
    description: "Euro",
    category: "Filled",
  },
  {
    name: "Exclamation",
    file: TxIconFilled.IconExclamation,
    description: "Exclamation",
    category: "Filled",
  },
  {
    name: "Expand",
    file: TxIconFilled.IconExpand,
    description: "Expand",
    category: "Filled",
  },
  {
    name: "EyeCrossed",
    file: TxIconFilled.IconEyeCrossed,
    description: "EyeCrossed",
    category: "Filled",
  },
  {
    name: "EyeDropper",
    file: TxIconFilled.IconEyeDropper,
    description: "EyeDropper",
    category: "Filled",
  },
  {
    name: "Eye",
    file: TxIconFilled.IconEye,
    description: "Eye",
    category: "Filled",
  },
  {
    name: "Feather",
    file: TxIconFilled.IconFeather,
    description: "Feather",
    category: "Filled",
  },
  {
    name: "FerrisWheel",
    file: TxIconFilled.IconFerrisWheel,
    description: "FerrisWheel",
    category: "Filled",
  },
  {
    name: "FileAdd",
    file: TxIconFilled.IconFileAdd,
    description: "FileAdd",
    category: "Filled",
  },
  {
    name: "FileAi",
    file: TxIconFilled.IconFileAi,
    description: "FileAi",
    category: "Filled",
  },
  {
    name: "FileCheck",
    file: TxIconFilled.IconFileCheck,
    description: "FileCheck",
    category: "Filled",
  },
  {
    name: "FileDelete",
    file: TxIconFilled.IconFileDelete,
    description: "FileDelete",
    category: "Filled",
  },
  {
    name: "FileEps",
    file: TxIconFilled.IconFileEps,
    description: "FileEps",
    category: "Filled",
  },
  {
    name: "FileGif",
    file: TxIconFilled.IconFileGif,
    description: "FileGif",
    category: "Filled",
  },
  {
    name: "FileMusic",
    file: TxIconFilled.IconFileMusic,
    description: "FileMusic",
    category: "Filled",
  },
  {
    name: "FilePsd",
    file: TxIconFilled.IconFilePsd,
    description: "FilePsd",
    category: "Filled",
  },
  {
    name: "File",
    file: TxIconFilled.IconFile,
    description: "File",
    category: "Filled",
  },
  {
    name: "Fill",
    file: TxIconFilled.IconFill,
    description: "Fill",
    category: "Filled",
  },
  {
    name: "Film",
    file: TxIconFilled.IconFilm,
    description: "Film",
    category: "Filled",
  },
  {
    name: "Filter",
    file: TxIconFilled.IconFilter,
    description: "Filter",
    category: "Filled",
  },
  {
    name: "Fingerprint",
    file: TxIconFilled.IconFingerprint,
    description: "Fingerprint",
    category: "Filled",
  },
  {
    name: "Fish",
    file: TxIconFilled.IconFish,
    description: "Fish",
    category: "Filled",
  },
  {
    name: "Flag",
    file: TxIconFilled.IconFlag,
    description: "Flag",
    category: "Filled",
  },
  {
    name: "Flame",
    file: TxIconFilled.IconFlame,
    description: "Flame",
    category: "Filled",
  },
  {
    name: "FlipHorizontal",
    file: TxIconFilled.IconFlipHorizontal,
    description: "FlipHorizontal",
    category: "Filled",
  },
  {
    name: "FlowerBouquet",
    file: TxIconFilled.IconFlowerBouquet,
    description: "FlowerBouquet",
    category: "Filled",
  },
  {
    name: "FlowerTulip",
    file: TxIconFilled.IconFlowerTulip,
    description: "FlowerTulip",
    category: "Filled",
  },
  {
    name: "Flower",
    file: TxIconFilled.IconFlower,
    description: "Flower",
    category: "Filled",
  },
  {
    name: "FolderAdd",
    file: TxIconFilled.IconFolderAdd,
    description: "FolderAdd",
    category: "Filled",
  },
  {
    name: "Folder",
    file: TxIconFilled.IconFolder,
    description: "Folder",
    category: "Filled",
  },
  {
    name: "Following",
    file: TxIconFilled.IconFollowing,
    description: "Following",
    category: "Filled",
  },
  {
    name: "Football",
    file: TxIconFilled.IconFootball,
    description: "Football",
    category: "Filled",
  },
  {
    name: "Form",
    file: TxIconFilled.IconForm,
    description: "Form",
    category: "Filled",
  },
  {
    name: "Forward",
    file: TxIconFilled.IconForward,
    description: "Forward",
    category: "Filled",
  },
  {
    name: "Fox",
    file: TxIconFilled.IconFox,
    description: "Fox",
    category: "Filled",
  },
  {
    name: "Frown",
    file: TxIconFilled.IconFrown,
    description: "Frown",
    category: "Filled",
  },
  {
    name: "Ftp",
    file: TxIconFilled.IconFtp,
    description: "Ftp",
    category: "Filled",
  },
  {
    name: "Gallery",
    file: TxIconFilled.IconGallery,
    description: "Gallery",
    category: "Filled",
  },
  {
    name: "Gamepad",
    file: TxIconFilled.IconGamepad,
    description: "Gamepad",
    category: "Filled",
  },
  {
    name: "GasPump",
    file: TxIconFilled.IconGasPump,
    description: "GasPump",
    category: "Filled",
  },
  {
    name: "Gem",
    file: TxIconFilled.IconGem,
    description: "Gem",
    category: "Filled",
  },
  {
    name: "Gift",
    file: TxIconFilled.IconGift,
    description: "Gift",
    category: "Filled",
  },
  {
    name: "GlassCheers",
    file: TxIconFilled.IconGlassCheers,
    description: "GlassCheers",
    category: "Filled",
  },
  {
    name: "Glasses",
    file: TxIconFilled.IconGlasses,
    description: "Glasses",
    category: "Filled",
  },
  {
    name: "GlobeAlt",
    file: TxIconFilled.IconGlobeAlt,
    description: "GlobeAlt",
    category: "Filled",
  },
  {
    name: "Globe",
    file: TxIconFilled.IconGlobe,
    description: "Globe",
    category: "Filled",
  },
  {
    name: "Golf",
    file: TxIconFilled.IconGolf,
    description: "Golf",
    category: "Filled",
  },
  {
    name: "GraduationCap",
    file: TxIconFilled.IconGraduationCap,
    description: "GraduationCap",
    category: "Filled",
  },
  {
    name: "GraphicTablet",
    file: TxIconFilled.IconGraphicTablet,
    description: "GraphicTablet",
    category: "Filled",
  },
  {
    name: "GridAlt",
    file: TxIconFilled.IconGridAlt,
    description: "GridAlt",
    category: "Filled",
  },
  {
    name: "Grid",
    file: TxIconFilled.IconGrid,
    description: "Grid",
    category: "Filled",
  },
  {
    name: "Guitar",
    file: TxIconFilled.IconGuitar,
    description: "Guitar",
    category: "Filled",
  },
  {
    name: "Gym",
    file: TxIconFilled.IconGym,
    description: "Gym",
    category: "Filled",
  },
  {
    name: "Hamburger",
    file: TxIconFilled.IconHamburger,
    description: "Hamburger",
    category: "Filled",
  },
  {
    name: "HandHoldingHeart",
    file: TxIconFilled.IconHandHoldingHeart,
    description: "HandHoldingHeart",
    category: "Filled",
  },
  {
    name: "Hastag",
    file: TxIconFilled.IconHastag,
    description: "Hastag",
    category: "Filled",
  },
  {
    name: "HatBirthday",
    file: TxIconFilled.IconHatBirthday,
    description: "HatBirthday",
    category: "Filled",
  },
  {
    name: "HeadSideThinking",
    file: TxIconFilled.IconHeadSideThinking,
    description: "HeadSideThinking",
    category: "Filled",
  },
  {
    name: "Headphones",
    file: TxIconFilled.IconHeadphones,
    description: "Headphones",
    category: "Filled",
  },
  {
    name: "Headset",
    file: TxIconFilled.IconHeadset,
    description: "Headset",
    category: "Filled",
  },
  {
    name: "HeartArrow",
    file: TxIconFilled.IconHeartArrow,
    description: "HeartArrow",
    category: "Filled",
  },
  {
    name: "Heart",
    file: TxIconFilled.IconHeart,
    description: "Heart",
    category: "Filled",
  },
  {
    name: "HomeLocationAlt",
    file: TxIconFilled.IconHomeLocationAlt,
    description: "HomeLocationAlt",
    category: "Filled",
  },
  {
    name: "HomeLocation",
    file: TxIconFilled.IconHomeLocation,
    description: "HomeLocation",
    category: "Filled",
  },
  {
    name: "Home",
    file: TxIconFilled.IconHome,
    description: "Home",
    category: "Filled",
  },
  {
    name: "HourglassEnd",
    file: TxIconFilled.IconHourglassEnd,
    description: "HourglassEnd",
    category: "Filled",
  },
  {
    name: "Hourglass",
    file: TxIconFilled.IconHourglass,
    description: "Hourglass",
    category: "Filled",
  },
  {
    name: "IceCream",
    file: TxIconFilled.IconIceCream,
    description: "IceCream",
    category: "Filled",
  },
  {
    name: "IceSkate",
    file: TxIconFilled.IconIceSkate,
    description: "IceSkate",
    category: "Filled",
  },
  {
    name: "IdBadge",
    file: TxIconFilled.IconIdBadge,
    description: "IdBadge",
    category: "Filled",
  },
  {
    name: "Inbox",
    file: TxIconFilled.IconInbox,
    description: "Inbox",
    category: "Filled",
  },
  {
    name: "Incognito",
    file: TxIconFilled.IconIncognito,
    description: "Incognito",
    category: "Filled",
  },
  {
    name: "Indent",
    file: TxIconFilled.IconIndent,
    description: "Indent",
    category: "Filled",
  },
  {
    name: "Infinity",
    file: TxIconFilled.IconInfinity,
    description: "Infinity",
    category: "Filled",
  },
  {
    name: "Info",
    file: TxIconFilled.IconInfo,
    description: "Info",
    category: "Filled",
  },
  {
    name: "Interactive",
    file: TxIconFilled.IconInteractive,
    description: "Interactive",
    category: "Filled",
  },
  {
    name: "Interlining",
    file: TxIconFilled.IconInterlining,
    description: "Interlining",
    category: "Filled",
  },
  {
    name: "Interrogation",
    file: TxIconFilled.IconInterrogation,
    description: "Interrogation",
    category: "Filled",
  },
  {
    name: "Italic",
    file: TxIconFilled.IconItalic,
    description: "Italic",
    category: "Filled",
  },
  {
    name: "Jpg",
    file: TxIconFilled.IconJpg,
    description: "Jpg",
    category: "Filled",
  },
  {
    name: "Key",
    file: TxIconFilled.IconKey,
    description: "Key",
    category: "Filled",
  },
  {
    name: "Keyboard",
    file: TxIconFilled.IconKeyboard,
    description: "Keyboard",
    category: "Filled",
  },
  {
    name: "Kite",
    file: TxIconFilled.IconKite,
    description: "Kite",
    category: "Filled",
  },
  {
    name: "Label",
    file: TxIconFilled.IconLabel,
    description: "Label",
    category: "Filled",
  },
  {
    name: "Laptop",
    file: TxIconFilled.IconLaptop,
    description: "Laptop",
    category: "Filled",
  },
  {
    name: "Lasso",
    file: TxIconFilled.IconLasso,
    description: "Lasso",
    category: "Filled",
  },
  {
    name: "Laugh",
    file: TxIconFilled.IconLaugh,
    description: "Laugh",
    category: "Filled",
  },
  {
    name: "Layers",
    file: TxIconFilled.IconLayers,
    description: "Layers",
    category: "Filled",
  },
  {
    name: "LayoutFluid",
    file: TxIconFilled.IconLayoutFluid,
    description: "LayoutFluid",
    category: "Filled",
  },
  {
    name: "Leaf",
    file: TxIconFilled.IconLeaf,
    description: "Leaf",
    category: "Filled",
  },
  {
    name: "LetterCase",
    file: TxIconFilled.IconLetterCase,
    description: "LetterCase",
    category: "Filled",
  },
  {
    name: "LifeRing",
    file: TxIconFilled.IconLifeRing,
    description: "LifeRing",
    category: "Filled",
  },
  {
    name: "LineWidth",
    file: TxIconFilled.IconLineWidth,
    description: "LineWidth",
    category: "Filled",
  },
  {
    name: "Link",
    file: TxIconFilled.IconLink,
    description: "Link",
    category: "Filled",
  },
  {
    name: "Lipstick",
    file: TxIconFilled.IconLipstick,
    description: "Lipstick",
    category: "Filled",
  },
  {
    name: "ListCheck",
    file: TxIconFilled.IconListCheck,
    description: "ListCheck",
    category: "Filled",
  },
  {
    name: "List",
    file: TxIconFilled.IconList,
    description: "List",
    category: "Filled",
  },
  {
    name: "LocationAlt",
    file: TxIconFilled.IconLocationAlt,
    description: "LocationAlt",
    category: "Filled",
  },
  {
    name: "LockAlt",
    file: TxIconFilled.IconLockAlt,
    description: "LockAlt",
    category: "Filled",
  },
  {
    name: "Lock",
    file: TxIconFilled.IconLock,
    description: "Lock",
    category: "Filled",
  },
  {
    name: "LuggageRolling",
    file: TxIconFilled.IconLuggageRolling,
    description: "LuggageRolling",
    category: "Filled",
  },
  {
    name: "MagicWand",
    file: TxIconFilled.IconMagicWand,
    description: "MagicWand",
    category: "Filled",
  },
  {
    name: "MakeupBrush",
    file: TxIconFilled.IconMakeupBrush,
    description: "MakeupBrush",
    category: "Filled",
  },
  {
    name: "ManHead",
    file: TxIconFilled.IconManHead,
    description: "ManHead",
    category: "Filled",
  },
  {
    name: "MapMarkerCross",
    file: TxIconFilled.IconMapMarkerCross,
    description: "MapMarkerCross",
    category: "Filled",
  },
  {
    name: "MapMarkerHome",
    file: TxIconFilled.IconMapMarkerHome,
    description: "MapMarkerHome",
    category: "Filled",
  },
  {
    name: "MapMarkerMinus",
    file: TxIconFilled.IconMapMarkerMinus,
    description: "MapMarkerMinus",
    category: "Filled",
  },
  {
    name: "MapMarkerPlus",
    file: TxIconFilled.IconMapMarkerPlus,
    description: "MapMarkerPlus",
    category: "Filled",
  },
  {
    name: "MapMarker",
    file: TxIconFilled.IconMapMarker,
    description: "MapMarker",
    category: "Filled",
  },
  {
    name: "Map",
    file: TxIconFilled.IconMap,
    description: "Map",
    category: "Filled",
  },
  {
    name: "MarkerTime",
    file: TxIconFilled.IconMarkerTime,
    description: "MarkerTime",
    category: "Filled",
  },
  {
    name: "Marker",
    file: TxIconFilled.IconMarker,
    description: "Marker",
    category: "Filled",
  },
  {
    name: "MarsDouble",
    file: TxIconFilled.IconMarsDouble,
    description: "MarsDouble",
    category: "Filled",
  },
  {
    name: "Mars",
    file: TxIconFilled.IconMars,
    description: "Mars",
    category: "Filled",
  },
  {
    name: "MaskCarnival",
    file: TxIconFilled.IconMaskCarnival,
    description: "MaskCarnival",
    category: "Filled",
  },
  {
    name: "Medicine",
    file: TxIconFilled.IconMedicine,
    description: "Medicine",
    category: "Filled",
  },
  {
    name: "Megaphone",
    file: TxIconFilled.IconMegaphone,
    description: "Megaphone",
    category: "Filled",
  },
  {
    name: "Meh",
    file: TxIconFilled.IconMeh,
    description: "Meh",
    category: "Filled",
  },
  {
    name: "MenuBurger",
    file: TxIconFilled.IconMenuBurger,
    description: "MenuBurger",
    category: "Filled",
  },
  {
    name: "MenuDotsVertical",
    file: TxIconFilled.IconMenuDotsVertical,
    description: "MenuDotsVertical",
    category: "Filled",
  },
  {
    name: "MenuDots",
    file: TxIconFilled.IconMenuDots,
    description: "MenuDots",
    category: "Filled",
  },
  {
    name: "MicrophoneAlt",
    file: TxIconFilled.IconMicrophoneAlt,
    description: "MicrophoneAlt",
    category: "Filled",
  },
  {
    name: "Microphone",
    file: TxIconFilled.IconMicrophone,
    description: "Microphone",
    category: "Filled",
  },
  {
    name: "MinusSmall",
    file: TxIconFilled.IconMinusSmall,
    description: "MinusSmall",
    category: "Filled",
  },
  {
    name: "Minus",
    file: TxIconFilled.IconMinus,
    description: "Minus",
    category: "Filled",
  },
  {
    name: "Mobile",
    file: TxIconFilled.IconMobile,
    description: "Mobile",
    category: "Filled",
  },
  {
    name: "ModeLandscape",
    file: TxIconFilled.IconModeLandscape,
    description: "ModeLandscape",
    category: "Filled",
  },
  {
    name: "ModePortrait",
    file: TxIconFilled.IconModePortrait,
    description: "ModePortrait",
    category: "Filled",
  },
  {
    name: "Money",
    file: TxIconFilled.IconMoney,
    description: "Money",
    category: "Filled",
  },
  {
    name: "Moon",
    file: TxIconFilled.IconMoon,
    description: "Moon",
    category: "Filled",
  },
  {
    name: "Mountains",
    file: TxIconFilled.IconMountains,
    description: "Mountains",
    category: "Filled",
  },
  {
    name: "Mouse",
    file: TxIconFilled.IconMouse,
    description: "Mouse",
    category: "Filled",
  },
  {
    name: "MugAlt",
    file: TxIconFilled.IconMugAlt,
    description: "MugAlt",
    category: "Filled",
  },
  {
    name: "MusicAlt",
    file: TxIconFilled.IconMusicAlt,
    description: "MusicAlt",
    category: "Filled",
  },
  {
    name: "Music",
    file: TxIconFilled.IconMusic,
    description: "Music",
    category: "Filled",
  },
  {
    name: "Navigation",
    file: TxIconFilled.IconNavigation,
    description: "Navigation",
    category: "Filled",
  },
  {
    name: "NetworkCloud",
    file: TxIconFilled.IconNetworkCloud,
    description: "NetworkCloud",
    category: "Filled",
  },
  {
    name: "Network",
    file: TxIconFilled.IconNetwork,
    description: "Network",
    category: "Filled",
  },
  {
    name: "Notebook",
    file: TxIconFilled.IconNotebook,
    description: "Notebook",
    category: "Filled",
  },
  {
    name: "Opacity",
    file: TxIconFilled.IconOpacity,
    description: "Opacity",
    category: "Filled",
  },
  {
    name: "Package",
    file: TxIconFilled.IconPackage,
    description: "Package",
    category: "Filled",
  },
  {
    name: "PaintBrush",
    file: TxIconFilled.IconPaintBrush,
    description: "PaintBrush",
    category: "Filled",
  },
  {
    name: "Palette",
    file: TxIconFilled.IconPalette,
    description: "Palette",
    category: "Filled",
  },
  {
    name: "PaperPlane",
    file: TxIconFilled.IconPaperPlane,
    description: "PaperPlane",
    category: "Filled",
  },
  {
    name: "Password",
    file: TxIconFilled.IconPassword,
    description: "Password",
    category: "Filled",
  },
  {
    name: "Pause",
    file: TxIconFilled.IconPause,
    description: "Pause",
    category: "Filled",
  },
  {
    name: "Paw",
    file: TxIconFilled.IconPaw,
    description: "Paw",
    category: "Filled",
  },
  {
    name: "Pencil",
    file: TxIconFilled.IconPencil,
    description: "Pencil",
    category: "Filled",
  },
  {
    name: "Pharmacy",
    file: TxIconFilled.IconPharmacy,
    description: "Pharmacy",
    category: "Filled",
  },
  {
    name: "PhoneCall",
    file: TxIconFilled.IconPhoneCall,
    description: "PhoneCall",
    category: "Filled",
  },
  {
    name: "PhoneCross",
    file: TxIconFilled.IconPhoneCross,
    description: "PhoneCross",
    category: "Filled",
  },
  {
    name: "PhonePause",
    file: TxIconFilled.IconPhonePause,
    description: "PhonePause",
    category: "Filled",
  },
  {
    name: "PhoneSlash",
    file: TxIconFilled.IconPhoneSlash,
    description: "PhoneSlash",
    category: "Filled",
  },
  {
    name: "Physics",
    file: TxIconFilled.IconPhysics,
    description: "Physics",
    category: "Filled",
  },
  {
    name: "Picture",
    file: TxIconFilled.IconPicture,
    description: "Picture",
    category: "Filled",
  },
  {
    name: "PingPong",
    file: TxIconFilled.IconPingPong,
    description: "PingPong",
    category: "Filled",
  },
  {
    name: "PizzaSlice",
    file: TxIconFilled.IconPizzaSlice,
    description: "PizzaSlice",
    category: "Filled",
  },
  {
    name: "Plane",
    file: TxIconFilled.IconPlane,
    description: "Plane",
    category: "Filled",
  },
  {
    name: "PlayAlt",
    file: TxIconFilled.IconPlayAlt,
    description: "PlayAlt",
    category: "Filled",
  },
  {
    name: "Play",
    file: TxIconFilled.IconPlay,
    description: "Play",
    category: "Filled",
  },
  {
    name: "PlayingCards",
    file: TxIconFilled.IconPlayingCards,
    description: "PlayingCards",
    category: "Filled",
  },
  {
    name: "PlusSmall",
    file: TxIconFilled.IconPlusSmall,
    description: "PlusSmall",
    category: "Filled",
  },
  {
    name: "Plus",
    file: TxIconFilled.IconPlus,
    description: "Plus",
    category: "Filled",
  },
  {
    name: "PokerChip",
    file: TxIconFilled.IconPokerChip,
    description: "PokerChip",
    category: "Filled",
  },
  {
    name: "Portrait",
    file: TxIconFilled.IconPortrait,
    description: "Portrait",
    category: "Filled",
  },
  {
    name: "Pound",
    file: TxIconFilled.IconPound,
    description: "Pound",
    category: "Filled",
  },
  {
    name: "Power",
    file: TxIconFilled.IconPower,
    description: "Power",
    category: "Filled",
  },
  {
    name: "Presentation",
    file: TxIconFilled.IconPresentation,
    description: "Presentation",
    category: "Filled",
  },
  {
    name: "Print",
    file: TxIconFilled.IconPrint,
    description: "Print",
    category: "Filled",
  },
  {
    name: "Protractor",
    file: TxIconFilled.IconProtractor,
    description: "Protractor",
    category: "Filled",
  },
  {
    name: "Pulse",
    file: TxIconFilled.IconPulse,
    description: "Pulse",
    category: "Filled",
  },
  {
    name: "Pyramid",
    file: TxIconFilled.IconPyramid,
    description: "Pyramid",
    category: "Filled",
  },
  {
    name: "QuoteRight",
    file: TxIconFilled.IconQuoteRight,
    description: "QuoteRight",
    category: "Filled",
  },
  {
    name: "Rainbow",
    file: TxIconFilled.IconRainbow,
    description: "Rainbow",
    category: "Filled",
  },
  {
    name: "Raindrops",
    file: TxIconFilled.IconRaindrops,
    description: "Raindrops",
    category: "Filled",
  },
  {
    name: "Rec",
    file: TxIconFilled.IconRec,
    description: "Rec",
    category: "Filled",
  },
  {
    name: "Receipt",
    file: TxIconFilled.IconReceipt,
    description: "Receipt",
    category: "Filled",
  },
  {
    name: "RecordVinyl",
    file: TxIconFilled.IconRecordVinyl,
    description: "RecordVinyl",
    category: "Filled",
  },
  {
    name: "RectabgleVertical",
    file: TxIconFilled.IconRectabgleVertical,
    description: "RectabgleVertical",
    category: "Filled",
  },
  {
    name: "RectangleHorizontal",
    file: TxIconFilled.IconRectangleHorizontal,
    description: "RectangleHorizontal",
    category: "Filled",
  },
  {
    name: "RectanglePanoramic",
    file: TxIconFilled.IconRectanglePanoramic,
    description: "RectanglePanoramic",
    category: "Filled",
  },
  {
    name: "Recycle",
    file: TxIconFilled.IconRecycle,
    description: "Recycle",
    category: "Filled",
  },
  {
    name: "RedoAlt",
    file: TxIconFilled.IconRedoAlt,
    description: "RedoAlt",
    category: "Filled",
  },
  {
    name: "Redo",
    file: TxIconFilled.IconRedo,
    description: "Redo",
    category: "Filled",
  },
  {
    name: "Reflect",
    file: TxIconFilled.IconReflect,
    description: "Reflect",
    category: "Filled",
  },
  {
    name: "Refresh",
    file: TxIconFilled.IconRefresh,
    description: "Refresh",
    category: "Filled",
  },
  {
    name: "Resize",
    file: TxIconFilled.IconResize,
    description: "Resize",
    category: "Filled",
  },
  {
    name: "Resources",
    file: TxIconFilled.IconResources,
    description: "Resources",
    category: "Filled",
  },
  {
    name: "Rewind",
    file: TxIconFilled.IconRewind,
    description: "Rewind",
    category: "Filled",
  },
  {
    name: "Rhombus",
    file: TxIconFilled.IconRhombus,
    description: "Rhombus",
    category: "Filled",
  },
  {
    name: "RingsWedding",
    file: TxIconFilled.IconRingsWedding,
    description: "RingsWedding",
    category: "Filled",
  },
  {
    name: "Road",
    file: TxIconFilled.IconRoad,
    description: "Road",
    category: "Filled",
  },
  {
    name: "Rocket",
    file: TxIconFilled.IconRocket,
    description: "Rocket",
    category: "Filled",
  },
  {
    name: "RoomService",
    file: TxIconFilled.IconRoomService,
    description: "RoomService",
    category: "Filled",
  },
  {
    name: "RotateRight",
    file: TxIconFilled.IconRotateRight,
    description: "RotateRight",
    category: "Filled",
  },
  {
    name: "Rugby",
    file: TxIconFilled.IconRugby,
    description: "Rugby",
    category: "Filled",
  },
  {
    name: "Sad",
    file: TxIconFilled.IconSad,
    description: "Sad",
    category: "Filled",
  },
  {
    name: "Salad",
    file: TxIconFilled.IconSalad,
    description: "Salad",
    category: "Filled",
  },
  {
    name: "Scale",
    file: TxIconFilled.IconScale,
    description: "Scale",
    category: "Filled",
  },
  {
    name: "SchoolBus",
    file: TxIconFilled.IconSchoolBus,
    description: "SchoolBus",
    category: "Filled",
  },
  {
    name: "School",
    file: TxIconFilled.IconSchool,
    description: "School",
    category: "Filled",
  },
  {
    name: "Scissors",
    file: TxIconFilled.IconScissors,
    description: "Scissors",
    category: "Filled",
  },
  {
    name: "Screen",
    file: TxIconFilled.IconScreen,
    description: "Screen",
    category: "Filled",
  },
  {
    name: "SearchAlt",
    file: TxIconFilled.IconSearchAlt,
    description: "SearchAlt",
    category: "Filled",
  },
  {
    name: "SearchHeart",
    file: TxIconFilled.IconSearchHeart,
    description: "SearchHeart",
    category: "Filled",
  },
  {
    name: "Search",
    file: TxIconFilled.IconSearch,
    description: "Search",
    category: "Filled",
  },
  {
    name: "SettingsSliders",
    file: TxIconFilled.IconSettingsSliders,
    description: "SettingsSliders",
    category: "Filled",
  },
  {
    name: "Settings",
    file: TxIconFilled.IconSettings,
    description: "Settings",
    category: "Filled",
  },
  {
    name: "Share",
    file: TxIconFilled.IconShare,
    description: "Share",
    category: "Filled",
  },
  {
    name: "ShieldCheck",
    file: TxIconFilled.IconShieldCheck,
    description: "ShieldCheck",
    category: "Filled",
  },
  {
    name: "ShieldExclamation",
    file: TxIconFilled.IconShieldExclamation,
    description: "ShieldExclamation",
    category: "Filled",
  },
  {
    name: "ShieldInterrogation",
    file: TxIconFilled.IconShieldInterrogation,
    description: "ShieldInterrogation",
    category: "Filled",
  },
  {
    name: "ShieldPlus",
    file: TxIconFilled.IconShieldPlus,
    description: "ShieldPlus",
    category: "Filled",
  },
  {
    name: "Shield",
    file: TxIconFilled.IconShield,
    description: "Shield",
    category: "Filled",
  },
  {
    name: "ShipSide",
    file: TxIconFilled.IconShipSide,
    description: "ShipSide",
    category: "Filled",
  },
  {
    name: "Ship",
    file: TxIconFilled.IconShip,
    description: "Ship",
    category: "Filled",
  },
  {
    name: "Shop",
    file: TxIconFilled.IconShop,
    description: "Shop",
    category: "Filled",
  },
  {
    name: "ShoppingBagAdd",
    file: TxIconFilled.IconShoppingBagAdd,
    description: "ShoppingBagAdd",
    category: "Filled",
  },
  {
    name: "ShoppingBag",
    file: TxIconFilled.IconShoppingBag,
    description: "ShoppingBag",
    category: "Filled",
  },
  {
    name: "ShoppingCartAdd",
    file: TxIconFilled.IconShoppingCartAdd,
    description: "ShoppingCartAdd",
    category: "Filled",
  },
  {
    name: "ShoppingCartCheck",
    file: TxIconFilled.IconShoppingCartCheck,
    description: "ShoppingCartCheck",
    category: "Filled",
  },
  {
    name: "ShoppingCart",
    file: TxIconFilled.IconShoppingCart,
    description: "ShoppingCart",
    category: "Filled",
  },
  {
    name: "Shuffle",
    file: TxIconFilled.IconShuffle,
    description: "Shuffle",
    category: "Filled",
  },
  {
    name: "SignInAlt",
    file: TxIconFilled.IconSignInAlt,
    description: "SignInAlt",
    category: "Filled",
  },
  {
    name: "SignIn",
    file: TxIconFilled.IconSignIn,
    description: "SignIn",
    category: "Filled",
  },
  {
    name: "SignOutAlt",
    file: TxIconFilled.IconSignOutAlt,
    description: "SignOutAlt",
    category: "Filled",
  },
  {
    name: "SignOut",
    file: TxIconFilled.IconSignOut,
    description: "SignOut",
    category: "Filled",
  },
  {
    name: "SignalAlt1",
    file: TxIconFilled.IconSignalAlt1,
    description: "SignalAlt1",
    category: "Filled",
  },
  {
    name: "SignalAlt2",
    file: TxIconFilled.IconSignalAlt2,
    description: "SignalAlt2",
    category: "Filled",
  },
  {
    name: "SignalAlt",
    file: TxIconFilled.IconSignalAlt,
    description: "SignalAlt",
    category: "Filled",
  },
  {
    name: "Skateboard",
    file: TxIconFilled.IconSkateboard,
    description: "Skateboard",
    category: "Filled",
  },
  {
    name: "Smartphone",
    file: TxIconFilled.IconSmartphone,
    description: "Smartphone",
    category: "Filled",
  },
  {
    name: "SmileWink",
    file: TxIconFilled.IconSmileWink,
    description: "SmileWink",
    category: "Filled",
  },
  {
    name: "Smile",
    file: TxIconFilled.IconSmile,
    description: "Smile",
    category: "Filled",
  },
  {
    name: "Snowflake",
    file: TxIconFilled.IconSnowflake,
    description: "Snowflake",
    category: "Filled",
  },
  {
    name: "Soap",
    file: TxIconFilled.IconSoap,
    description: "Soap",
    category: "Filled",
  },
  {
    name: "Soup",
    file: TxIconFilled.IconSoup,
    description: "Soup",
    category: "Filled",
  },
  {
    name: "Spa",
    file: TxIconFilled.IconSpa,
    description: "Spa",
    category: "Filled",
  },
  {
    name: "Speaker",
    file: TxIconFilled.IconSpeaker,
    description: "Speaker",
    category: "Filled",
  },
  {
    name: "Sphere",
    file: TxIconFilled.IconSphere,
    description: "Sphere",
    category: "Filled",
  },
  {
    name: "SpinnerAlt",
    file: TxIconFilled.IconSpinnerAlt,
    description: "SpinnerAlt",
    category: "Filled",
  },
  {
    name: "Spinner",
    file: TxIconFilled.IconSpinner,
    description: "Spinner",
    category: "Filled",
  },
  {
    name: "SquareRoot",
    file: TxIconFilled.IconSquareRoot,
    description: "SquareRoot",
    category: "Filled",
  },
  {
    name: "Square",
    file: TxIconFilled.IconSquare,
    description: "Square",
    category: "Filled",
  },
  {
    name: "StarOctogram",
    file: TxIconFilled.IconStarOctogram,
    description: "StarOctogram",
    category: "Filled",
  },
  {
    name: "Star",
    file: TxIconFilled.IconStar,
    description: "Star",
    category: "Filled",
  },
  {
    name: "Stats",
    file: TxIconFilled.IconStats,
    description: "Stats",
    category: "Filled",
  },
  {
    name: "Stethoscope",
    file: TxIconFilled.IconStethoscope,
    description: "Stethoscope",
    category: "Filled",
  },
  {
    name: "Sticker",
    file: TxIconFilled.IconSticker,
    description: "Sticker",
    category: "Filled",
  },
  {
    name: "Stop",
    file: TxIconFilled.IconStop,
    description: "Stop",
    category: "Filled",
  },
  {
    name: "Stopwatch",
    file: TxIconFilled.IconStopwatch,
    description: "Stopwatch",
    category: "Filled",
  },
  {
    name: "Subtitles",
    file: TxIconFilled.IconSubtitles,
    description: "Subtitles",
    category: "Filled",
  },
  {
    name: "Sun",
    file: TxIconFilled.IconSun,
    description: "Sun",
    category: "Filled",
  },
  {
    name: "Sunrise",
    file: TxIconFilled.IconSunrise,
    description: "Sunrise",
    category: "Filled",
  },
  {
    name: "Surfing",
    file: TxIconFilled.IconSurfing,
    description: "Surfing",
    category: "Filled",
  },
  {
    name: "Sword",
    file: TxIconFilled.IconSword,
    description: "Sword",
    category: "Filled",
  },
  {
    name: "Syringe",
    file: TxIconFilled.IconSyringe,
    description: "Syringe",
    category: "Filled",
  },
  {
    name: "Tablet",
    file: TxIconFilled.IconTablet,
    description: "Tablet",
    category: "Filled",
  },
  {
    name: "Target",
    file: TxIconFilled.IconTarget,
    description: "Target",
    category: "Filled",
  },
  {
    name: "Taxi",
    file: TxIconFilled.IconTaxi,
    description: "Taxi",
    category: "Filled",
  },
  {
    name: "Tennis",
    file: TxIconFilled.IconTennis,
    description: "Tennis",
    category: "Filled",
  },
  {
    name: "Terrace",
    file: TxIconFilled.IconTerrace,
    description: "Terrace",
    category: "Filled",
  },
  {
    name: "TestTube",
    file: TxIconFilled.IconTestTube,
    description: "TestTube",
    category: "Filled",
  },
  {
    name: "Test",
    file: TxIconFilled.IconTest,
    description: "Test",
    category: "Filled",
  },
  {
    name: "TextCheck",
    file: TxIconFilled.IconTextCheck,
    description: "TextCheck",
    category: "Filled",
  },
  {
    name: "Text",
    file: TxIconFilled.IconText,
    description: "Text",
    category: "Filled",
  },
  {
    name: "ThermometerHalf",
    file: TxIconFilled.IconThermometerHalf,
    description: "ThermometerHalf",
    category: "Filled",
  },
  {
    name: "ThumbsDown",
    file: TxIconFilled.IconThumbsDown,
    description: "ThumbsDown",
    category: "Filled",
  },
  {
    name: "ThumbsUp",
    file: TxIconFilled.IconThumbsUp,
    description: "ThumbsUp",
    category: "Filled",
  },
  {
    name: "Thumbtack",
    file: TxIconFilled.IconThumbtack,
    description: "Thumbtack",
    category: "Filled",
  },
  {
    name: "Ticket",
    file: TxIconFilled.IconTicket,
    description: "Ticket",
    category: "Filled",
  },
  {
    name: "TimeAdd",
    file: TxIconFilled.IconTimeAdd,
    description: "TimeAdd",
    category: "Filled",
  },
  {
    name: "TimeCheck",
    file: TxIconFilled.IconTimeCheck,
    description: "TimeCheck",
    category: "Filled",
  },
  {
    name: "TimeDelete",
    file: TxIconFilled.IconTimeDelete,
    description: "TimeDelete",
    category: "Filled",
  },
  {
    name: "TimeFast",
    file: TxIconFilled.IconTimeFast,
    description: "TimeFast",
    category: "Filled",
  },
  {
    name: "TimeForwardSixty",
    file: TxIconFilled.IconTimeForwardSixty,
    description: "TimeForwardSixty",
    category: "Filled",
  },
  {
    name: "TimeForwardTen",
    file: TxIconFilled.IconTimeForwardTen,
    description: "TimeForwardTen",
    category: "Filled",
  },
  {
    name: "TimeForward",
    file: TxIconFilled.IconTimeForward,
    description: "TimeForward",
    category: "Filled",
  },
  {
    name: "TimeHalfPast",
    file: TxIconFilled.IconTimeHalfPast,
    description: "TimeHalfPast",
    category: "Filled",
  },
  {
    name: "TimeOclock",
    file: TxIconFilled.IconTimeOclock,
    description: "TimeOclock",
    category: "Filled",
  },
  {
    name: "TimePast",
    file: TxIconFilled.IconTimePast,
    description: "TimePast",
    category: "Filled",
  },
  {
    name: "TimeQuarterPast",
    file: TxIconFilled.IconTimeQuarterPast,
    description: "TimeQuarterPast",
    category: "Filled",
  },
  {
    name: "TimeQuarterTo",
    file: TxIconFilled.IconTimeQuarterTo,
    description: "TimeQuarterTo",
    category: "Filled",
  },
  {
    name: "TimeTwentyFour",
    file: TxIconFilled.IconTimeTwentyFour,
    description: "TimeTwentyFour",
    category: "Filled",
  },
  {
    name: "ToolCrop",
    file: TxIconFilled.IconToolCrop,
    description: "ToolCrop",
    category: "Filled",
  },
  {
    name: "ToolMarquee",
    file: TxIconFilled.IconToolMarquee,
    description: "ToolMarquee",
    category: "Filled",
  },
  {
    name: "Tooth",
    file: TxIconFilled.IconTooth,
    description: "Tooth",
    category: "Filled",
  },
  {
    name: "Tornado",
    file: TxIconFilled.IconTornado,
    description: "Tornado",
    category: "Filled",
  },
  {
    name: "TrainSide",
    file: TxIconFilled.IconTrainSide,
    description: "TrainSide",
    category: "Filled",
  },
  {
    name: "Train",
    file: TxIconFilled.IconTrain,
    description: "Train",
    category: "Filled",
  },
  {
    name: "Transform",
    file: TxIconFilled.IconTransform,
    description: "Transform",
    category: "Filled",
  },
  {
    name: "Trash",
    file: TxIconFilled.IconTrash,
    description: "Trash",
    category: "Filled",
  },
  {
    name: "Treatment",
    file: TxIconFilled.IconTreatment,
    description: "Treatment",
    category: "Filled",
  },
  {
    name: "TreeChristmas",
    file: TxIconFilled.IconTreeChristmas,
    description: "TreeChristmas",
    category: "Filled",
  },
  {
    name: "Tree",
    file: TxIconFilled.IconTree,
    description: "Tree",
    category: "Filled",
  },
  {
    name: "Triangle",
    file: TxIconFilled.IconTriangle,
    description: "Triangle",
    category: "Filled",
  },
  {
    name: "Trophy",
    file: TxIconFilled.IconTrophy,
    description: "Trophy",
    category: "Filled",
  },
  {
    name: "TruckSide",
    file: TxIconFilled.IconTruckSide,
    description: "TruckSide",
    category: "Filled",
  },
  {
    name: "Umbrella",
    file: TxIconFilled.IconUmbrella,
    description: "Umbrella",
    category: "Filled",
  },
  {
    name: "Underline",
    file: TxIconFilled.IconUnderline,
    description: "Underline",
    category: "Filled",
  },
  {
    name: "UndoAlt",
    file: TxIconFilled.IconUndoAlt,
    description: "UndoAlt",
    category: "Filled",
  },
  {
    name: "Undo",
    file: TxIconFilled.IconUndo,
    description: "Undo",
    category: "Filled",
  },
  {
    name: "Unlock",
    file: TxIconFilled.IconUnlock,
    description: "Unlock",
    category: "Filled",
  },
  {
    name: "Upload",
    file: TxIconFilled.IconUpload,
    description: "Upload",
    category: "Filled",
  },
  {
    name: "UsbPendrive",
    file: TxIconFilled.IconUsbPendrive,
    description: "UsbPendrive",
    category: "Filled",
  },
  {
    name: "UserAdd",
    file: TxIconFilled.IconUserAdd,
    description: "UserAdd",
    category: "Filled",
  },
  {
    name: "UserDelete",
    file: TxIconFilled.IconUserDelete,
    description: "UserDelete",
    category: "Filled",
  },
  {
    name: "UserRemove",
    file: TxIconFilled.IconUserRemove,
    description: "UserRemove",
    category: "Filled",
  },
  {
    name: "UserTime",
    file: TxIconFilled.IconUserTime,
    description: "UserTime",
    category: "Filled",
  },
  {
    name: "User",
    file: TxIconFilled.IconUser,
    description: "User",
    category: "Filled",
  },
  {
    name: "Utensils",
    file: TxIconFilled.IconUtensils,
    description: "Utensils",
    category: "Filled",
  },
  {
    name: "VectorAlt",
    file: TxIconFilled.IconVectorAlt,
    description: "VectorAlt",
    category: "Filled",
  },
  {
    name: "Vector",
    file: TxIconFilled.IconVector,
    description: "Vector",
    category: "Filled",
  },
  {
    name: "VenusDouble",
    file: TxIconFilled.IconVenusDouble,
    description: "VenusDouble",
    category: "Filled",
  },
  {
    name: "VenusMars",
    file: TxIconFilled.IconVenusMars,
    description: "VenusMars",
    category: "Filled",
  },
  {
    name: "Venus",
    file: TxIconFilled.IconVenus,
    description: "Venus",
    category: "Filled",
  },
  {
    name: "VideoCamera",
    file: TxIconFilled.IconVideoCamera,
    description: "VideoCamera",
    category: "Filled",
  },
  {
    name: "Volleyball",
    file: TxIconFilled.IconVolleyball,
    description: "Volleyball",
    category: "Filled",
  },
  {
    name: "Volume",
    file: TxIconFilled.IconVolume,
    description: "Volume",
    category: "Filled",
  },
  {
    name: "Wheelchair",
    file: TxIconFilled.IconWheelchair,
    description: "Wheelchair",
    category: "Filled",
  },
  {
    name: "WifiAlt",
    file: TxIconFilled.IconWifiAlt,
    description: "WifiAlt",
    category: "Filled",
  },
  {
    name: "Wind",
    file: TxIconFilled.IconWind,
    description: "Wind",
    category: "Filled",
  },
  {
    name: "WomanHead",
    file: TxIconFilled.IconWomanHead,
    description: "WomanHead",
    category: "Filled",
  },
  {
    name: "World",
    file: TxIconFilled.IconWorld,
    description: "World",
    category: "Filled",
  },
  {
    name: "Yen",
    file: TxIconFilled.IconYen,
    description: "Yen",
    category: "Filled",
  },
  {
    name: "ZoomIn",
    file: TxIconFilled.IconZoomIn,
    description: "ZoomIn",
    category: "Filled",
  },
  {
    name: "ZoomOut",
    file: TxIconFilled.IconZoomOut,
    description: "ZoomOut",
    category: "Filled",
  },
];

function IconListTemplate({ variant = "Filled" }) {
  const [searchQuery, setSearchQuery] = useState("");

  const filteredIcons = iconData.filter(
    icon =>
      icon.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      icon.description.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div style={{ margin: "0 auto" }}>
      {/* Search Input */}
      <div style={{ marginBottom: "24px" }}>
        <input
          type="text"
          placeholder={`Search ${iconData.length} icons by name...`}
          value={searchQuery}
          onChange={e => setSearchQuery(e.target.value)}
          style={{
            width: "100%",
            padding: "14px 18px",
            border: "1px solid #e0e0e0",
            borderRadius: "8px",
            fontSize: "15px",
            Filled: "none",
            transition: "border-color 0.2s",
          }}
          onFocus={e => {
            e.target.style.borderColor = "#00bcff";
          }}
          onBlur={e => {
            e.target.style.borderColor = "#e0e0e0";
          }}
        />
      </div>

      {/* Results count */}
      <div style={{ marginBottom: "16px", fontSize: "14px", color: "#666" }}>
        Showing {filteredIcons.length} of {iconData.length} icons
      </div>

      {/* Icons Grid */}
      {filteredIcons.length > 0 ? (
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fill, minmax(110px, 1fr))",
            gap: "8px",
          }}
        >
          {filteredIcons.map(icon => (
            <div
              key={icon.name}
              style={{
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                gap: "8px",
                padding: "12px",
                background: "#ffffff",
                border: "1px solid #e0e0e0",
                borderRadius: "12px",
                transition: "all 0.2s",
                cursor: "pointer",
              }}
              onMouseEnter={e => {
                e.currentTarget.style.transform = "translateY(-4px)";
                e.currentTarget.style.boxShadow = "0 8px 16px rgba(0, 0, 0, 0.1)";
                e.currentTarget.style.borderColor = "#00bcff";
              }}
              onMouseLeave={e => {
                e.currentTarget.style.transform = "translateY(0)";
                e.currentTarget.style.boxShadow = "none";
                e.currentTarget.style.borderColor = "#e0e0e0";
              }}
            >
              {/* Icon Display */}
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  width: "40px",
                  height: "40px",
                  background: "#f5f5f5",
                  borderRadius: "12px",
                  marginBottom: "4px",
                }}
              >
                <img src={icon.file} alt={icon.name} style={{ width: "16px", height: "16px", objectFit: "contain" }} />
              </div>

              {/* Icon Info */}
              <div style={{ textAlign: "center", width: "100%" }}>
                <span
                  style={{
                    display: "block",
                    marginBottom: "4px",
                    fontSize: "11px",
                    color: "#1a1a1a",
                    lineHeight: "1.2",
                    fontWeight: "500",
                  }}
                >
                  {icon.name}
                </span>
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div style={{ textAlign: "center", padding: "60px", color: "#888" }}>
          <p style={{ fontSize: "16px" }}>No icons found matching "{searchQuery}"</p>
          <p style={{ fontSize: "14px", marginTop: "8px" }}>Try a different search term</p>
        </div>
      )}
    </div>
  );
}

// Story for Filled icons
export const Filled = {
  render: () => <IconListTemplate variant="filled" />,
};
