import { useState } from "react";
import { TxIconOutline } from "../assets/icons/outline";

const TxIconOutlineStory = {
  title: "tx-design-ui/Foundation/TxIcon/TxIconOutline",
  component: "TxIcon",
  parameters: {
    layout: "fullscreen",
  },
};
export default TxIconOutlineStory;

const iconData = [
  {
    name: "IconAdd",
    file: TxIconOutline.IconAdd,
    description: "IconAdd",
    category: "Outline",
  },
  {
    name: "IconAddressBook",
    file: TxIconOutline.IconAddressBook,
    description: "IconAddressBook",
    category: "Outline",
  },
  {
    name: "IconAlarmClock",
    file: TxIconOutline.IconAlarmClock,
    description: "IconAlarmClock",
    category: "Outline",
  },
  {
    name: "IconAlignCenter",
    file: TxIconOutline.IconAlignCenter,
    description: "IconAlignCenter",
    category: "Outline",
  },
  {
    name: "IconAlignJustify",
    file: TxIconOutline.IconAlignJustify,
    description: "IconAlignJustify",
    category: "Outline",
  },
  {
    name: "IconAlignLeft",
    file: TxIconOutline.IconAlignLeft,
    description: "IconAlignLeft",
    category: "Outline",
  },
  {
    name: "IconAlignRight",
    file: TxIconOutline.IconAlignRight,
    description: "IconAlignRight",
    category: "Outline",
  },
  {
    name: "IconAmbulance",
    file: TxIconOutline.IconAmbulance,
    description: "IconAmbulance",
    category: "Outline",
  },
  {
    name: "IconAngleDoubleLeft",
    file: TxIconOutline.IconAngleDoubleLeft,
    description: "IconAngleDoubleLeft",
    category: "Outline",
  },
  {
    name: "IconAngleDoubleRight",
    file: TxIconOutline.IconAngleDoubleRight,
    description: "IconAngleDoubleRight",
    category: "Outline",
  },
  {
    name: "IconAngleDoubleSmallLeft",
    file: TxIconOutline.IconAngleDoubleSmallLeft,
    description: "IconAngleDoubleSmallLeft",
    category: "Outline",
  },
  {
    name: "IconAngleDoubleSmallRight",
    file: TxIconOutline.IconAngleDoubleSmallRight,
    description: "IconAngleDoubleSmallRight",
    category: "Outline",
  },
  {
    name: "IconAngleDown",
    file: TxIconOutline.IconAngleDown,
    description: "IconAngleDown",
    category: "Outline",
  },
  {
    name: "IconAngleLeft",
    file: TxIconOutline.IconAngleLeft,
    description: "IconAngleLeft",
    category: "Outline",
  },
  {
    name: "IconAngleRight",
    file: TxIconOutline.IconAngleRight,
    description: "IconAngleRight",
    category: "Outline",
  },
  {
    name: "IconAngleSmallDown",
    file: TxIconOutline.IconAngleSmallDown,
    description: "IconAngleSmallDown",
    category: "Outline",
  },
  {
    name: "IconAngleSmallLeft",
    file: TxIconOutline.IconAngleSmallLeft,
    description: "IconAngleSmallLeft",
    category: "Outline",
  },
  {
    name: "IconAngleSmallRight",
    file: TxIconOutline.IconAngleSmallRight,
    description: "IconAngleSmallRight",
    category: "Outline",
  },
  {
    name: "IconAngleSmallUp",
    file: TxIconOutline.IconAngleSmallUp,
    description: "IconAngleSmallUp",
    category: "Outline",
  },
  {
    name: "IconAngleUp",
    file: TxIconOutline.IconAngleUp,
    description: "IconAngleUp",
    category: "Outline",
  },
  {
    name: "IconApple",
    file: TxIconOutline.IconApple,
    description: "IconApple",
    category: "Outline",
  },
  {
    name: "IconAppsAdd",
    file: TxIconOutline.IconAppsAdd,
    description: "IconAppsAdd",
    category: "Outline",
  },
  {
    name: "IconAppsDelete",
    file: TxIconOutline.IconAppsDelete,
    description: "IconAppsDelete",
    category: "Outline",
  },
  {
    name: "IconAppsSort",
    file: TxIconOutline.IconAppsSort,
    description: "IconAppsSort",
    category: "Outline",
  },
  {
    name: "IconApps",
    file: TxIconOutline.IconApps,
    description: "IconApps",
    category: "Outline",
  },
  {
    name: "IconArchive",
    file: TxIconOutline.IconArchive,
    description: "IconArchive",
    category: "Outline",
  },
  {
    name: "IconArrowDown",
    file: TxIconOutline.IconArrowDown,
    description: "IconArrowDown",
    category: "Outline",
  },
  {
    name: "IconArrowFromBottom",
    file: TxIconOutline.IconArrowFromBottom,
    description: "IconArrowFromBottom",
    category: "Outline",
  },
  {
    name: "IconArrowLeft",
    file: TxIconOutline.IconArrowLeft,
    description: "IconArrowLeft",
    category: "Outline",
  },
  {
    name: "IconArrowRight",
    file: TxIconOutline.IconArrowRight,
    description: "IconArrowRight",
    category: "Outline",
  },
  {
    name: "IconArrowSmallDown",
    file: TxIconOutline.IconArrowSmallDown,
    description: "IconArrowSmallDown",
    category: "Outline",
  },
  {
    name: "IconArrowSmallLeft",
    file: TxIconOutline.IconArrowSmallLeft,
    description: "IconArrowSmallLeft",
    category: "Outline",
  },
  {
    name: "IconArrowSmallRight",
    file: TxIconOutline.IconArrowSmallRight,
    description: "IconArrowSmallRight",
    category: "Outline",
  },
  {
    name: "IconArrowSmallUp",
    file: TxIconOutline.IconArrowSmallUp,
    description: "IconArrowSmallUp",
    category: "Outline",
  },
  {
    name: "IconArrowUp",
    file: TxIconOutline.IconArrowUp,
    description: "IconArrowUp",
    category: "Outline",
  },
  {
    name: "IconAsterik",
    file: TxIconOutline.IconAsterik,
    description: "IconAsterik",
    category: "Outline",
  },
  {
    name: "IconAt",
    file: TxIconOutline.IconAt,
    description: "IconAt",
    category: "Outline",
  },
  {
    name: "IconBackpack",
    file: TxIconOutline.IconBackpack,
    description: "IconBackpack",
    category: "Outline",
  },
  {
    name: "IconBadge",
    file: TxIconOutline.IconBadge,
    description: "IconBadge",
    category: "Outline",
  },
  {
    name: "IconBalloons",
    file: TxIconOutline.IconBalloons,
    description: "IconBalloons",
    category: "Outline",
  },
  {
    name: "IconBan",
    file: TxIconOutline.IconBan,
    description: "IconBan",
    category: "Outline",
  },
  {
    name: "IconBandAid",
    file: TxIconOutline.IconBandAid,
    description: "IconBandAid",
    category: "Outline",
  },
  {
    name: "IconBank",
    file: TxIconOutline.IconBank,
    description: "IconBank",
    category: "Outline",
  },
  {
    name: "IconBarberShop",
    file: TxIconOutline.IconBarberShop,
    description: "IconBarberShop",
    category: "Outline",
  },
  {
    name: "IconBaseball",
    file: TxIconOutline.IconBaseball,
    description: "IconBaseball",
    category: "Outline",
  },
  {
    name: "IconBasketball",
    file: TxIconOutline.IconBasketball,
    description: "IconBasketball",
    category: "Outline",
  },
  {
    name: "IconBed",
    file: TxIconOutline.IconBed,
    description: "IconBed",
    category: "Outline",
  },
  {
    name: "IconBeer",
    file: TxIconOutline.IconBeer,
    description: "IconBeer",
    category: "Outline",
  },
  {
    name: "IconBellRing",
    file: TxIconOutline.IconBellRing,
    description: "IconBellRing",
    category: "Outline",
  },
  {
    name: "IconBellSchool",
    file: TxIconOutline.IconBellSchool,
    description: "IconBellSchool",
    category: "Outline",
  },
  {
    name: "IconBell",
    file: TxIconOutline.IconBell,
    description: "IconBell",
    category: "Outline",
  },
  {
    name: "IconBike",
    file: TxIconOutline.IconBike,
    description: "IconBike",
    category: "Outline",
  },
  {
    name: "IconBilliard",
    file: TxIconOutline.IconBilliard,
    description: "IconBilliard",
    category: "Outline",
  },
  {
    name: "IconBold",
    file: TxIconOutline.IconBold,
    description: "IconBold",
    category: "Outline",
  },
  {
    name: "IconBookAlt",
    file: TxIconOutline.IconBookAlt,
    description: "IconBookAlt",
    category: "Outline",
  },
  {
    name: "IconBook",
    file: TxIconOutline.IconBook,
    description: "IconBook",
    category: "Outline",
  },
  {
    name: "IconBookmark",
    file: TxIconOutline.IconBookmark,
    description: "IconBookmark",
    category: "Outline",
  },
  {
    name: "IconBowling",
    file: TxIconOutline.IconBowling,
    description: "IconBowling",
    category: "Outline",
  },
  {
    name: "IconBoxAlt",
    file: TxIconOutline.IconBoxAlt,
    description: "IconBoxAlt",
    category: "Outline",
  },
  {
    name: "IconBox",
    file: TxIconOutline.IconBox,
    description: "IconBox",
    category: "Outline",
  },
  {
    name: "IconBreadSlice",
    file: TxIconOutline.IconBreadSlice,
    description: "IconBreadSlice",
    category: "Outline",
  },
  {
    name: "IconBriefcase",
    file: TxIconOutline.IconBriefcase,
    description: "IconBriefcase",
    category: "Outline",
  },
  {
    name: "IconBroom",
    file: TxIconOutline.IconBroom,
    description: "IconBroom",
    category: "Outline",
  },
  {
    name: "IconBrowser",
    file: TxIconOutline.IconBrowser,
    description: "IconBrowser",
    category: "Outline",
  },
  {
    name: "IconBrush",
    file: TxIconOutline.IconBrush,
    description: "IconBrush",
    category: "Outline",
  },
  {
    name: "IconBug",
    file: TxIconOutline.IconBug,
    description: "IconBug",
    category: "Outline",
  },
  {
    name: "IconBuilding",
    file: TxIconOutline.IconBuilding,
    description: "IconBuilding",
    category: "Outline",
  },
  {
    name: "IconBulb",
    file: TxIconOutline.IconBulb,
    description: "IconBulb",
    category: "Outline",
  },
  {
    name: "IconButterfly",
    file: TxIconOutline.IconButterfly,
    description: "IconButterfly",
    category: "Outline",
  },
  {
    name: "IconCakeBirthday",
    file: TxIconOutline.IconCakeBirthday,
    description: "IconCakeBirthday",
    category: "Outline",
  },
  {
    name: "IconCakeWedding",
    file: TxIconOutline.IconCakeWedding,
    description: "IconCakeWedding",
    category: "Outline",
  },
  {
    name: "IconCalculator",
    file: TxIconOutline.IconCalculator,
    description: "IconCalculator",
    category: "Outline",
  },
  {
    name: "IconCalendar",
    file: TxIconOutline.IconCalendar,
    description: "IconCalendar",
    category: "Outline",
  },
  {
    name: "IconCallHistory",
    file: TxIconOutline.IconCallHistory,
    description: "IconCallHistory",
    category: "Outline",
  },
  {
    name: "IconCallIncoming",
    file: TxIconOutline.IconCallIncoming,
    description: "IconCallIncoming",
    category: "Outline",
  },
  {
    name: "IconCallMissed",
    file: TxIconOutline.IconCallMissed,
    description: "IconCallMissed",
    category: "Outline",
  },
  {
    name: "IconCallOutgoing",
    file: TxIconOutline.IconCallOutgoing,
    description: "IconCallOutgoing",
    category: "Outline",
  },
  {
    name: "IconCamera",
    file: TxIconOutline.IconCamera,
    description: "IconCamera",
    category: "Outline",
  },
  {
    name: "IconCamping",
    file: TxIconOutline.IconCamping,
    description: "IconCamping",
    category: "Outline",
  },
  {
    name: "IconCar",
    file: TxIconOutline.IconCar,
    description: "IconCar",
    category: "Outline",
  },
  {
    name: "IconCaretDown",
    file: TxIconOutline.IconCaretDown,
    description: "IconCaretDown",
    category: "Outline",
  },
  {
    name: "IconCaretLeft",
    file: TxIconOutline.IconCaretLeft,
    description: "IconCaretLeft",
    category: "Outline",
  },
  {
    name: "IconCaretRight",
    file: TxIconOutline.IconCaretRight,
    description: "IconCaretRight",
    category: "Outline",
  },
  {
    name: "IconCaretUp",
    file: TxIconOutline.IconCaretUp,
    description: "IconCaretUp",
    category: "Outline",
  },
  {
    name: "IconCarrot",
    file: TxIconOutline.IconCarrot,
    description: "IconCarrot",
    category: "Outline",
  },
  {
    name: "IconChartConnected",
    file: TxIconOutline.IconChartConnected,
    description: "IconChartConnected",
    category: "Outline",
  },
  {
    name: "IconChartHistogram",
    file: TxIconOutline.IconChartHistogram,
    description: "IconChartHistogram",
    category: "Outline",
  },
  {
    name: "IconChartNetwork",
    file: TxIconOutline.IconChartNetwork,
    description: "IconChartNetwork",
    category: "Outline",
  },
  {
    name: "IconChartPieAlt",
    file: TxIconOutline.IconChartPieAlt,
    description: "IconChartPieAlt",
    category: "Outline",
  },
  {
    name: "IconChartPie",
    file: TxIconOutline.IconChartPie,
    description: "IconChartPie",
    category: "Outline",
  },
  {
    name: "IconChartPyramid",
    file: TxIconOutline.IconChartPyramid,
    description: "IconChartPyramid",
    category: "Outline",
  },
  {
    name: "IconChartSetTheory",
    file: TxIconOutline.IconChartSetTheory,
    description: "IconChartSetTheory",
    category: "Outline",
  },
  {
    name: "IconChartTree",
    file: TxIconOutline.IconChartTree,
    description: "IconChartTree",
    category: "Outline",
  },
  {
    name: "IconChatArrowDown",
    file: TxIconOutline.IconChatArrowDown,
    description: "IconChatArrowDown",
    category: "Outline",
  },
  {
    name: "IconChatArrowGrow",
    file: TxIconOutline.IconChatArrowGrow,
    description: "IconChatArrowGrow",
    category: "Outline",
  },
  {
    name: "IconCheck",
    file: TxIconOutline.IconCheck,
    description: "IconCheck",
    category: "Outline",
  },
  {
    name: "IconCheckbox",
    file: TxIconOutline.IconCheckbox,
    description: "IconCheckbox",
    category: "Outline",
  },
  {
    name: "IconCheese",
    file: TxIconOutline.IconCheese,
    description: "IconCheese",
    category: "Outline",
  },
  {
    name: "IconChessPiece",
    file: TxIconOutline.IconChessPiece,
    description: "IconChessPiece",
    category: "Outline",
  },
  {
    name: "IconChildHead",
    file: TxIconOutline.IconChildHead,
    description: "IconChildHead",
    category: "Outline",
  },
  {
    name: "IconCircleSmall",
    file: TxIconOutline.IconCircleSmall,
    description: "IconCircleSmall",
    category: "Outline",
  },
  {
    name: "IconCircle",
    file: TxIconOutline.IconCircle,
    description: "IconCircle",
    category: "Outline",
  },
  {
    name: "IconClip",
    file: TxIconOutline.IconClip,
    description: "IconClip",
    category: "Outline",
  },
  {
    name: "IconClock",
    file: TxIconOutline.IconClock,
    description: "IconClock",
    category: "Outline",
  },
  {
    name: "IconCloudCheck",
    file: TxIconOutline.IconCloudCheck,
    description: "IconCloudCheck",
    category: "Outline",
  },
  {
    name: "IconCloudDisabled",
    file: TxIconOutline.IconCloudDisabled,
    description: "IconCloudDisabled",
    category: "Outline",
  },
  {
    name: "IconCloudDownload",
    file: TxIconOutline.IconCloudDownload,
    description: "IconCloudDownload",
    category: "Outline",
  },
  {
    name: "IconCloudShare",
    file: TxIconOutline.IconCloudShare,
    description: "IconCloudShare",
    category: "Outline",
  },
  {
    name: "IconCloudUpload",
    file: TxIconOutline.IconCloudUpload,
    description: "IconCloudUpload",
    category: "Outline",
  },
  {
    name: "IconCloud",
    file: TxIconOutline.IconCloud,
    description: "IconCloud",
    category: "Outline",
  },
  {
    name: "IconClouds",
    file: TxIconOutline.IconClouds,
    description: "IconClouds",
    category: "Outline",
  },
  {
    name: "IconCocktail",
    file: TxIconOutline.IconCocktail,
    description: "IconCocktail",
    category: "Outline",
  },
  {
    name: "IconCoffee",
    file: TxIconOutline.IconCoffee,
    description: "IconCoffee",
    category: "Outline",
  },
  {
    name: "IconCommentAlt",
    file: TxIconOutline.IconCommentAlt,
    description: "IconCommentAlt",
    category: "Outline",
  },
  {
    name: "IconCommentCheck",
    file: TxIconOutline.IconCommentCheck,
    description: "IconCommentCheck",
    category: "Outline",
  },
  {
    name: "IconCommentHeart",
    file: TxIconOutline.IconCommentHeart,
    description: "IconCommentHeart",
    category: "Outline",
  },
  {
    name: "IconCommentInfo",
    file: TxIconOutline.IconCommentInfo,
    description: "IconCommentInfo",
    category: "Outline",
  },
  {
    name: "IconCommentUser",
    file: TxIconOutline.IconCommentUser,
    description: "IconCommentUser",
    category: "Outline",
  },
  {
    name: "IconComment",
    file: TxIconOutline.IconComment,
    description: "IconComment",
    category: "Outline",
  },
  {
    name: "IconComments",
    file: TxIconOutline.IconComments,
    description: "IconComments",
    category: "Outline",
  },
  {
    name: "IconCompressAlt",
    file: TxIconOutline.IconCompressAlt,
    description: "IconCompressAlt",
    category: "Outline",
  },
  {
    name: "IconCompress",
    file: TxIconOutline.IconCompress,
    description: "IconCompress",
    category: "Outline",
  },
  {
    name: "IconComputer",
    file: TxIconOutline.IconComputer,
    description: "IconComputer",
    category: "Outline",
  },
  {
    name: "IconConfetti",
    file: TxIconOutline.IconConfetti,
    description: "IconConfetti",
    category: "Outline",
  },
  {
    name: "IconCookie",
    file: TxIconOutline.IconCookie,
    description: "IconCookie",
    category: "Outline",
  },
  {
    name: "IconCopyAlt",
    file: TxIconOutline.IconCopyAlt,
    description: "IconCopyAlt",
    category: "Outline",
  },
  {
    name: "IconCopy",
    file: TxIconOutline.IconCopy,
    description: "IconCopy",
    category: "Outline",
  },
  {
    name: "IconCopyright",
    file: TxIconOutline.IconCopyright,
    description: "IconCopyright",
    category: "Outline",
  },
  {
    name: "IconCow",
    file: TxIconOutline.IconCow,
    description: "IconCow",
    category: "Outline",
  },
  {
    name: "IconCream",
    file: TxIconOutline.IconCream,
    description: "IconCream",
    category: "Outline",
  },
  {
    name: "IconCreditCard",
    file: TxIconOutline.IconCreditCard,
    description: "IconCreditCard",
    category: "Outline",
  },
  {
    name: "IconCroissant",
    file: TxIconOutline.IconCroissant,
    description: "IconCroissant",
    category: "Outline",
  },
  {
    name: "IconCrossCircle",
    file: TxIconOutline.IconCrossCircle,
    description: "IconCrossCircle",
    category: "Outline",
  },
  {
    name: "IconCrossSmall",
    file: TxIconOutline.IconCrossSmall,
    description: "IconCrossSmall",
    category: "Outline",
  },
  {
    name: "IconCross",
    file: TxIconOutline.IconCross,
    description: "IconCross",
    category: "Outline",
  },
  {
    name: "IconCrown",
    file: TxIconOutline.IconCrown,
    description: "IconCrown",
    category: "Outline",
  },
  {
    name: "IconCube",
    file: TxIconOutline.IconCube,
    description: "IconCube",
    category: "Outline",
  },
  {
    name: "IconCupcake",
    file: TxIconOutline.IconCupcake,
    description: "IconCupcake",
    category: "Outline",
  },
  {
    name: "IconCursorFinger",
    file: TxIconOutline.IconCursorFinger,
    description: "IconCursorFinger",
    category: "Outline",
  },
  {
    name: "IconCursorPlus",
    file: TxIconOutline.IconCursorPlus,
    description: "IconCursorPlus",
    category: "Outline",
  },
  {
    name: "IconCursorTextAlt",
    file: TxIconOutline.IconCursorTextAlt,
    description: "IconCursorTextAlt",
    category: "Outline",
  },
  {
    name: "IconCursorText",
    file: TxIconOutline.IconCursorText,
    description: "IconCursorText",
    category: "Outline",
  },
  {
    name: "IconCursor",
    file: TxIconOutline.IconCursor,
    description: "IconCursor",
    category: "Outline",
  },
  {
    name: "IconDart",
    file: TxIconOutline.IconDart,
    description: "IconDart",
    category: "Outline",
  },
  {
    name: "IconDashboard",
    file: TxIconOutline.IconDashboard,
    description: "IconDashboard",
    category: "Outline",
  },
  {
    name: "IconDataTransfer",
    file: TxIconOutline.IconDataTransfer,
    description: "IconDataTransfer",
    category: "Outline",
  },
  {
    name: "IconDatabase",
    file: TxIconOutline.IconDatabase,
    description: "IconDatabase",
    category: "Outline",
  },
  {
    name: "IconDelete",
    file: TxIconOutline.IconDelete,
    description: "IconDelete",
    category: "Outline",
  },
  {
    name: "IconDiamond",
    file: TxIconOutline.IconDiamond,
    description: "IconDiamond",
    category: "Outline",
  },
  {
    name: "IconDice",
    file: TxIconOutline.IconDice,
    description: "IconDice",
    category: "Outline",
  },
  {
    name: "IconDiploma",
    file: TxIconOutline.IconDiploma,
    description: "IconDiploma",
    category: "Outline",
  },
  {
    name: "IconDiscoBall",
    file: TxIconOutline.IconDiscoBall,
    description: "IconDiscoBall",
    category: "Outline",
  },
  {
    name: "IconDisk",
    file: TxIconOutline.IconDisk,
    description: "IconDisk",
    category: "Outline",
  },
  {
    name: "IconDoctor",
    file: TxIconOutline.IconDoctor,
    description: "IconDoctor",
    category: "Outline",
  },
  {
    name: "IconDocumentSigned",
    file: TxIconOutline.IconDocumentSigned,
    description: "IconDocumentSigned",
    category: "Outline",
  },
  {
    name: "IconDocument",
    file: TxIconOutline.IconDocument,
    description: "IconDocument",
    category: "Outline",
  },
  {
    name: "IconDollar",
    file: TxIconOutline.IconDollar,
    description: "IconDollar",
    category: "Outline",
  },
  {
    name: "IconDownload",
    file: TxIconOutline.IconDownload,
    description: "IconDownload",
    category: "Outline",
  },
  {
    name: "IconDrinkAlt",
    file: TxIconOutline.IconDrinkAlt,
    description: "IconDrinkAlt",
    category: "Outline",
  },
  {
    name: "IconDrumstick",
    file: TxIconOutline.IconDrumstick,
    description: "IconDrumstick",
    category: "Outline",
  },
  {
    name: "IconDuplicate",
    file: TxIconOutline.IconDuplicate,
    description: "IconDuplicate",
    category: "Outline",
  },
  {
    name: "IconELearning",
    file: TxIconOutline.IconELearning,
    description: "IconELearning",
    category: "Outline",
  },
  {
    name: "IconEarnings",
    file: TxIconOutline.IconEarnings,
    description: "IconEarnings",
    category: "Outline",
  },
  {
    name: "IconEditAlt",
    file: TxIconOutline.IconEditAlt,
    description: "IconEditAlt",
    category: "Outline",
  },
  {
    name: "IconEdit",
    file: TxIconOutline.IconEdit,
    description: "IconEdit",
    category: "Outline",
  },
  {
    name: "IconEnvelopeBan",
    file: TxIconOutline.IconEnvelopeBan,
    description: "IconEnvelopeBan",
    category: "Outline",
  },
  {
    name: "IconEnvelopeDownload",
    file: TxIconOutline.IconEnvelopeDownload,
    description: "IconEnvelopeDownload",
    category: "Outline",
  },
  {
    name: "IconEnvelopeMarker",
    file: TxIconOutline.IconEnvelopeMarker,
    description: "IconEnvelopeMarker",
    category: "Outline",
  },
  {
    name: "IconEnvelopeOpen",
    file: TxIconOutline.IconEnvelopeOpen,
    description: "IconEnvelopeOpen",
    category: "Outline",
  },
  {
    name: "IconEnvelopePlus",
    file: TxIconOutline.IconEnvelopePlus,
    description: "IconEnvelopePlus",
    category: "Outline",
  },
  {
    name: "IconEnvelope",
    file: TxIconOutline.IconEnvelope,
    description: "IconEnvelope",
    category: "Outline",
  },
  {
    name: "IconEuro",
    file: TxIconOutline.IconEuro,
    description: "IconEuro",
    category: "Outline",
  },
  {
    name: "IconExclamation",
    file: TxIconOutline.IconExclamation,
    description: "IconExclamation",
    category: "Outline",
  },
  {
    name: "IconExpand",
    file: TxIconOutline.IconExpand,
    description: "IconExpand",
    category: "Outline",
  },
  {
    name: "IconEyeCrossed",
    file: TxIconOutline.IconEyeCrossed,
    description: "IconEyeCrossed",
    category: "Outline",
  },
  {
    name: "IconEyeDropper",
    file: TxIconOutline.IconEyeDropper,
    description: "IconEyeDropper",
    category: "Outline",
  },
  {
    name: "IconEye",
    file: TxIconOutline.IconEye,
    description: "IconEye",
    category: "Outline",
  },
  {
    name: "IconFeather",
    file: TxIconOutline.IconFeather,
    description: "IconFeather",
    category: "Outline",
  },
  {
    name: "IconFerrisWheel",
    file: TxIconOutline.IconFerrisWheel,
    description: "IconFerrisWheel",
    category: "Outline",
  },
  {
    name: "IconFileAdd",
    file: TxIconOutline.IconFileAdd,
    description: "IconFileAdd",
    category: "Outline",
  },
  {
    name: "IconFileAi",
    file: TxIconOutline.IconFileAi,
    description: "IconFileAi",
    category: "Outline",
  },
  {
    name: "IconFileCheck",
    file: TxIconOutline.IconFileCheck,
    description: "IconFileCheck",
    category: "Outline",
  },
  {
    name: "IconFileDelete",
    file: TxIconOutline.IconFileDelete,
    description: "IconFileDelete",
    category: "Outline",
  },
  {
    name: "IconFileEps",
    file: TxIconOutline.IconFileEps,
    description: "IconFileEps",
    category: "Outline",
  },
  {
    name: "IconFileGif",
    file: TxIconOutline.IconFileGif,
    description: "IconFileGif",
    category: "Outline",
  },
  {
    name: "IconFileMusic",
    file: TxIconOutline.IconFileMusic,
    description: "IconFileMusic",
    category: "Outline",
  },
  {
    name: "IconFilePsd",
    file: TxIconOutline.IconFilePsd,
    description: "IconFilePsd",
    category: "Outline",
  },
  {
    name: "IconFile",
    file: TxIconOutline.IconFile,
    description: "IconFile",
    category: "Outline",
  },
  {
    name: "IconFill",
    file: TxIconOutline.IconFill,
    description: "IconFill",
    category: "Outline",
  },
  {
    name: "IconFilm",
    file: TxIconOutline.IconFilm,
    description: "IconFilm",
    category: "Outline",
  },
  {
    name: "IconFilter",
    file: TxIconOutline.IconFilter,
    description: "IconFilter",
    category: "Outline",
  },
  {
    name: "IconFingerprint",
    file: TxIconOutline.IconFingerprint,
    description: "IconFingerprint",
    category: "Outline",
  },
  {
    name: "IconFish",
    file: TxIconOutline.IconFish,
    description: "IconFish",
    category: "Outline",
  },
  {
    name: "IconFlag",
    file: TxIconOutline.IconFlag,
    description: "IconFlag",
    category: "Outline",
  },
  {
    name: "IconFlame",
    file: TxIconOutline.IconFlame,
    description: "IconFlame",
    category: "Outline",
  },
  {
    name: "IconFlipHorizontal",
    file: TxIconOutline.IconFlipHorizontal,
    description: "IconFlipHorizontal",
    category: "Outline",
  },
  {
    name: "IconFlowerBouquet",
    file: TxIconOutline.IconFlowerBouquet,
    description: "IconFlowerBouquet",
    category: "Outline",
  },
  {
    name: "IconFlowerTulip",
    file: TxIconOutline.IconFlowerTulip,
    description: "IconFlowerTulip",
    category: "Outline",
  },
  {
    name: "IconFlower",
    file: TxIconOutline.IconFlower,
    description: "IconFlower",
    category: "Outline",
  },
  {
    name: "IconFolderAdd",
    file: TxIconOutline.IconFolderAdd,
    description: "IconFolderAdd",
    category: "Outline",
  },
  {
    name: "IconFolder",
    file: TxIconOutline.IconFolder,
    description: "IconFolder",
    category: "Outline",
  },
  {
    name: "IconFollowing",
    file: TxIconOutline.IconFollowing,
    description: "IconFollowing",
    category: "Outline",
  },
  {
    name: "IconFootball",
    file: TxIconOutline.IconFootball,
    description: "IconFootball",
    category: "Outline",
  },
  {
    name: "IconForm",
    file: TxIconOutline.IconForm,
    description: "IconForm",
    category: "Outline",
  },
  {
    name: "IconForward",
    file: TxIconOutline.IconForward,
    description: "IconForward",
    category: "Outline",
  },
  {
    name: "IconFox",
    file: TxIconOutline.IconFox,
    description: "IconFox",
    category: "Outline",
  },
  {
    name: "IconFrown",
    file: TxIconOutline.IconFrown,
    description: "IconFrown",
    category: "Outline",
  },
  {
    name: "IconFtp",
    file: TxIconOutline.IconFtp,
    description: "IconFtp",
    category: "Outline",
  },
  {
    name: "IconGallery",
    file: TxIconOutline.IconGallery,
    description: "IconGallery",
    category: "Outline",
  },
  {
    name: "IconGamepad",
    file: TxIconOutline.IconGamepad,
    description: "IconGamepad",
    category: "Outline",
  },
  {
    name: "IconGasPump",
    file: TxIconOutline.IconGasPump,
    description: "IconGasPump",
    category: "Outline",
  },
  {
    name: "IconGem",
    file: TxIconOutline.IconGem,
    description: "IconGem",
    category: "Outline",
  },
  {
    name: "IconGift",
    file: TxIconOutline.IconGift,
    description: "IconGift",
    category: "Outline",
  },
  {
    name: "IconGlassCheers",
    file: TxIconOutline.IconGlassCheers,
    description: "IconGlassCheers",
    category: "Outline",
  },
  {
    name: "IconGlasses",
    file: TxIconOutline.IconGlasses,
    description: "IconGlasses",
    category: "Outline",
  },
  {
    name: "IconGlobeAlt",
    file: TxIconOutline.IconGlobeAlt,
    description: "IconGlobeAlt",
    category: "Outline",
  },
  {
    name: "IconGlobe",
    file: TxIconOutline.IconGlobe,
    description: "IconGlobe",
    category: "Outline",
  },
  {
    name: "IconGolf",
    file: TxIconOutline.IconGolf,
    description: "IconGolf",
    category: "Outline",
  },
  {
    name: "IconGraduationCap",
    file: TxIconOutline.IconGraduationCap,
    description: "IconGraduationCap",
    category: "Outline",
  },
  {
    name: "IconGraphicTablet",
    file: TxIconOutline.IconGraphicTablet,
    description: "IconGraphicTablet",
    category: "Outline",
  },
  {
    name: "IconGridAlt",
    file: TxIconOutline.IconGridAlt,
    description: "IconGridAlt",
    category: "Outline",
  },
  {
    name: "IconGrid",
    file: TxIconOutline.IconGrid,
    description: "IconGrid",
    category: "Outline",
  },
  {
    name: "IconGuitar",
    file: TxIconOutline.IconGuitar,
    description: "IconGuitar",
    category: "Outline",
  },
  {
    name: "IconGym",
    file: TxIconOutline.IconGym,
    description: "IconGym",
    category: "Outline",
  },
  {
    name: "IconHamburger",
    file: TxIconOutline.IconHamburger,
    description: "IconHamburger",
    category: "Outline",
  },
  {
    name: "IconHandHoldingHeart",
    file: TxIconOutline.IconHandHoldingHeart,
    description: "IconHandHoldingHeart",
    category: "Outline",
  },
  {
    name: "IconHastag",
    file: TxIconOutline.IconHastag,
    description: "IconHastag",
    category: "Outline",
  },
  {
    name: "IconHatBirthday",
    file: TxIconOutline.IconHatBirthday,
    description: "IconHatBirthday",
    category: "Outline",
  },
  {
    name: "IconHeadSideThinking",
    file: TxIconOutline.IconHeadSideThinking,
    description: "IconHeadSideThinking",
    category: "Outline",
  },
  {
    name: "IconHeadphones",
    file: TxIconOutline.IconHeadphones,
    description: "IconHeadphones",
    category: "Outline",
  },
  {
    name: "IconHeadset",
    file: TxIconOutline.IconHeadset,
    description: "IconHeadset",
    category: "Outline",
  },
  {
    name: "IconHeartArrow",
    file: TxIconOutline.IconHeartArrow,
    description: "IconHeartArrow",
    category: "Outline",
  },
  {
    name: "IconHeart",
    file: TxIconOutline.IconHeart,
    description: "IconHeart",
    category: "Outline",
  },
  {
    name: "IconHomeLocationAlt",
    file: TxIconOutline.IconHomeLocationAlt,
    description: "IconHomeLocationAlt",
    category: "Outline",
  },
  {
    name: "IconHomeLocation",
    file: TxIconOutline.IconHomeLocation,
    description: "IconHomeLocation",
    category: "Outline",
  },
  {
    name: "IconHome",
    file: TxIconOutline.IconHome,
    description: "IconHome",
    category: "Outline",
  },
  {
    name: "IconHourglassEnd",
    file: TxIconOutline.IconHourglassEnd,
    description: "IconHourglassEnd",
    category: "Outline",
  },
  {
    name: "IconHourglass",
    file: TxIconOutline.IconHourglass,
    description: "IconHourglass",
    category: "Outline",
  },
  {
    name: "IconIceCream",
    file: TxIconOutline.IconIceCream,
    description: "IconIceCream",
    category: "Outline",
  },
  {
    name: "IconIceSkate",
    file: TxIconOutline.IconIceSkate,
    description: "IconIceSkate",
    category: "Outline",
  },
  {
    name: "IconIdBadge",
    file: TxIconOutline.IconIdBadge,
    description: "IconIdBadge",
    category: "Outline",
  },
  {
    name: "IconInbox",
    file: TxIconOutline.IconInbox,
    description: "IconInbox",
    category: "Outline",
  },
  {
    name: "IconIncognito",
    file: TxIconOutline.IconIncognito,
    description: "IconIncognito",
    category: "Outline",
  },
  {
    name: "IconIndent",
    file: TxIconOutline.IconIndent,
    description: "IconIndent",
    category: "Outline",
  },
  {
    name: "IconInfinity",
    file: TxIconOutline.IconInfinity,
    description: "IconInfinity",
    category: "Outline",
  },
  {
    name: "IconInfo",
    file: TxIconOutline.IconInfo,
    description: "IconInfo",
    category: "Outline",
  },
  {
    name: "IconInteractive",
    file: TxIconOutline.IconInteractive,
    description: "IconInteractive",
    category: "Outline",
  },
  {
    name: "IconInterlining",
    file: TxIconOutline.IconInterlining,
    description: "IconInterlining",
    category: "Outline",
  },
  {
    name: "IconInterrogation",
    file: TxIconOutline.IconInterrogation,
    description: "IconInterrogation",
    category: "Outline",
  },
  {
    name: "IconItalic",
    file: TxIconOutline.IconItalic,
    description: "IconItalic",
    category: "Outline",
  },
  {
    name: "IconJpg",
    file: TxIconOutline.IconJpg,
    description: "IconJpg",
    category: "Outline",
  },
  {
    name: "IconKey",
    file: TxIconOutline.IconKey,
    description: "IconKey",
    category: "Outline",
  },
  {
    name: "IconKeyboard",
    file: TxIconOutline.IconKeyboard,
    description: "IconKeyboard",
    category: "Outline",
  },
  {
    name: "IconKite",
    file: TxIconOutline.IconKite,
    description: "IconKite",
    category: "Outline",
  },
  {
    name: "IconLabel",
    file: TxIconOutline.IconLabel,
    description: "IconLabel",
    category: "Outline",
  },
  {
    name: "IconLaptop",
    file: TxIconOutline.IconLaptop,
    description: "IconLaptop",
    category: "Outline",
  },
  {
    name: "IconLasso",
    file: TxIconOutline.IconLasso,
    description: "IconLasso",
    category: "Outline",
  },
  {
    name: "IconLaugh",
    file: TxIconOutline.IconLaugh,
    description: "IconLaugh",
    category: "Outline",
  },
  {
    name: "IconLayers",
    file: TxIconOutline.IconLayers,
    description: "IconLayers",
    category: "Outline",
  },
  {
    name: "IconLayoutFluid",
    file: TxIconOutline.IconLayoutFluid,
    description: "IconLayoutFluid",
    category: "Outline",
  },
  {
    name: "IconLeaf",
    file: TxIconOutline.IconLeaf,
    description: "IconLeaf",
    category: "Outline",
  },
  {
    name: "IconLetterCase",
    file: TxIconOutline.IconLetterCase,
    description: "IconLetterCase",
    category: "Outline",
  },
  {
    name: "IconLifeRing",
    file: TxIconOutline.IconLifeRing,
    description: "IconLifeRing",
    category: "Outline",
  },
  {
    name: "IconLineWidth",
    file: TxIconOutline.IconLineWidth,
    description: "IconLineWidth",
    category: "Outline",
  },
  {
    name: "IconLink",
    file: TxIconOutline.IconLink,
    description: "IconLink",
    category: "Outline",
  },
  {
    name: "IconLipstick",
    file: TxIconOutline.IconLipstick,
    description: "IconLipstick",
    category: "Outline",
  },
  {
    name: "IconListCheck",
    file: TxIconOutline.IconListCheck,
    description: "IconListCheck",
    category: "Outline",
  },
  {
    name: "IconList",
    file: TxIconOutline.IconList,
    description: "IconList",
    category: "Outline",
  },
  {
    name: "IconLocationAlt",
    file: TxIconOutline.IconLocationAlt,
    description: "IconLocationAlt",
    category: "Outline",
  },
  {
    name: "IconLockAlt",
    file: TxIconOutline.IconLockAlt,
    description: "IconLockAlt",
    category: "Outline",
  },
  {
    name: "IconLock",
    file: TxIconOutline.IconLock,
    description: "IconLock",
    category: "Outline",
  },
  {
    name: "IconLuggageRolling",
    file: TxIconOutline.IconLuggageRolling,
    description: "IconLuggageRolling",
    category: "Outline",
  },
  {
    name: "IconMagicWand",
    file: TxIconOutline.IconMagicWand,
    description: "IconMagicWand",
    category: "Outline",
  },
  {
    name: "IconMakeupBrush",
    file: TxIconOutline.IconMakeupBrush,
    description: "IconMakeupBrush",
    category: "Outline",
  },
  {
    name: "IconManHead",
    file: TxIconOutline.IconManHead,
    description: "IconManHead",
    category: "Outline",
  },
  {
    name: "IconMapMarkerCross",
    file: TxIconOutline.IconMapMarkerCross,
    description: "IconMapMarkerCross",
    category: "Outline",
  },
  {
    name: "IconMapMarkerHome",
    file: TxIconOutline.IconMapMarkerHome,
    description: "IconMapMarkerHome",
    category: "Outline",
  },
  {
    name: "IconMapMarkerMinus",
    file: TxIconOutline.IconMapMarkerMinus,
    description: "IconMapMarkerMinus",
    category: "Outline",
  },
  {
    name: "IconMapMarkerPlus",
    file: TxIconOutline.IconMapMarkerPlus,
    description: "IconMapMarkerPlus",
    category: "Outline",
  },
  {
    name: "IconMapMarker",
    file: TxIconOutline.IconMapMarker,
    description: "IconMapMarker",
    category: "Outline",
  },
  {
    name: "IconMap",
    file: TxIconOutline.IconMap,
    description: "IconMap",
    category: "Outline",
  },
  {
    name: "IconMarkerTime",
    file: TxIconOutline.IconMarkerTime,
    description: "IconMarkerTime",
    category: "Outline",
  },
  {
    name: "IconMarker",
    file: TxIconOutline.IconMarker,
    description: "IconMarker",
    category: "Outline",
  },
  {
    name: "IconMarsDouble",
    file: TxIconOutline.IconMarsDouble,
    description: "IconMarsDouble",
    category: "Outline",
  },
  {
    name: "IconMars",
    file: TxIconOutline.IconMars,
    description: "IconMars",
    category: "Outline",
  },
  {
    name: "IconMaskCarnival",
    file: TxIconOutline.IconMaskCarnival,
    description: "IconMaskCarnival",
    category: "Outline",
  },
  {
    name: "IconMedicine",
    file: TxIconOutline.IconMedicine,
    description: "IconMedicine",
    category: "Outline",
  },
  {
    name: "IconMegaphone",
    file: TxIconOutline.IconMegaphone,
    description: "IconMegaphone",
    category: "Outline",
  },
  {
    name: "IconMeh",
    file: TxIconOutline.IconMeh,
    description: "IconMeh",
    category: "Outline",
  },
  {
    name: "IconMenuBurger",
    file: TxIconOutline.IconMenuBurger,
    description: "IconMenuBurger",
    category: "Outline",
  },
  {
    name: "IconMenuDotsVertical",
    file: TxIconOutline.IconMenuDotsVertical,
    description: "IconMenuDotsVertical",
    category: "Outline",
  },
  {
    name: "IconMenuDots",
    file: TxIconOutline.IconMenuDots,
    description: "IconMenuDots",
    category: "Outline",
  },
  {
    name: "IconMicrophoneAlt",
    file: TxIconOutline.IconMicrophoneAlt,
    description: "IconMicrophoneAlt",
    category: "Outline",
  },
  {
    name: "IconMicrophone",
    file: TxIconOutline.IconMicrophone,
    description: "IconMicrophone",
    category: "Outline",
  },
  {
    name: "IconMinusSmall",
    file: TxIconOutline.IconMinusSmall,
    description: "IconMinusSmall",
    category: "Outline",
  },
  {
    name: "IconMinus",
    file: TxIconOutline.IconMinus,
    description: "IconMinus",
    category: "Outline",
  },
  {
    name: "IconMobile",
    file: TxIconOutline.IconMobile,
    description: "IconMobile",
    category: "Outline",
  },
  {
    name: "IconModeLandscape",
    file: TxIconOutline.IconModeLandscape,
    description: "IconModeLandscape",
    category: "Outline",
  },
  {
    name: "IconModePortrait",
    file: TxIconOutline.IconModePortrait,
    description: "IconModePortrait",
    category: "Outline",
  },
  {
    name: "IconMoney",
    file: TxIconOutline.IconMoney,
    description: "IconMoney",
    category: "Outline",
  },
  {
    name: "IconMoon",
    file: TxIconOutline.IconMoon,
    description: "IconMoon",
    category: "Outline",
  },
  {
    name: "IconMountains",
    file: TxIconOutline.IconMountains,
    description: "IconMountains",
    category: "Outline",
  },
  {
    name: "IconMouse",
    file: TxIconOutline.IconMouse,
    description: "IconMouse",
    category: "Outline",
  },
  {
    name: "IconMugAlt",
    file: TxIconOutline.IconMugAlt,
    description: "IconMugAlt",
    category: "Outline",
  },
  {
    name: "IconMusicAlt",
    file: TxIconOutline.IconMusicAlt,
    description: "IconMusicAlt",
    category: "Outline",
  },
  {
    name: "IconMusic",
    file: TxIconOutline.IconMusic,
    description: "IconMusic",
    category: "Outline",
  },
  {
    name: "IconNavigation",
    file: TxIconOutline.IconNavigation,
    description: "IconNavigation",
    category: "Outline",
  },
  {
    name: "IconNetworkCloud",
    file: TxIconOutline.IconNetworkCloud,
    description: "IconNetworkCloud",
    category: "Outline",
  },
  {
    name: "IconNetwork",
    file: TxIconOutline.IconNetwork,
    description: "IconNetwork",
    category: "Outline",
  },
  {
    name: "IconNotebook",
    file: TxIconOutline.IconNotebook,
    description: "IconNotebook",
    category: "Outline",
  },
  {
    name: "IconOpacity",
    file: TxIconOutline.IconOpacity,
    description: "IconOpacity",
    category: "Outline",
  },
  {
    name: "IconPackage",
    file: TxIconOutline.IconPackage,
    description: "IconPackage",
    category: "Outline",
  },
  {
    name: "IconPaintBrush",
    file: TxIconOutline.IconPaintBrush,
    description: "IconPaintBrush",
    category: "Outline",
  },
  {
    name: "IconPalette",
    file: TxIconOutline.IconPalette,
    description: "IconPalette",
    category: "Outline",
  },
  {
    name: "IconPaperPlane",
    file: TxIconOutline.IconPaperPlane,
    description: "IconPaperPlane",
    category: "Outline",
  },
  {
    name: "IconPassword",
    file: TxIconOutline.IconPassword,
    description: "IconPassword",
    category: "Outline",
  },
  {
    name: "IconPause",
    file: TxIconOutline.IconPause,
    description: "IconPause",
    category: "Outline",
  },
  {
    name: "IconPaw",
    file: TxIconOutline.IconPaw,
    description: "IconPaw",
    category: "Outline",
  },
  {
    name: "IconPencil",
    file: TxIconOutline.IconPencil,
    description: "IconPencil",
    category: "Outline",
  },
  {
    name: "IconPharmacy",
    file: TxIconOutline.IconPharmacy,
    description: "IconPharmacy",
    category: "Outline",
  },
  {
    name: "IconPhoneCall",
    file: TxIconOutline.IconPhoneCall,
    description: "IconPhoneCall",
    category: "Outline",
  },
  {
    name: "IconPhoneCross",
    file: TxIconOutline.IconPhoneCross,
    description: "IconPhoneCross",
    category: "Outline",
  },
  {
    name: "IconPhonePause",
    file: TxIconOutline.IconPhonePause,
    description: "IconPhonePause",
    category: "Outline",
  },
  {
    name: "IconPhoneSlash",
    file: TxIconOutline.IconPhoneSlash,
    description: "IconPhoneSlash",
    category: "Outline",
  },
  {
    name: "IconPhysics",
    file: TxIconOutline.IconPhysics,
    description: "IconPhysics",
    category: "Outline",
  },
  {
    name: "IconPicture",
    file: TxIconOutline.IconPicture,
    description: "IconPicture",
    category: "Outline",
  },
  {
    name: "IconPingPong",
    file: TxIconOutline.IconPingPong,
    description: "IconPingPong",
    category: "Outline",
  },
  {
    name: "IconPizzaSlice",
    file: TxIconOutline.IconPizzaSlice,
    description: "IconPizzaSlice",
    category: "Outline",
  },
  {
    name: "IconPlane",
    file: TxIconOutline.IconPlane,
    description: "IconPlane",
    category: "Outline",
  },
  {
    name: "IconPlayAlt",
    file: TxIconOutline.IconPlayAlt,
    description: "IconPlayAlt",
    category: "Outline",
  },
  {
    name: "IconPlay",
    file: TxIconOutline.IconPlay,
    description: "IconPlay",
    category: "Outline",
  },
  {
    name: "IconPlayingCards",
    file: TxIconOutline.IconPlayingCards,
    description: "IconPlayingCards",
    category: "Outline",
  },
  {
    name: "IconPlusSmall",
    file: TxIconOutline.IconPlusSmall,
    description: "IconPlusSmall",
    category: "Outline",
  },
  {
    name: "IconPlus",
    file: TxIconOutline.IconPlus,
    description: "IconPlus",
    category: "Outline",
  },
  {
    name: "IconPokerChip",
    file: TxIconOutline.IconPokerChip,
    description: "IconPokerChip",
    category: "Outline",
  },
  {
    name: "IconPortrait",
    file: TxIconOutline.IconPortrait,
    description: "IconPortrait",
    category: "Outline",
  },
  {
    name: "IconPound",
    file: TxIconOutline.IconPound,
    description: "IconPound",
    category: "Outline",
  },
  {
    name: "IconPower",
    file: TxIconOutline.IconPower,
    description: "IconPower",
    category: "Outline",
  },
  {
    name: "IconPresentation",
    file: TxIconOutline.IconPresentation,
    description: "IconPresentation",
    category: "Outline",
  },
  {
    name: "IconPrint",
    file: TxIconOutline.IconPrint,
    description: "IconPrint",
    category: "Outline",
  },
  {
    name: "IconProtractor",
    file: TxIconOutline.IconProtractor,
    description: "IconProtractor",
    category: "Outline",
  },
  {
    name: "IconPulse",
    file: TxIconOutline.IconPulse,
    description: "IconPulse",
    category: "Outline",
  },
  {
    name: "IconPyramid",
    file: TxIconOutline.IconPyramid,
    description: "IconPyramid",
    category: "Outline",
  },
  {
    name: "IconQuoteRight",
    file: TxIconOutline.IconQuoteRight,
    description: "IconQuoteRight",
    category: "Outline",
  },
  {
    name: "IconRainbow",
    file: TxIconOutline.IconRainbow,
    description: "IconRainbow",
    category: "Outline",
  },
  {
    name: "IconRaindrops",
    file: TxIconOutline.IconRaindrops,
    description: "IconRaindrops",
    category: "Outline",
  },
  {
    name: "IconRec",
    file: TxIconOutline.IconRec,
    description: "IconRec",
    category: "Outline",
  },
  {
    name: "IconReceipt",
    file: TxIconOutline.IconReceipt,
    description: "IconReceipt",
    category: "Outline",
  },
  {
    name: "IconRecordVinyl",
    file: TxIconOutline.IconRecordVinyl,
    description: "IconRecordVinyl",
    category: "Outline",
  },
  {
    name: "IconRectabgleVertical",
    file: TxIconOutline.IconRectabgleVertical,
    description: "IconRectabgleVertical",
    category: "Outline",
  },
  {
    name: "IconRectangleHorizontal",
    file: TxIconOutline.IconRectangleHorizontal,
    description: "IconRectangleHorizontal",
    category: "Outline",
  },
  {
    name: "IconRectanglePanoramic",
    file: TxIconOutline.IconRectanglePanoramic,
    description: "IconRectanglePanoramic",
    category: "Outline",
  },
  {
    name: "IconRecycle",
    file: TxIconOutline.IconRecycle,
    description: "IconRecycle",
    category: "Outline",
  },
  {
    name: "IconRedoAlt",
    file: TxIconOutline.IconRedoAlt,
    description: "IconRedoAlt",
    category: "Outline",
  },
  {
    name: "IconRedo",
    file: TxIconOutline.IconRedo,
    description: "IconRedo",
    category: "Outline",
  },
  {
    name: "IconReflect",
    file: TxIconOutline.IconReflect,
    description: "IconReflect",
    category: "Outline",
  },
  {
    name: "IconRefresh",
    file: TxIconOutline.IconRefresh,
    description: "IconRefresh",
    category: "Outline",
  },
  {
    name: "IconResize",
    file: TxIconOutline.IconResize,
    description: "IconResize",
    category: "Outline",
  },
  {
    name: "IconResources",
    file: TxIconOutline.IconResources,
    description: "IconResources",
    category: "Outline",
  },
  {
    name: "IconRewind",
    file: TxIconOutline.IconRewind,
    description: "IconRewind",
    category: "Outline",
  },
  {
    name: "IconRhombus",
    file: TxIconOutline.IconRhombus,
    description: "IconRhombus",
    category: "Outline",
  },
  {
    name: "IconRingsWedding",
    file: TxIconOutline.IconRingsWedding,
    description: "IconRingsWedding",
    category: "Outline",
  },
  {
    name: "IconRoad",
    file: TxIconOutline.IconRoad,
    description: "IconRoad",
    category: "Outline",
  },
  {
    name: "IconRocket",
    file: TxIconOutline.IconRocket,
    description: "IconRocket",
    category: "Outline",
  },
  {
    name: "IconRoomService",
    file: TxIconOutline.IconRoomService,
    description: "IconRoomService",
    category: "Outline",
  },
  {
    name: "IconRotateRight",
    file: TxIconOutline.IconRotateRight,
    description: "IconRotateRight",
    category: "Outline",
  },
  {
    name: "IconRugby",
    file: TxIconOutline.IconRugby,
    description: "IconRugby",
    category: "Outline",
  },
  {
    name: "IconSad",
    file: TxIconOutline.IconSad,
    description: "IconSad",
    category: "Outline",
  },
  {
    name: "IconSalad",
    file: TxIconOutline.IconSalad,
    description: "IconSalad",
    category: "Outline",
  },
  {
    name: "IconScale",
    file: TxIconOutline.IconScale,
    description: "IconScale",
    category: "Outline",
  },
  {
    name: "IconSchoolBus",
    file: TxIconOutline.IconSchoolBus,
    description: "IconSchoolBus",
    category: "Outline",
  },
  {
    name: "IconSchool",
    file: TxIconOutline.IconSchool,
    description: "IconSchool",
    category: "Outline",
  },
  {
    name: "IconScissors",
    file: TxIconOutline.IconScissors,
    description: "IconScissors",
    category: "Outline",
  },
  {
    name: "IconScreen",
    file: TxIconOutline.IconScreen,
    description: "IconScreen",
    category: "Outline",
  },
  {
    name: "IconSearchAlt",
    file: TxIconOutline.IconSearchAlt,
    description: "IconSearchAlt",
    category: "Outline",
  },
  {
    name: "IconSearchHeart",
    file: TxIconOutline.IconSearchHeart,
    description: "IconSearchHeart",
    category: "Outline",
  },
  {
    name: "IconSearch",
    file: TxIconOutline.IconSearch,
    description: "IconSearch",
    category: "Outline",
  },
  {
    name: "IconSettingsSliders",
    file: TxIconOutline.IconSettingsSliders,
    description: "IconSettingsSliders",
    category: "Outline",
  },
  {
    name: "IconSettings",
    file: TxIconOutline.IconSettings,
    description: "IconSettings",
    category: "Outline",
  },
  {
    name: "IconShare",
    file: TxIconOutline.IconShare,
    description: "IconShare",
    category: "Outline",
  },
  {
    name: "IconShieldCheck",
    file: TxIconOutline.IconShieldCheck,
    description: "IconShieldCheck",
    category: "Outline",
  },
  {
    name: "IconShieldExclamation",
    file: TxIconOutline.IconShieldExclamation,
    description: "IconShieldExclamation",
    category: "Outline",
  },
  {
    name: "IconShieldInterrogation",
    file: TxIconOutline.IconShieldInterrogation,
    description: "IconShieldInterrogation",
    category: "Outline",
  },
  {
    name: "IconShieldPlus",
    file: TxIconOutline.IconShieldPlus,
    description: "IconShieldPlus",
    category: "Outline",
  },
  {
    name: "IconShield",
    file: TxIconOutline.IconShield,
    description: "IconShield",
    category: "Outline",
  },
  {
    name: "IconShipSide",
    file: TxIconOutline.IconShipSide,
    description: "IconShipSide",
    category: "Outline",
  },
  {
    name: "IconShip",
    file: TxIconOutline.IconShip,
    description: "IconShip",
    category: "Outline",
  },
  {
    name: "IconShop",
    file: TxIconOutline.IconShop,
    description: "IconShop",
    category: "Outline",
  },
  {
    name: "IconShoppingBagAdd",
    file: TxIconOutline.IconShoppingBagAdd,
    description: "IconShoppingBagAdd",
    category: "Outline",
  },
  {
    name: "IconShoppingBag",
    file: TxIconOutline.IconShoppingBag,
    description: "IconShoppingBag",
    category: "Outline",
  },
  {
    name: "IconShoppingCartAdd",
    file: TxIconOutline.IconShoppingCartAdd,
    description: "IconShoppingCartAdd",
    category: "Outline",
  },
  {
    name: "IconShoppingCartCheck",
    file: TxIconOutline.IconShoppingCartCheck,
    description: "IconShoppingCartCheck",
    category: "Outline",
  },
  {
    name: "IconShoppingCart",
    file: TxIconOutline.IconShoppingCart,
    description: "IconShoppingCart",
    category: "Outline",
  },
  {
    name: "IconShuffle",
    file: TxIconOutline.IconShuffle,
    description: "IconShuffle",
    category: "Outline",
  },
  {
    name: "IconSignInAlt",
    file: TxIconOutline.IconSignInAlt,
    description: "IconSignInAlt",
    category: "Outline",
  },
  {
    name: "IconSignIn",
    file: TxIconOutline.IconSignIn,
    description: "IconSignIn",
    category: "Outline",
  },
  {
    name: "IconSignOutAlt",
    file: TxIconOutline.IconSignOutAlt,
    description: "IconSignOutAlt",
    category: "Outline",
  },
  {
    name: "IconSignOut",
    file: TxIconOutline.IconSignOut,
    description: "IconSignOut",
    category: "Outline",
  },
  {
    name: "IconSignalAlt1",
    file: TxIconOutline.IconSignalAlt1,
    description: "IconSignalAlt1",
    category: "Outline",
  },
  {
    name: "IconSignalAlt2",
    file: TxIconOutline.IconSignalAlt2,
    description: "IconSignalAlt2",
    category: "Outline",
  },
  {
    name: "IconSignalAlt",
    file: TxIconOutline.IconSignalAlt,
    description: "IconSignalAlt",
    category: "Outline",
  },
  {
    name: "IconSkateboard",
    file: TxIconOutline.IconSkateboard,
    description: "IconSkateboard",
    category: "Outline",
  },
  {
    name: "IconSmartphone",
    file: TxIconOutline.IconSmartphone,
    description: "IconSmartphone",
    category: "Outline",
  },
  {
    name: "IconSmileWink",
    file: TxIconOutline.IconSmileWink,
    description: "IconSmileWink",
    category: "Outline",
  },
  {
    name: "IconSmile",
    file: TxIconOutline.IconSmile,
    description: "IconSmile",
    category: "Outline",
  },
  {
    name: "IconSnowflake",
    file: TxIconOutline.IconSnowflake,
    description: "IconSnowflake",
    category: "Outline",
  },
  {
    name: "IconSoap",
    file: TxIconOutline.IconSoap,
    description: "IconSoap",
    category: "Outline",
  },
  {
    name: "IconSoup",
    file: TxIconOutline.IconSoup,
    description: "IconSoup",
    category: "Outline",
  },
  {
    name: "IconSpa",
    file: TxIconOutline.IconSpa,
    description: "IconSpa",
    category: "Outline",
  },
  {
    name: "IconSpeaker",
    file: TxIconOutline.IconSpeaker,
    description: "IconSpeaker",
    category: "Outline",
  },
  {
    name: "IconSphere",
    file: TxIconOutline.IconSphere,
    description: "IconSphere",
    category: "Outline",
  },
  {
    name: "IconSpinnerAlt",
    file: TxIconOutline.IconSpinnerAlt,
    description: "IconSpinnerAlt",
    category: "Outline",
  },
  {
    name: "IconSpinner",
    file: TxIconOutline.IconSpinner,
    description: "IconSpinner",
    category: "Outline",
  },
  {
    name: "IconSquareRoot",
    file: TxIconOutline.IconSquareRoot,
    description: "IconSquareRoot",
    category: "Outline",
  },
  {
    name: "IconSquare",
    file: TxIconOutline.IconSquare,
    description: "IconSquare",
    category: "Outline",
  },
  {
    name: "IconStarOctogram",
    file: TxIconOutline.IconStarOctogram,
    description: "IconStarOctogram",
    category: "Outline",
  },
  {
    name: "IconStar",
    file: TxIconOutline.IconStar,
    description: "IconStar",
    category: "Outline",
  },
  {
    name: "IconStats",
    file: TxIconOutline.IconStats,
    description: "IconStats",
    category: "Outline",
  },
  {
    name: "IconStethoscope",
    file: TxIconOutline.IconStethoscope,
    description: "IconStethoscope",
    category: "Outline",
  },
  {
    name: "IconSticker",
    file: TxIconOutline.IconSticker,
    description: "IconSticker",
    category: "Outline",
  },
  {
    name: "IconStop",
    file: TxIconOutline.IconStop,
    description: "IconStop",
    category: "Outline",
  },
  {
    name: "IconStopwatch",
    file: TxIconOutline.IconStopwatch,
    description: "IconStopwatch",
    category: "Outline",
  },
  {
    name: "IconSubtitles",
    file: TxIconOutline.IconSubtitles,
    description: "IconSubtitles",
    category: "Outline",
  },
  {
    name: "IconSun",
    file: TxIconOutline.IconSun,
    description: "IconSun",
    category: "Outline",
  },
  {
    name: "IconSunrise",
    file: TxIconOutline.IconSunrise,
    description: "IconSunrise",
    category: "Outline",
  },
  {
    name: "IconSurfing",
    file: TxIconOutline.IconSurfing,
    description: "IconSurfing",
    category: "Outline",
  },
  {
    name: "IconSword",
    file: TxIconOutline.IconSword,
    description: "IconSword",
    category: "Outline",
  },
  {
    name: "IconSyringe",
    file: TxIconOutline.IconSyringe,
    description: "IconSyringe",
    category: "Outline",
  },
  {
    name: "IconTablet",
    file: TxIconOutline.IconTablet,
    description: "IconTablet",
    category: "Outline",
  },
  {
    name: "IconTarget",
    file: TxIconOutline.IconTarget,
    description: "IconTarget",
    category: "Outline",
  },
  {
    name: "IconTaxi",
    file: TxIconOutline.IconTaxi,
    description: "IconTaxi",
    category: "Outline",
  },
  {
    name: "IconTennis",
    file: TxIconOutline.IconTennis,
    description: "IconTennis",
    category: "Outline",
  },
  {
    name: "IconTerrace",
    file: TxIconOutline.IconTerrace,
    description: "IconTerrace",
    category: "Outline",
  },
  {
    name: "IconTestTube",
    file: TxIconOutline.IconTestTube,
    description: "IconTestTube",
    category: "Outline",
  },
  {
    name: "IconTest",
    file: TxIconOutline.IconTest,
    description: "IconTest",
    category: "Outline",
  },
  {
    name: "IconTextCheck",
    file: TxIconOutline.IconTextCheck,
    description: "IconTextCheck",
    category: "Outline",
  },
  {
    name: "IconText",
    file: TxIconOutline.IconText,
    description: "IconText",
    category: "Outline",
  },
  {
    name: "IconThermometerHalf",
    file: TxIconOutline.IconThermometerHalf,
    description: "IconThermometerHalf",
    category: "Outline",
  },
  {
    name: "IconThumbsDown",
    file: TxIconOutline.IconThumbsDown,
    description: "IconThumbsDown",
    category: "Outline",
  },
  {
    name: "IconThumbsUp",
    file: TxIconOutline.IconThumbsUp,
    description: "IconThumbsUp",
    category: "Outline",
  },
  {
    name: "IconThumbtack",
    file: TxIconOutline.IconThumbtack,
    description: "IconThumbtack",
    category: "Outline",
  },
  {
    name: "IconTicket",
    file: TxIconOutline.IconTicket,
    description: "IconTicket",
    category: "Outline",
  },
  {
    name: "IconTimeAdd",
    file: TxIconOutline.IconTimeAdd,
    description: "IconTimeAdd",
    category: "Outline",
  },
  {
    name: "IconTimeCheck",
    file: TxIconOutline.IconTimeCheck,
    description: "IconTimeCheck",
    category: "Outline",
  },
  {
    name: "IconTimeDelete",
    file: TxIconOutline.IconTimeDelete,
    description: "IconTimeDelete",
    category: "Outline",
  },
  {
    name: "IconTimeFast",
    file: TxIconOutline.IconTimeFast,
    description: "IconTimeFast",
    category: "Outline",
  },
  {
    name: "IconTimeForwardSixty",
    file: TxIconOutline.IconTimeForwardSixty,
    description: "IconTimeForwardSixty",
    category: "Outline",
  },
  {
    name: "IconTimeForwardTen",
    file: TxIconOutline.IconTimeForwardTen,
    description: "IconTimeForwardTen",
    category: "Outline",
  },
  {
    name: "IconTimeForward",
    file: TxIconOutline.IconTimeForward,
    description: "IconTimeForward",
    category: "Outline",
  },
  {
    name: "IconTimeHalfPast",
    file: TxIconOutline.IconTimeHalfPast,
    description: "IconTimeHalfPast",
    category: "Outline",
  },
  {
    name: "IconTimeOclock",
    file: TxIconOutline.IconTimeOclock,
    description: "IconTimeOclock",
    category: "Outline",
  },
  {
    name: "IconTimePast",
    file: TxIconOutline.IconTimePast,
    description: "IconTimePast",
    category: "Outline",
  },
  {
    name: "IconTimeQuarterPast",
    file: TxIconOutline.IconTimeQuarterPast,
    description: "IconTimeQuarterPast",
    category: "Outline",
  },
  {
    name: "IconTimeQuarterTo",
    file: TxIconOutline.IconTimeQuarterTo,
    description: "IconTimeQuarterTo",
    category: "Outline",
  },
  {
    name: "IconTimeTwentyFour",
    file: TxIconOutline.IconTimeTwentyFour,
    description: "IconTimeTwentyFour",
    category: "Outline",
  },
  {
    name: "IconToolCrop",
    file: TxIconOutline.IconToolCrop,
    description: "IconToolCrop",
    category: "Outline",
  },
  {
    name: "IconToolMarquee",
    file: TxIconOutline.IconToolMarquee,
    description: "IconToolMarquee",
    category: "Outline",
  },
  {
    name: "IconTooth",
    file: TxIconOutline.IconTooth,
    description: "IconTooth",
    category: "Outline",
  },
  {
    name: "IconTornado",
    file: TxIconOutline.IconTornado,
    description: "IconTornado",
    category: "Outline",
  },
  {
    name: "IconTrainSide",
    file: TxIconOutline.IconTrainSide,
    description: "IconTrainSide",
    category: "Outline",
  },
  {
    name: "IconTrain",
    file: TxIconOutline.IconTrain,
    description: "IconTrain",
    category: "Outline",
  },
  {
    name: "IconTransform",
    file: TxIconOutline.IconTransform,
    description: "IconTransform",
    category: "Outline",
  },
  {
    name: "IconTrash",
    file: TxIconOutline.IconTrash,
    description: "IconTrash",
    category: "Outline",
  },
  {
    name: "IconTreatment",
    file: TxIconOutline.IconTreatment,
    description: "IconTreatment",
    category: "Outline",
  },
  {
    name: "IconTreeChristmas",
    file: TxIconOutline.IconTreeChristmas,
    description: "IconTreeChristmas",
    category: "Outline",
  },
  {
    name: "IconTree",
    file: TxIconOutline.IconTree,
    description: "IconTree",
    category: "Outline",
  },
  {
    name: "IconTriangle",
    file: TxIconOutline.IconTriangle,
    description: "IconTriangle",
    category: "Outline",
  },
  {
    name: "IconTrophy",
    file: TxIconOutline.IconTrophy,
    description: "IconTrophy",
    category: "Outline",
  },
  {
    name: "IconTruckSide",
    file: TxIconOutline.IconTruckSide,
    description: "IconTruckSide",
    category: "Outline",
  },
  {
    name: "IconUmbrella",
    file: TxIconOutline.IconUmbrella,
    description: "IconUmbrella",
    category: "Outline",
  },
  {
    name: "IconUnderline",
    file: TxIconOutline.IconUnderline,
    description: "IconUnderline",
    category: "Outline",
  },
  {
    name: "IconUndoAlt",
    file: TxIconOutline.IconUndoAlt,
    description: "IconUndoAlt",
    category: "Outline",
  },
  {
    name: "IconUndo",
    file: TxIconOutline.IconUndo,
    description: "IconUndo",
    category: "Outline",
  },
  {
    name: "IconUnlock",
    file: TxIconOutline.IconUnlock,
    description: "IconUnlock",
    category: "Outline",
  },
  {
    name: "IconUpload",
    file: TxIconOutline.IconUpload,
    description: "IconUpload",
    category: "Outline",
  },
  {
    name: "IconUsbPendrive",
    file: TxIconOutline.IconUsbPendrive,
    description: "IconUsbPendrive",
    category: "Outline",
  },
  {
    name: "IconUserAdd",
    file: TxIconOutline.IconUserAdd,
    description: "IconUserAdd",
    category: "Outline",
  },
  {
    name: "IconUserDelete",
    file: TxIconOutline.IconUserDelete,
    description: "IconUserDelete",
    category: "Outline",
  },
  {
    name: "IconUserRemove",
    file: TxIconOutline.IconUserRemove,
    description: "IconUserRemove",
    category: "Outline",
  },
  {
    name: "IconUserTime",
    file: TxIconOutline.IconUserTime,
    description: "IconUserTime",
    category: "Outline",
  },
  {
    name: "IconUser",
    file: TxIconOutline.IconUser,
    description: "IconUser",
    category: "Outline",
  },
  {
    name: "IconUtensils",
    file: TxIconOutline.IconUtensils,
    description: "IconUtensils",
    category: "Outline",
  },
  {
    name: "IconVectorAlt",
    file: TxIconOutline.IconVectorAlt,
    description: "IconVectorAlt",
    category: "Outline",
  },
  {
    name: "IconVector",
    file: TxIconOutline.IconVector,
    description: "IconVector",
    category: "Outline",
  },
  {
    name: "IconVenusDouble",
    file: TxIconOutline.IconVenusDouble,
    description: "IconVenusDouble",
    category: "Outline",
  },
  {
    name: "IconVenusMars",
    file: TxIconOutline.IconVenusMars,
    description: "IconVenusMars",
    category: "Outline",
  },
  {
    name: "IconVenus",
    file: TxIconOutline.IconVenus,
    description: "IconVenus",
    category: "Outline",
  },
  {
    name: "IconVideoCamera",
    file: TxIconOutline.IconVideoCamera,
    description: "IconVideoCamera",
    category: "Outline",
  },
  {
    name: "IconVolleyball",
    file: TxIconOutline.IconVolleyball,
    description: "IconVolleyball",
    category: "Outline",
  },
  {
    name: "IconVolume",
    file: TxIconOutline.IconVolume,
    description: "IconVolume",
    category: "Outline",
  },
  {
    name: "IconWheelchair",
    file: TxIconOutline.IconWheelchair,
    description: "IconWheelchair",
    category: "Outline",
  },
  {
    name: "IconWifiAlt",
    file: TxIconOutline.IconWifiAlt,
    description: "IconWifiAlt",
    category: "Outline",
  },
  {
    name: "IconWind",
    file: TxIconOutline.IconWind,
    description: "IconWind",
    category: "Outline",
  },
  {
    name: "IconWomanHead",
    file: TxIconOutline.IconWomanHead,
    description: "IconWomanHead",
    category: "Outline",
  },
  {
    name: "IconWorld",
    file: TxIconOutline.IconWorld,
    description: "IconWorld",
    category: "Outline",
  },
  {
    name: "IconYen",
    file: TxIconOutline.IconYen,
    description: "IconYen",
    category: "Outline",
  },
  {
    name: "IconZoomIn",
    file: TxIconOutline.IconZoomIn,
    description: "IconZoomIn",
    category: "Outline",
  },
  {
    name: "IconZoomOut",
    file: TxIconOutline.IconZoomOut,
    description: "IconZoomOut",
    category: "Outline",
  },
];

function IconListTemplate({ variant = "outline" }) {
  const [searchQuery, setSearchQuery] = useState("");

  const filteredIcons = iconData.filter(
    icon =>
      icon.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      icon.description.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div style={{ margin: "0 auto", fontFamily: "sans-serif" }}>
      {/* Search Input */}
      <div style={{ marginBottom: "24px" }}>
        <input
          type="text"
          placeholder={`Search ${iconData.length} icons by name...`}
          value={searchQuery}
          onChange={e => setSearchQuery(e.target.value)}
          style={{
            width: "100%",
            padding: "14px 18px",
            border: "1px solid #e0e0e0",
            borderRadius: "8px",
            fontSize: "15px",
            outline: "none",
            transition: "border-color 0.2s",
          }}
          onFocus={e => {
            e.target.style.borderColor = "#00bcff";
          }}
          onBlur={e => {
            e.target.style.borderColor = "#e0e0e0";
          }}
        />
      </div>

      {/* Results count */}
      <div style={{ marginBottom: "16px", fontSize: "14px", color: "#666" }}>
        Showing {filteredIcons.length} of {iconData.length} icons
      </div>

      {/* Icons Grid */}
      {filteredIcons.length > 0 ? (
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fill, minmax(110px, 1fr))",
            gap: "8px",
          }}
        >
          {filteredIcons.map(icon => (
            <div
              key={icon.name}
              style={{
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                gap: "8px",
                padding: "12px",
                background: "#ffffff",
                border: "1px solid #e0e0e0",
                borderRadius: "12px",
                transition: "all 0.2s",
                cursor: "pointer",
              }}
              onMouseEnter={e => {
                e.currentTarget.style.transform = "translateY(-4px)";
                e.currentTarget.style.boxShadow = "0 8px 16px rgba(0, 0, 0, 0.1)";
                e.currentTarget.style.borderColor = "#00bcff";
              }}
              onMouseLeave={e => {
                e.currentTarget.style.transform = "translateY(0)";
                e.currentTarget.style.boxShadow = "none";
                e.currentTarget.style.borderColor = "#e0e0e0";
              }}
            >
              {/* Icon Display */}
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  width: "40px",
                  height: "40px",
                  background: "#f5f5f5",
                  borderRadius: "12px",
                  marginBottom: "4px",
                }}
              >
                <img src={icon.file} alt={icon.name} style={{ width: "16px", height: "16px", objectFit: "contain" }} />
              </div>

              {/* Icon Info */}
              <div style={{ textAlign: "center", width: "100%" }}>
                <span
                  style={{
                    display: "block",
                    marginBottom: "4px",
                    fontSize: "12px",
                    color: "#1a1a1a",
                    lineHeight: "1.2",
                    fontWeight: "500",
                  }}
                >
                  {icon.name}
                </span>
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div style={{ textAlign: "center", padding: "60px", color: "#888" }}>
          <p style={{ fontSize: "16px" }}>No icons found matching "{searchQuery}"</p>
          <p style={{ fontSize: "14px", marginTop: "8px" }}>Try a different search term</p>
        </div>
      )}
    </div>
  );
}

// Story for Outline icons
export const Outline = {
  render: () => <IconListTemplate variant="outline" />,
};

// Story for Filled icons (placeholder)
export const Filled = {
  render: () => (
    <div style={{ padding: "60px", textAlign: "center", color: "#888", fontFamily: "sans-serif" }}>
      <p style={{ fontSize: "16px" }}>Filled icons coming soon...</p>
    </div>
  ),
};
