import { useState } from "react";
import { TxIconOutline } from "../assets/icons/outline";

const TxIconOutlineStory = {
  title: "tx-design-ui/Foundation/TxIcon/TxIconOutline",
  component: "TxIcon",
  parameters: {
    layout: "fullscreen",
  },
};
export default TxIconOutlineStory;

const iconData = [
  {
    name: "Add",
    file: TxIconOutline.IconAdd,
    description: "Add",
    category: "Outline",
  },
  {
    name: "AddressBook",
    file: TxIconOutline.IconAddressBook,
    description: "AddressBook",
    category: "Outline",
  },
  {
    name: "AlarmClock",
    file: TxIconOutline.IconAlarmClock,
    description: "AlarmClock",
    category: "Outline",
  },
  {
    name: "AlignCenter",
    file: TxIconOutline.IconAlignCenter,
    description: "AlignCenter",
    category: "Outline",
  },
  {
    name: "AlignJustify",
    file: TxIconOutline.IconAlignJustify,
    description: "AlignJustify",
    category: "Outline",
  },
  {
    name: "AlignLeft",
    file: TxIconOutline.IconAlignLeft,
    description: "AlignLeft",
    category: "Outline",
  },
  {
    name: "AlignRight",
    file: TxIconOutline.IconAlignRight,
    description: "AlignRight",
    category: "Outline",
  },
  {
    name: "Ambulance",
    file: TxIconOutline.IconAmbulance,
    description: "Ambulance",
    category: "Outline",
  },
  {
    name: "AngleDoubleLeft",
    file: TxIconOutline.IconAngleDoubleLeft,
    description: "AngleDoubleLeft",
    category: "Outline",
  },
  {
    name: "AngleDoubleRight",
    file: TxIconOutline.IconAngleDoubleRight,
    description: "AngleDoubleRight",
    category: "Outline",
  },
  {
    name: "AngleDoubleSmallLeft",
    file: TxIconOutline.IconAngleDoubleSmallLeft,
    description: "AngleDoubleSmallLeft",
    category: "Outline",
  },
  {
    name: "AngleDoubleSmallRight",
    file: TxIconOutline.IconAngleDoubleSmallRight,
    description: "AngleDoubleSmallRight",
    category: "Outline",
  },
  {
    name: "AngleDown",
    file: TxIconOutline.IconAngleDown,
    description: "AngleDown",
    category: "Outline",
  },
  {
    name: "AngleLeft",
    file: TxIconOutline.IconAngleLeft,
    description: "AngleLeft",
    category: "Outline",
  },
  {
    name: "AngleRight",
    file: TxIconOutline.IconAngleRight,
    description: "AngleRight",
    category: "Outline",
  },
  {
    name: "AngleSmallDown",
    file: TxIconOutline.IconAngleSmallDown,
    description: "AngleSmallDown",
    category: "Outline",
  },
  {
    name: "AngleSmallLeft",
    file: TxIconOutline.IconAngleSmallLeft,
    description: "AngleSmallLeft",
    category: "Outline",
  },
  {
    name: "AngleSmallRight",
    file: TxIconOutline.IconAngleSmallRight,
    description: "AngleSmallRight",
    category: "Outline",
  },
  {
    name: "AngleSmallUp",
    file: TxIconOutline.IconAngleSmallUp,
    description: "AngleSmallUp",
    category: "Outline",
  },
  {
    name: "AngleUp",
    file: TxIconOutline.IconAngleUp,
    description: "AngleUp",
    category: "Outline",
  },
  {
    name: "Apple",
    file: TxIconOutline.IconApple,
    description: "Apple",
    category: "Outline",
  },
  {
    name: "AppsAdd",
    file: TxIconOutline.IconAppsAdd,
    description: "AppsAdd",
    category: "Outline",
  },
  {
    name: "AppsDelete",
    file: TxIconOutline.IconAppsDelete,
    description: "AppsDelete",
    category: "Outline",
  },
  {
    name: "AppsSort",
    file: TxIconOutline.IconAppsSort,
    description: "AppsSort",
    category: "Outline",
  },
  {
    name: "Apps",
    file: TxIconOutline.IconApps,
    description: "Apps",
    category: "Outline",
  },
  {
    name: "Archive",
    file: TxIconOutline.IconArchive,
    description: "Archive",
    category: "Outline",
  },
  {
    name: "ArrowDown",
    file: TxIconOutline.IconArrowDown,
    description: "ArrowDown",
    category: "Outline",
  },
  {
    name: "ArrowFromBottom",
    file: TxIconOutline.IconArrowFromBottom,
    description: "ArrowFromBottom",
    category: "Outline",
  },
  {
    name: "ArrowLeft",
    file: TxIconOutline.IconArrowLeft,
    description: "ArrowLeft",
    category: "Outline",
  },
  {
    name: "ArrowRight",
    file: TxIconOutline.IconArrowRight,
    description: "ArrowRight",
    category: "Outline",
  },
  {
    name: "ArrowSmallDown",
    file: TxIconOutline.IconArrowSmallDown,
    description: "ArrowSmallDown",
    category: "Outline",
  },
  {
    name: "ArrowSmallLeft",
    file: TxIconOutline.IconArrowSmallLeft,
    description: "ArrowSmallLeft",
    category: "Outline",
  },
  {
    name: "ArrowSmallRight",
    file: TxIconOutline.IconArrowSmallRight,
    description: "ArrowSmallRight",
    category: "Outline",
  },
  {
    name: "ArrowSmallUp",
    file: TxIconOutline.IconArrowSmallUp,
    description: "ArrowSmallUp",
    category: "Outline",
  },
  {
    name: "ArrowUp",
    file: TxIconOutline.IconArrowUp,
    description: "ArrowUp",
    category: "Outline",
  },
  {
    name: "Asterik",
    file: TxIconOutline.IconAsterik,
    description: "Asterik",
    category: "Outline",
  },
  {
    name: "At",
    file: TxIconOutline.IconAt,
    description: "At",
    category: "Outline",
  },
  {
    name: "Backpack",
    file: TxIconOutline.IconBackpack,
    description: "Backpack",
    category: "Outline",
  },
  {
    name: "Badge",
    file: TxIconOutline.IconBadge,
    description: "Badge",
    category: "Outline",
  },
  {
    name: "Balloons",
    file: TxIconOutline.IconBalloons,
    description: "Balloons",
    category: "Outline",
  },
  {
    name: "Ban",
    file: TxIconOutline.IconBan,
    description: "Ban",
    category: "Outline",
  },
  {
    name: "BandAid",
    file: TxIconOutline.IconBandAid,
    description: "BandAid",
    category: "Outline",
  },
  {
    name: "Bank",
    file: TxIconOutline.IconBank,
    description: "Bank",
    category: "Outline",
  },
  {
    name: "BarberShop",
    file: TxIconOutline.IconBarberShop,
    description: "BarberShop",
    category: "Outline",
  },
  {
    name: "Baseball",
    file: TxIconOutline.IconBaseball,
    description: "Baseball",
    category: "Outline",
  },
  {
    name: "Basketball",
    file: TxIconOutline.IconBasketball,
    description: "Basketball",
    category: "Outline",
  },
  {
    name: "Bed",
    file: TxIconOutline.IconBed,
    description: "Bed",
    category: "Outline",
  },
  {
    name: "Beer",
    file: TxIconOutline.IconBeer,
    description: "Beer",
    category: "Outline",
  },
  {
    name: "BellRing",
    file: TxIconOutline.IconBellRing,
    description: "BellRing",
    category: "Outline",
  },
  {
    name: "BellSchool",
    file: TxIconOutline.IconBellSchool,
    description: "BellSchool",
    category: "Outline",
  },
  {
    name: "Bell",
    file: TxIconOutline.IconBell,
    description: "Bell",
    category: "Outline",
  },
  {
    name: "Bike",
    file: TxIconOutline.IconBike,
    description: "Bike",
    category: "Outline",
  },
  {
    name: "Billiard",
    file: TxIconOutline.IconBilliard,
    description: "Billiard",
    category: "Outline",
  },
  {
    name: "Bold",
    file: TxIconOutline.IconBold,
    description: "Bold",
    category: "Outline",
  },
  {
    name: "BookAlt",
    file: TxIconOutline.IconBookAlt,
    description: "BookAlt",
    category: "Outline",
  },
  {
    name: "Book",
    file: TxIconOutline.IconBook,
    description: "Book",
    category: "Outline",
  },
  {
    name: "Bookmark",
    file: TxIconOutline.IconBookmark,
    description: "Bookmark",
    category: "Outline",
  },
  {
    name: "Bowling",
    file: TxIconOutline.IconBowling,
    description: "Bowling",
    category: "Outline",
  },
  {
    name: "BoxAlt",
    file: TxIconOutline.IconBoxAlt,
    description: "BoxAlt",
    category: "Outline",
  },
  {
    name: "Box",
    file: TxIconOutline.IconBox,
    description: "Box",
    category: "Outline",
  },
  {
    name: "BreadSlice",
    file: TxIconOutline.IconBreadSlice,
    description: "BreadSlice",
    category: "Outline",
  },
  {
    name: "Briefcase",
    file: TxIconOutline.IconBriefcase,
    description: "Briefcase",
    category: "Outline",
  },
  {
    name: "Broom",
    file: TxIconOutline.IconBroom,
    description: "Broom",
    category: "Outline",
  },
  {
    name: "Browser",
    file: TxIconOutline.IconBrowser,
    description: "Browser",
    category: "Outline",
  },
  {
    name: "Brush",
    file: TxIconOutline.IconBrush,
    description: "Brush",
    category: "Outline",
  },
  {
    name: "Bug",
    file: TxIconOutline.IconBug,
    description: "Bug",
    category: "Outline",
  },
  {
    name: "Building",
    file: TxIconOutline.IconBuilding,
    description: "Building",
    category: "Outline",
  },
  {
    name: "Bulb",
    file: TxIconOutline.IconBulb,
    description: "Bulb",
    category: "Outline",
  },
  {
    name: "Butterfly",
    file: TxIconOutline.IconButterfly,
    description: "Butterfly",
    category: "Outline",
  },
  {
    name: "CakeBirthday",
    file: TxIconOutline.IconCakeBirthday,
    description: "CakeBirthday",
    category: "Outline",
  },
  {
    name: "CakeWedding",
    file: TxIconOutline.IconCakeWedding,
    description: "CakeWedding",
    category: "Outline",
  },
  {
    name: "Calculator",
    file: TxIconOutline.IconCalculator,
    description: "Calculator",
    category: "Outline",
  },
  {
    name: "Calendar",
    file: TxIconOutline.IconCalendar,
    description: "Calendar",
    category: "Outline",
  },
  {
    name: "CallHistory",
    file: TxIconOutline.IconCallHistory,
    description: "CallHistory",
    category: "Outline",
  },
  {
    name: "CallIncoming",
    file: TxIconOutline.IconCallIncoming,
    description: "CallIncoming",
    category: "Outline",
  },
  {
    name: "CallMissed",
    file: TxIconOutline.IconCallMissed,
    description: "CallMissed",
    category: "Outline",
  },
  {
    name: "CallOutgoing",
    file: TxIconOutline.IconCallOutgoing,
    description: "CallOutgoing",
    category: "Outline",
  },
  {
    name: "Camera",
    file: TxIconOutline.IconCamera,
    description: "Camera",
    category: "Outline",
  },
  {
    name: "Camping",
    file: TxIconOutline.IconCamping,
    description: "Camping",
    category: "Outline",
  },
  {
    name: "Car",
    file: TxIconOutline.IconCar,
    description: "Car",
    category: "Outline",
  },
  {
    name: "CaretDown",
    file: TxIconOutline.IconCaretDown,
    description: "CaretDown",
    category: "Outline",
  },
  {
    name: "CaretLeft",
    file: TxIconOutline.IconCaretLeft,
    description: "CaretLeft",
    category: "Outline",
  },
  {
    name: "CaretRight",
    file: TxIconOutline.IconCaretRight,
    description: "CaretRight",
    category: "Outline",
  },
  {
    name: "CaretUp",
    file: TxIconOutline.IconCaretUp,
    description: "CaretUp",
    category: "Outline",
  },
  {
    name: "Carrot",
    file: TxIconOutline.IconCarrot,
    description: "Carrot",
    category: "Outline",
  },
  {
    name: "ChartConnected",
    file: TxIconOutline.IconChartConnected,
    description: "ChartConnected",
    category: "Outline",
  },
  {
    name: "ChartHistogram",
    file: TxIconOutline.IconChartHistogram,
    description: "ChartHistogram",
    category: "Outline",
  },
  {
    name: "ChartNetwork",
    file: TxIconOutline.IconChartNetwork,
    description: "ChartNetwork",
    category: "Outline",
  },
  {
    name: "ChartPieAlt",
    file: TxIconOutline.IconChartPieAlt,
    description: "ChartPieAlt",
    category: "Outline",
  },
  {
    name: "ChartPie",
    file: TxIconOutline.IconChartPie,
    description: "ChartPie",
    category: "Outline",
  },
  {
    name: "ChartPyramid",
    file: TxIconOutline.IconChartPyramid,
    description: "ChartPyramid",
    category: "Outline",
  },
  {
    name: "ChartSetTheory",
    file: TxIconOutline.IconChartSetTheory,
    description: "ChartSetTheory",
    category: "Outline",
  },
  {
    name: "ChartTree",
    file: TxIconOutline.IconChartTree,
    description: "ChartTree",
    category: "Outline",
  },
  {
    name: "ChatArrowDown",
    file: TxIconOutline.IconChatArrowDown,
    description: "ChatArrowDown",
    category: "Outline",
  },
  {
    name: "ChatArrowGrow",
    file: TxIconOutline.IconChatArrowGrow,
    description: "ChatArrowGrow",
    category: "Outline",
  },
  {
    name: "Check",
    file: TxIconOutline.IconCheck,
    description: "Check",
    category: "Outline",
  },
  {
    name: "Checkbox",
    file: TxIconOutline.IconCheckbox,
    description: "Checkbox",
    category: "Outline",
  },
  {
    name: "Cheese",
    file: TxIconOutline.IconCheese,
    description: "Cheese",
    category: "Outline",
  },
  {
    name: "ChessPiece",
    file: TxIconOutline.IconChessPiece,
    description: "ChessPiece",
    category: "Outline",
  },
  {
    name: "ChildHead",
    file: TxIconOutline.IconChildHead,
    description: "ChildHead",
    category: "Outline",
  },
  {
    name: "CircleSmall",
    file: TxIconOutline.IconCircleSmall,
    description: "CircleSmall",
    category: "Outline",
  },
  {
    name: "Circle",
    file: TxIconOutline.IconCircle,
    description: "Circle",
    category: "Outline",
  },
  {
    name: "Clip",
    file: TxIconOutline.IconClip,
    description: "Clip",
    category: "Outline",
  },
  {
    name: "Clock",
    file: TxIconOutline.IconClock,
    description: "Clock",
    category: "Outline",
  },
  {
    name: "CloudCheck",
    file: TxIconOutline.IconCloudCheck,
    description: "CloudCheck",
    category: "Outline",
  },
  {
    name: "CloudDisabled",
    file: TxIconOutline.IconCloudDisabled,
    description: "CloudDisabled",
    category: "Outline",
  },
  {
    name: "CloudDownload",
    file: TxIconOutline.IconCloudDownload,
    description: "CloudDownload",
    category: "Outline",
  },
  {
    name: "CloudShare",
    file: TxIconOutline.IconCloudShare,
    description: "CloudShare",
    category: "Outline",
  },
  {
    name: "CloudUpload",
    file: TxIconOutline.IconCloudUpload,
    description: "CloudUpload",
    category: "Outline",
  },
  {
    name: "Cloud",
    file: TxIconOutline.IconCloud,
    description: "Cloud",
    category: "Outline",
  },
  {
    name: "Clouds",
    file: TxIconOutline.IconClouds,
    description: "Clouds",
    category: "Outline",
  },
  {
    name: "Cocktail",
    file: TxIconOutline.IconCocktail,
    description: "Cocktail",
    category: "Outline",
  },
  {
    name: "Coffee",
    file: TxIconOutline.IconCoffee,
    description: "Coffee",
    category: "Outline",
  },
  {
    name: "CommentAlt",
    file: TxIconOutline.IconCommentAlt,
    description: "CommentAlt",
    category: "Outline",
  },
  {
    name: "CommentCheck",
    file: TxIconOutline.IconCommentCheck,
    description: "CommentCheck",
    category: "Outline",
  },
  {
    name: "CommentHeart",
    file: TxIconOutline.IconCommentHeart,
    description: "CommentHeart",
    category: "Outline",
  },
  {
    name: "CommentInfo",
    file: TxIconOutline.IconCommentInfo,
    description: "CommentInfo",
    category: "Outline",
  },
  {
    name: "CommentUser",
    file: TxIconOutline.IconCommentUser,
    description: "CommentUser",
    category: "Outline",
  },
  {
    name: "Comment",
    file: TxIconOutline.IconComment,
    description: "Comment",
    category: "Outline",
  },
  {
    name: "Comments",
    file: TxIconOutline.IconComments,
    description: "Comments",
    category: "Outline",
  },
  {
    name: "CompressAlt",
    file: TxIconOutline.IconCompressAlt,
    description: "CompressAlt",
    category: "Outline",
  },
  {
    name: "Compress",
    file: TxIconOutline.IconCompress,
    description: "Compress",
    category: "Outline",
  },
  {
    name: "Computer",
    file: TxIconOutline.IconComputer,
    description: "Computer",
    category: "Outline",
  },
  {
    name: "Confetti",
    file: TxIconOutline.IconConfetti,
    description: "Confetti",
    category: "Outline",
  },
  {
    name: "Cookie",
    file: TxIconOutline.IconCookie,
    description: "Cookie",
    category: "Outline",
  },
  {
    name: "CopyAlt",
    file: TxIconOutline.IconCopyAlt,
    description: "CopyAlt",
    category: "Outline",
  },
  {
    name: "Copy",
    file: TxIconOutline.IconCopy,
    description: "Copy",
    category: "Outline",
  },
  {
    name: "Copyright",
    file: TxIconOutline.IconCopyright,
    description: "Copyright",
    category: "Outline",
  },
  {
    name: "Cow",
    file: TxIconOutline.IconCow,
    description: "Cow",
    category: "Outline",
  },
  {
    name: "Cream",
    file: TxIconOutline.IconCream,
    description: "Cream",
    category: "Outline",
  },
  {
    name: "CreditCard",
    file: TxIconOutline.IconCreditCard,
    description: "CreditCard",
    category: "Outline",
  },
  {
    name: "Croissant",
    file: TxIconOutline.IconCroissant,
    description: "Croissant",
    category: "Outline",
  },
  {
    name: "CrossCircle",
    file: TxIconOutline.IconCrossCircle,
    description: "CrossCircle",
    category: "Outline",
  },
  {
    name: "CrossSmall",
    file: TxIconOutline.IconCrossSmall,
    description: "CrossSmall",
    category: "Outline",
  },
  {
    name: "Cross",
    file: TxIconOutline.IconCross,
    description: "Cross",
    category: "Outline",
  },
  {
    name: "Crown",
    file: TxIconOutline.IconCrown,
    description: "Crown",
    category: "Outline",
  },
  {
    name: "Cube",
    file: TxIconOutline.IconCube,
    description: "Cube",
    category: "Outline",
  },
  {
    name: "Cupcake",
    file: TxIconOutline.IconCupcake,
    description: "Cupcake",
    category: "Outline",
  },
  {
    name: "CursorFinger",
    file: TxIconOutline.IconCursorFinger,
    description: "CursorFinger",
    category: "Outline",
  },
  {
    name: "CursorPlus",
    file: TxIconOutline.IconCursorPlus,
    description: "CursorPlus",
    category: "Outline",
  },
  {
    name: "CursorTextAlt",
    file: TxIconOutline.IconCursorTextAlt,
    description: "CursorTextAlt",
    category: "Outline",
  },
  {
    name: "CursorText",
    file: TxIconOutline.IconCursorText,
    description: "CursorText",
    category: "Outline",
  },
  {
    name: "Cursor",
    file: TxIconOutline.IconCursor,
    description: "Cursor",
    category: "Outline",
  },
  {
    name: "Dart",
    file: TxIconOutline.IconDart,
    description: "Dart",
    category: "Outline",
  },
  {
    name: "Dashboard",
    file: TxIconOutline.IconDashboard,
    description: "Dashboard",
    category: "Outline",
  },
  {
    name: "DataTransfer",
    file: TxIconOutline.IconDataTransfer,
    description: "DataTransfer",
    category: "Outline",
  },
  {
    name: "Database",
    file: TxIconOutline.IconDatabase,
    description: "Database",
    category: "Outline",
  },
  {
    name: "Delete",
    file: TxIconOutline.IconDelete,
    description: "Delete",
    category: "Outline",
  },
  {
    name: "Diamond",
    file: TxIconOutline.IconDiamond,
    description: "Diamond",
    category: "Outline",
  },
  {
    name: "Dice",
    file: TxIconOutline.IconDice,
    description: "Dice",
    category: "Outline",
  },
  {
    name: "Diploma",
    file: TxIconOutline.IconDiploma,
    description: "Diploma",
    category: "Outline",
  },
  {
    name: "DiscoBall",
    file: TxIconOutline.IconDiscoBall,
    description: "DiscoBall",
    category: "Outline",
  },
  {
    name: "Disk",
    file: TxIconOutline.IconDisk,
    description: "Disk",
    category: "Outline",
  },
  {
    name: "Doctor",
    file: TxIconOutline.IconDoctor,
    description: "Doctor",
    category: "Outline",
  },
  {
    name: "DocumentSigned",
    file: TxIconOutline.IconDocumentSigned,
    description: "DocumentSigned",
    category: "Outline",
  },
  {
    name: "Document",
    file: TxIconOutline.IconDocument,
    description: "Document",
    category: "Outline",
  },
  {
    name: "Dollar",
    file: TxIconOutline.IconDollar,
    description: "Dollar",
    category: "Outline",
  },
  {
    name: "Download",
    file: TxIconOutline.IconDownload,
    description: "Download",
    category: "Outline",
  },
  {
    name: "DrinkAlt",
    file: TxIconOutline.IconDrinkAlt,
    description: "DrinkAlt",
    category: "Outline",
  },
  {
    name: "Drumstick",
    file: TxIconOutline.IconDrumstick,
    description: "Drumstick",
    category: "Outline",
  },
  {
    name: "Duplicate",
    file: TxIconOutline.IconDuplicate,
    description: "Duplicate",
    category: "Outline",
  },
  {
    name: "ELearning",
    file: TxIconOutline.IconELearning,
    description: "ELearning",
    category: "Outline",
  },
  {
    name: "Earnings",
    file: TxIconOutline.IconEarnings,
    description: "Earnings",
    category: "Outline",
  },
  {
    name: "EditAlt",
    file: TxIconOutline.IconEditAlt,
    description: "EditAlt",
    category: "Outline",
  },
  {
    name: "Edit",
    file: TxIconOutline.IconEdit,
    description: "Edit",
    category: "Outline",
  },
  {
    name: "EnvelopeBan",
    file: TxIconOutline.IconEnvelopeBan,
    description: "EnvelopeBan",
    category: "Outline",
  },
  {
    name: "EnvelopeDownload",
    file: TxIconOutline.IconEnvelopeDownload,
    description: "EnvelopeDownload",
    category: "Outline",
  },
  {
    name: "EnvelopeMarker",
    file: TxIconOutline.IconEnvelopeMarker,
    description: "EnvelopeMarker",
    category: "Outline",
  },
  {
    name: "EnvelopeOpen",
    file: TxIconOutline.IconEnvelopeOpen,
    description: "EnvelopeOpen",
    category: "Outline",
  },
  {
    name: "EnvelopePlus",
    file: TxIconOutline.IconEnvelopePlus,
    description: "EnvelopePlus",
    category: "Outline",
  },
  {
    name: "Envelope",
    file: TxIconOutline.IconEnvelope,
    description: "Envelope",
    category: "Outline",
  },
  {
    name: "Euro",
    file: TxIconOutline.IconEuro,
    description: "Euro",
    category: "Outline",
  },
  {
    name: "Exclamation",
    file: TxIconOutline.IconExclamation,
    description: "Exclamation",
    category: "Outline",
  },
  {
    name: "Expand",
    file: TxIconOutline.IconExpand,
    description: "Expand",
    category: "Outline",
  },
  {
    name: "EyeCrossed",
    file: TxIconOutline.IconEyeCrossed,
    description: "EyeCrossed",
    category: "Outline",
  },
  {
    name: "EyeDropper",
    file: TxIconOutline.IconEyeDropper,
    description: "EyeDropper",
    category: "Outline",
  },
  {
    name: "Eye",
    file: TxIconOutline.IconEye,
    description: "Eye",
    category: "Outline",
  },
  {
    name: "Feather",
    file: TxIconOutline.IconFeather,
    description: "Feather",
    category: "Outline",
  },
  {
    name: "FerrisWheel",
    file: TxIconOutline.IconFerrisWheel,
    description: "FerrisWheel",
    category: "Outline",
  },
  {
    name: "FileAdd",
    file: TxIconOutline.IconFileAdd,
    description: "FileAdd",
    category: "Outline",
  },
  {
    name: "FileAi",
    file: TxIconOutline.IconFileAi,
    description: "FileAi",
    category: "Outline",
  },
  {
    name: "FileCheck",
    file: TxIconOutline.IconFileCheck,
    description: "FileCheck",
    category: "Outline",
  },
  {
    name: "FileDelete",
    file: TxIconOutline.IconFileDelete,
    description: "FileDelete",
    category: "Outline",
  },
  {
    name: "FileEps",
    file: TxIconOutline.IconFileEps,
    description: "FileEps",
    category: "Outline",
  },
  {
    name: "FileGif",
    file: TxIconOutline.IconFileGif,
    description: "FileGif",
    category: "Outline",
  },
  {
    name: "FileMusic",
    file: TxIconOutline.IconFileMusic,
    description: "FileMusic",
    category: "Outline",
  },
  {
    name: "FilePsd",
    file: TxIconOutline.IconFilePsd,
    description: "FilePsd",
    category: "Outline",
  },
  {
    name: "File",
    file: TxIconOutline.IconFile,
    description: "File",
    category: "Outline",
  },
  {
    name: "Fill",
    file: TxIconOutline.IconFill,
    description: "Fill",
    category: "Outline",
  },
  {
    name: "Film",
    file: TxIconOutline.IconFilm,
    description: "Film",
    category: "Outline",
  },
  {
    name: "Filter",
    file: TxIconOutline.IconFilter,
    description: "Filter",
    category: "Outline",
  },
  {
    name: "Fingerprint",
    file: TxIconOutline.IconFingerprint,
    description: "Fingerprint",
    category: "Outline",
  },
  {
    name: "Fish",
    file: TxIconOutline.IconFish,
    description: "Fish",
    category: "Outline",
  },
  {
    name: "Flag",
    file: TxIconOutline.IconFlag,
    description: "Flag",
    category: "Outline",
  },
  {
    name: "Flame",
    file: TxIconOutline.IconFlame,
    description: "Flame",
    category: "Outline",
  },
  {
    name: "FlipHorizontal",
    file: TxIconOutline.IconFlipHorizontal,
    description: "FlipHorizontal",
    category: "Outline",
  },
  {
    name: "FlowerBouquet",
    file: TxIconOutline.IconFlowerBouquet,
    description: "FlowerBouquet",
    category: "Outline",
  },
  {
    name: "FlowerTulip",
    file: TxIconOutline.IconFlowerTulip,
    description: "FlowerTulip",
    category: "Outline",
  },
  {
    name: "Flower",
    file: TxIconOutline.IconFlower,
    description: "Flower",
    category: "Outline",
  },
  {
    name: "FolderAdd",
    file: TxIconOutline.IconFolderAdd,
    description: "FolderAdd",
    category: "Outline",
  },
  {
    name: "Folder",
    file: TxIconOutline.IconFolder,
    description: "Folder",
    category: "Outline",
  },
  {
    name: "Following",
    file: TxIconOutline.IconFollowing,
    description: "Following",
    category: "Outline",
  },
  {
    name: "Football",
    file: TxIconOutline.IconFootball,
    description: "Football",
    category: "Outline",
  },
  {
    name: "Form",
    file: TxIconOutline.IconForm,
    description: "Form",
    category: "Outline",
  },
  {
    name: "Forward",
    file: TxIconOutline.IconForward,
    description: "Forward",
    category: "Outline",
  },
  {
    name: "Fox",
    file: TxIconOutline.IconFox,
    description: "Fox",
    category: "Outline",
  },
  {
    name: "Frown",
    file: TxIconOutline.IconFrown,
    description: "Frown",
    category: "Outline",
  },
  {
    name: "Ftp",
    file: TxIconOutline.IconFtp,
    description: "Ftp",
    category: "Outline",
  },
  {
    name: "Gallery",
    file: TxIconOutline.IconGallery,
    description: "Gallery",
    category: "Outline",
  },
  {
    name: "Gamepad",
    file: TxIconOutline.IconGamepad,
    description: "Gamepad",
    category: "Outline",
  },
  {
    name: "GasPump",
    file: TxIconOutline.IconGasPump,
    description: "GasPump",
    category: "Outline",
  },
  {
    name: "Gem",
    file: TxIconOutline.IconGem,
    description: "Gem",
    category: "Outline",
  },
  {
    name: "Gift",
    file: TxIconOutline.IconGift,
    description: "Gift",
    category: "Outline",
  },
  {
    name: "GlassCheers",
    file: TxIconOutline.IconGlassCheers,
    description: "GlassCheers",
    category: "Outline",
  },
  {
    name: "Glasses",
    file: TxIconOutline.IconGlasses,
    description: "Glasses",
    category: "Outline",
  },
  {
    name: "GlobeAlt",
    file: TxIconOutline.IconGlobeAlt,
    description: "GlobeAlt",
    category: "Outline",
  },
  {
    name: "Globe",
    file: TxIconOutline.IconGlobe,
    description: "Globe",
    category: "Outline",
  },
  {
    name: "Golf",
    file: TxIconOutline.IconGolf,
    description: "Golf",
    category: "Outline",
  },
  {
    name: "GraduationCap",
    file: TxIconOutline.IconGraduationCap,
    description: "GraduationCap",
    category: "Outline",
  },
  {
    name: "GraphicTablet",
    file: TxIconOutline.IconGraphicTablet,
    description: "GraphicTablet",
    category: "Outline",
  },
  {
    name: "GridAlt",
    file: TxIconOutline.IconGridAlt,
    description: "GridAlt",
    category: "Outline",
  },
  {
    name: "Grid",
    file: TxIconOutline.IconGrid,
    description: "Grid",
    category: "Outline",
  },
  {
    name: "Guitar",
    file: TxIconOutline.IconGuitar,
    description: "Guitar",
    category: "Outline",
  },
  {
    name: "Gym",
    file: TxIconOutline.IconGym,
    description: "Gym",
    category: "Outline",
  },
  {
    name: "Hamburger",
    file: TxIconOutline.IconHamburger,
    description: "Hamburger",
    category: "Outline",
  },
  {
    name: "HandHoldingHeart",
    file: TxIconOutline.IconHandHoldingHeart,
    description: "HandHoldingHeart",
    category: "Outline",
  },
  {
    name: "Hastag",
    file: TxIconOutline.IconHastag,
    description: "Hastag",
    category: "Outline",
  },
  {
    name: "HatBirthday",
    file: TxIconOutline.IconHatBirthday,
    description: "HatBirthday",
    category: "Outline",
  },
  {
    name: "HeadSideThinking",
    file: TxIconOutline.IconHeadSideThinking,
    description: "HeadSideThinking",
    category: "Outline",
  },
  {
    name: "Headphones",
    file: TxIconOutline.IconHeadphones,
    description: "Headphones",
    category: "Outline",
  },
  {
    name: "Headset",
    file: TxIconOutline.IconHeadset,
    description: "Headset",
    category: "Outline",
  },
  {
    name: "HeartArrow",
    file: TxIconOutline.IconHeartArrow,
    description: "HeartArrow",
    category: "Outline",
  },
  {
    name: "Heart",
    file: TxIconOutline.IconHeart,
    description: "Heart",
    category: "Outline",
  },
  {
    name: "HomeLocationAlt",
    file: TxIconOutline.IconHomeLocationAlt,
    description: "HomeLocationAlt",
    category: "Outline",
  },
  {
    name: "HomeLocation",
    file: TxIconOutline.IconHomeLocation,
    description: "HomeLocation",
    category: "Outline",
  },
  {
    name: "Home",
    file: TxIconOutline.IconHome,
    description: "Home",
    category: "Outline",
  },
  {
    name: "HourglassEnd",
    file: TxIconOutline.IconHourglassEnd,
    description: "HourglassEnd",
    category: "Outline",
  },
  {
    name: "Hourglass",
    file: TxIconOutline.IconHourglass,
    description: "Hourglass",
    category: "Outline",
  },
  {
    name: "IceCream",
    file: TxIconOutline.IconIceCream,
    description: "IceCream",
    category: "Outline",
  },
  {
    name: "IceSkate",
    file: TxIconOutline.IconIceSkate,
    description: "IceSkate",
    category: "Outline",
  },
  {
    name: "IdBadge",
    file: TxIconOutline.IconIdBadge,
    description: "IdBadge",
    category: "Outline",
  },
  {
    name: "Inbox",
    file: TxIconOutline.IconInbox,
    description: "Inbox",
    category: "Outline",
  },
  {
    name: "Incognito",
    file: TxIconOutline.IconIncognito,
    description: "Incognito",
    category: "Outline",
  },
  {
    name: "Indent",
    file: TxIconOutline.IconIndent,
    description: "Indent",
    category: "Outline",
  },
  {
    name: "Infinity",
    file: TxIconOutline.IconInfinity,
    description: "Infinity",
    category: "Outline",
  },
  {
    name: "Info",
    file: TxIconOutline.IconInfo,
    description: "Info",
    category: "Outline",
  },
  {
    name: "Interactive",
    file: TxIconOutline.IconInteractive,
    description: "Interactive",
    category: "Outline",
  },
  {
    name: "Interlining",
    file: TxIconOutline.IconInterlining,
    description: "Interlining",
    category: "Outline",
  },
  {
    name: "Interrogation",
    file: TxIconOutline.IconInterrogation,
    description: "Interrogation",
    category: "Outline",
  },
  {
    name: "Italic",
    file: TxIconOutline.IconItalic,
    description: "Italic",
    category: "Outline",
  },
  {
    name: "Jpg",
    file: TxIconOutline.IconJpg,
    description: "Jpg",
    category: "Outline",
  },
  {
    name: "Key",
    file: TxIconOutline.IconKey,
    description: "Key",
    category: "Outline",
  },
  {
    name: "Keyboard",
    file: TxIconOutline.IconKeyboard,
    description: "Keyboard",
    category: "Outline",
  },
  {
    name: "Kite",
    file: TxIconOutline.IconKite,
    description: "Kite",
    category: "Outline",
  },
  {
    name: "Label",
    file: TxIconOutline.IconLabel,
    description: "Label",
    category: "Outline",
  },
  {
    name: "Laptop",
    file: TxIconOutline.IconLaptop,
    description: "Laptop",
    category: "Outline",
  },
  {
    name: "Lasso",
    file: TxIconOutline.IconLasso,
    description: "Lasso",
    category: "Outline",
  },
  {
    name: "Laugh",
    file: TxIconOutline.IconLaugh,
    description: "Laugh",
    category: "Outline",
  },
  {
    name: "Layers",
    file: TxIconOutline.IconLayers,
    description: "Layers",
    category: "Outline",
  },
  {
    name: "LayoutFluid",
    file: TxIconOutline.IconLayoutFluid,
    description: "LayoutFluid",
    category: "Outline",
  },
  {
    name: "Leaf",
    file: TxIconOutline.IconLeaf,
    description: "Leaf",
    category: "Outline",
  },
  {
    name: "LetterCase",
    file: TxIconOutline.IconLetterCase,
    description: "LetterCase",
    category: "Outline",
  },
  {
    name: "LifeRing",
    file: TxIconOutline.IconLifeRing,
    description: "LifeRing",
    category: "Outline",
  },
  {
    name: "LineWidth",
    file: TxIconOutline.IconLineWidth,
    description: "LineWidth",
    category: "Outline",
  },
  {
    name: "Link",
    file: TxIconOutline.IconLink,
    description: "Link",
    category: "Outline",
  },
  {
    name: "Lipstick",
    file: TxIconOutline.IconLipstick,
    description: "Lipstick",
    category: "Outline",
  },
  {
    name: "ListCheck",
    file: TxIconOutline.IconListCheck,
    description: "ListCheck",
    category: "Outline",
  },
  {
    name: "List",
    file: TxIconOutline.IconList,
    description: "List",
    category: "Outline",
  },
  {
    name: "LocationAlt",
    file: TxIconOutline.IconLocationAlt,
    description: "LocationAlt",
    category: "Outline",
  },
  {
    name: "LockAlt",
    file: TxIconOutline.IconLockAlt,
    description: "LockAlt",
    category: "Outline",
  },
  {
    name: "Lock",
    file: TxIconOutline.IconLock,
    description: "Lock",
    category: "Outline",
  },
  {
    name: "LuggageRolling",
    file: TxIconOutline.IconLuggageRolling,
    description: "LuggageRolling",
    category: "Outline",
  },
  {
    name: "MagicWand",
    file: TxIconOutline.IconMagicWand,
    description: "MagicWand",
    category: "Outline",
  },
  {
    name: "MakeupBrush",
    file: TxIconOutline.IconMakeupBrush,
    description: "MakeupBrush",
    category: "Outline",
  },
  {
    name: "ManHead",
    file: TxIconOutline.IconManHead,
    description: "ManHead",
    category: "Outline",
  },
  {
    name: "MapMarkerCross",
    file: TxIconOutline.IconMapMarkerCross,
    description: "MapMarkerCross",
    category: "Outline",
  },
  {
    name: "MapMarkerHome",
    file: TxIconOutline.IconMapMarkerHome,
    description: "MapMarkerHome",
    category: "Outline",
  },
  {
    name: "MapMarkerMinus",
    file: TxIconOutline.IconMapMarkerMinus,
    description: "MapMarkerMinus",
    category: "Outline",
  },
  {
    name: "MapMarkerPlus",
    file: TxIconOutline.IconMapMarkerPlus,
    description: "MapMarkerPlus",
    category: "Outline",
  },
  {
    name: "MapMarker",
    file: TxIconOutline.IconMapMarker,
    description: "MapMarker",
    category: "Outline",
  },
  {
    name: "Map",
    file: TxIconOutline.IconMap,
    description: "Map",
    category: "Outline",
  },
  {
    name: "MarkerTime",
    file: TxIconOutline.IconMarkerTime,
    description: "MarkerTime",
    category: "Outline",
  },
  {
    name: "Marker",
    file: TxIconOutline.IconMarker,
    description: "Marker",
    category: "Outline",
  },
  {
    name: "MarsDouble",
    file: TxIconOutline.IconMarsDouble,
    description: "MarsDouble",
    category: "Outline",
  },
  {
    name: "Mars",
    file: TxIconOutline.IconMars,
    description: "Mars",
    category: "Outline",
  },
  {
    name: "MaskCarnival",
    file: TxIconOutline.IconMaskCarnival,
    description: "MaskCarnival",
    category: "Outline",
  },
  {
    name: "Medicine",
    file: TxIconOutline.IconMedicine,
    description: "Medicine",
    category: "Outline",
  },
  {
    name: "Megaphone",
    file: TxIconOutline.IconMegaphone,
    description: "Megaphone",
    category: "Outline",
  },
  {
    name: "Meh",
    file: TxIconOutline.IconMeh,
    description: "Meh",
    category: "Outline",
  },
  {
    name: "MenuBurger",
    file: TxIconOutline.IconMenuBurger,
    description: "MenuBurger",
    category: "Outline",
  },
  {
    name: "MenuDotsVertical",
    file: TxIconOutline.IconMenuDotsVertical,
    description: "MenuDotsVertical",
    category: "Outline",
  },
  {
    name: "MenuDots",
    file: TxIconOutline.IconMenuDots,
    description: "MenuDots",
    category: "Outline",
  },
  {
    name: "MicrophoneAlt",
    file: TxIconOutline.IconMicrophoneAlt,
    description: "MicrophoneAlt",
    category: "Outline",
  },
  {
    name: "Microphone",
    file: TxIconOutline.IconMicrophone,
    description: "Microphone",
    category: "Outline",
  },
  {
    name: "MinusSmall",
    file: TxIconOutline.IconMinusSmall,
    description: "MinusSmall",
    category: "Outline",
  },
  {
    name: "Minus",
    file: TxIconOutline.IconMinus,
    description: "Minus",
    category: "Outline",
  },
  {
    name: "Mobile",
    file: TxIconOutline.IconMobile,
    description: "Mobile",
    category: "Outline",
  },
  {
    name: "ModeLandscape",
    file: TxIconOutline.IconModeLandscape,
    description: "ModeLandscape",
    category: "Outline",
  },
  {
    name: "ModePortrait",
    file: TxIconOutline.IconModePortrait,
    description: "ModePortrait",
    category: "Outline",
  },
  {
    name: "Money",
    file: TxIconOutline.IconMoney,
    description: "Money",
    category: "Outline",
  },
  {
    name: "Moon",
    file: TxIconOutline.IconMoon,
    description: "Moon",
    category: "Outline",
  },
  {
    name: "Mountains",
    file: TxIconOutline.IconMountains,
    description: "Mountains",
    category: "Outline",
  },
  {
    name: "Mouse",
    file: TxIconOutline.IconMouse,
    description: "Mouse",
    category: "Outline",
  },
  {
    name: "MugAlt",
    file: TxIconOutline.IconMugAlt,
    description: "MugAlt",
    category: "Outline",
  },
  {
    name: "MusicAlt",
    file: TxIconOutline.IconMusicAlt,
    description: "MusicAlt",
    category: "Outline",
  },
  {
    name: "Music",
    file: TxIconOutline.IconMusic,
    description: "Music",
    category: "Outline",
  },
  {
    name: "Navigation",
    file: TxIconOutline.IconNavigation,
    description: "Navigation",
    category: "Outline",
  },
  {
    name: "NetworkCloud",
    file: TxIconOutline.IconNetworkCloud,
    description: "NetworkCloud",
    category: "Outline",
  },
  {
    name: "Network",
    file: TxIconOutline.IconNetwork,
    description: "Network",
    category: "Outline",
  },
  {
    name: "Notebook",
    file: TxIconOutline.IconNotebook,
    description: "Notebook",
    category: "Outline",
  },
  {
    name: "Opacity",
    file: TxIconOutline.IconOpacity,
    description: "Opacity",
    category: "Outline",
  },
  {
    name: "Package",
    file: TxIconOutline.IconPackage,
    description: "Package",
    category: "Outline",
  },
  {
    name: "PaintBrush",
    file: TxIconOutline.IconPaintBrush,
    description: "PaintBrush",
    category: "Outline",
  },
  {
    name: "Palette",
    file: TxIconOutline.IconPalette,
    description: "Palette",
    category: "Outline",
  },
  {
    name: "PaperPlane",
    file: TxIconOutline.IconPaperPlane,
    description: "PaperPlane",
    category: "Outline",
  },
  {
    name: "Password",
    file: TxIconOutline.IconPassword,
    description: "Password",
    category: "Outline",
  },
  {
    name: "Pause",
    file: TxIconOutline.IconPause,
    description: "Pause",
    category: "Outline",
  },
  {
    name: "Paw",
    file: TxIconOutline.IconPaw,
    description: "Paw",
    category: "Outline",
  },
  {
    name: "Pencil",
    file: TxIconOutline.IconPencil,
    description: "Pencil",
    category: "Outline",
  },
  {
    name: "Pharmacy",
    file: TxIconOutline.IconPharmacy,
    description: "Pharmacy",
    category: "Outline",
  },
  {
    name: "PhoneCall",
    file: TxIconOutline.IconPhoneCall,
    description: "PhoneCall",
    category: "Outline",
  },
  {
    name: "PhoneCross",
    file: TxIconOutline.IconPhoneCross,
    description: "PhoneCross",
    category: "Outline",
  },
  {
    name: "PhonePause",
    file: TxIconOutline.IconPhonePause,
    description: "PhonePause",
    category: "Outline",
  },
  {
    name: "PhoneSlash",
    file: TxIconOutline.IconPhoneSlash,
    description: "PhoneSlash",
    category: "Outline",
  },
  {
    name: "Physics",
    file: TxIconOutline.IconPhysics,
    description: "Physics",
    category: "Outline",
  },
  {
    name: "Picture",
    file: TxIconOutline.IconPicture,
    description: "Picture",
    category: "Outline",
  },
  {
    name: "PingPong",
    file: TxIconOutline.IconPingPong,
    description: "PingPong",
    category: "Outline",
  },
  {
    name: "PizzaSlice",
    file: TxIconOutline.IconPizzaSlice,
    description: "PizzaSlice",
    category: "Outline",
  },
  {
    name: "Plane",
    file: TxIconOutline.IconPlane,
    description: "Plane",
    category: "Outline",
  },
  {
    name: "PlayAlt",
    file: TxIconOutline.IconPlayAlt,
    description: "PlayAlt",
    category: "Outline",
  },
  {
    name: "Play",
    file: TxIconOutline.IconPlay,
    description: "Play",
    category: "Outline",
  },
  {
    name: "PlayingCards",
    file: TxIconOutline.IconPlayingCards,
    description: "PlayingCards",
    category: "Outline",
  },
  {
    name: "PlusSmall",
    file: TxIconOutline.IconPlusSmall,
    description: "PlusSmall",
    category: "Outline",
  },
  {
    name: "Plus",
    file: TxIconOutline.IconPlus,
    description: "Plus",
    category: "Outline",
  },
  {
    name: "PokerChip",
    file: TxIconOutline.IconPokerChip,
    description: "PokerChip",
    category: "Outline",
  },
  {
    name: "Portrait",
    file: TxIconOutline.IconPortrait,
    description: "Portrait",
    category: "Outline",
  },
  {
    name: "Pound",
    file: TxIconOutline.IconPound,
    description: "Pound",
    category: "Outline",
  },
  {
    name: "Power",
    file: TxIconOutline.IconPower,
    description: "Power",
    category: "Outline",
  },
  {
    name: "Presentation",
    file: TxIconOutline.IconPresentation,
    description: "Presentation",
    category: "Outline",
  },
  {
    name: "Print",
    file: TxIconOutline.IconPrint,
    description: "Print",
    category: "Outline",
  },
  {
    name: "Protractor",
    file: TxIconOutline.IconProtractor,
    description: "Protractor",
    category: "Outline",
  },
  {
    name: "Pulse",
    file: TxIconOutline.IconPulse,
    description: "Pulse",
    category: "Outline",
  },
  {
    name: "Pyramid",
    file: TxIconOutline.IconPyramid,
    description: "Pyramid",
    category: "Outline",
  },
  {
    name: "QuoteRight",
    file: TxIconOutline.IconQuoteRight,
    description: "QuoteRight",
    category: "Outline",
  },
  {
    name: "Rainbow",
    file: TxIconOutline.IconRainbow,
    description: "Rainbow",
    category: "Outline",
  },
  {
    name: "Raindrops",
    file: TxIconOutline.IconRaindrops,
    description: "Raindrops",
    category: "Outline",
  },
  {
    name: "Rec",
    file: TxIconOutline.IconRec,
    description: "Rec",
    category: "Outline",
  },
  {
    name: "Receipt",
    file: TxIconOutline.IconReceipt,
    description: "Receipt",
    category: "Outline",
  },
  {
    name: "RecordVinyl",
    file: TxIconOutline.IconRecordVinyl,
    description: "RecordVinyl",
    category: "Outline",
  },
  {
    name: "RectabgleVertical",
    file: TxIconOutline.IconRectabgleVertical,
    description: "RectabgleVertical",
    category: "Outline",
  },
  {
    name: "RectangleHorizontal",
    file: TxIconOutline.IconRectangleHorizontal,
    description: "RectangleHorizontal",
    category: "Outline",
  },
  {
    name: "RectanglePanoramic",
    file: TxIconOutline.IconRectanglePanoramic,
    description: "RectanglePanoramic",
    category: "Outline",
  },
  {
    name: "Recycle",
    file: TxIconOutline.IconRecycle,
    description: "Recycle",
    category: "Outline",
  },
  {
    name: "RedoAlt",
    file: TxIconOutline.IconRedoAlt,
    description: "RedoAlt",
    category: "Outline",
  },
  {
    name: "Redo",
    file: TxIconOutline.IconRedo,
    description: "Redo",
    category: "Outline",
  },
  {
    name: "Reflect",
    file: TxIconOutline.IconReflect,
    description: "Reflect",
    category: "Outline",
  },
  {
    name: "Refresh",
    file: TxIconOutline.IconRefresh,
    description: "Refresh",
    category: "Outline",
  },
  {
    name: "Resize",
    file: TxIconOutline.IconResize,
    description: "Resize",
    category: "Outline",
  },
  {
    name: "Resources",
    file: TxIconOutline.IconResources,
    description: "Resources",
    category: "Outline",
  },
  {
    name: "Rewind",
    file: TxIconOutline.IconRewind,
    description: "Rewind",
    category: "Outline",
  },
  {
    name: "Rhombus",
    file: TxIconOutline.IconRhombus,
    description: "Rhombus",
    category: "Outline",
  },
  {
    name: "RingsWedding",
    file: TxIconOutline.IconRingsWedding,
    description: "RingsWedding",
    category: "Outline",
  },
  {
    name: "Road",
    file: TxIconOutline.IconRoad,
    description: "Road",
    category: "Outline",
  },
  {
    name: "Rocket",
    file: TxIconOutline.IconRocket,
    description: "Rocket",
    category: "Outline",
  },
  {
    name: "RoomService",
    file: TxIconOutline.IconRoomService,
    description: "RoomService",
    category: "Outline",
  },
  {
    name: "RotateRight",
    file: TxIconOutline.IconRotateRight,
    description: "RotateRight",
    category: "Outline",
  },
  {
    name: "Rugby",
    file: TxIconOutline.IconRugby,
    description: "Rugby",
    category: "Outline",
  },
  {
    name: "Sad",
    file: TxIconOutline.IconSad,
    description: "Sad",
    category: "Outline",
  },
  {
    name: "Salad",
    file: TxIconOutline.IconSalad,
    description: "Salad",
    category: "Outline",
  },
  {
    name: "Scale",
    file: TxIconOutline.IconScale,
    description: "Scale",
    category: "Outline",
  },
  {
    name: "SchoolBus",
    file: TxIconOutline.IconSchoolBus,
    description: "SchoolBus",
    category: "Outline",
  },
  {
    name: "School",
    file: TxIconOutline.IconSchool,
    description: "School",
    category: "Outline",
  },
  {
    name: "Scissors",
    file: TxIconOutline.IconScissors,
    description: "Scissors",
    category: "Outline",
  },
  {
    name: "Screen",
    file: TxIconOutline.IconScreen,
    description: "Screen",
    category: "Outline",
  },
  {
    name: "SearchAlt",
    file: TxIconOutline.IconSearchAlt,
    description: "SearchAlt",
    category: "Outline",
  },
  {
    name: "SearchHeart",
    file: TxIconOutline.IconSearchHeart,
    description: "SearchHeart",
    category: "Outline",
  },
  {
    name: "Search",
    file: TxIconOutline.IconSearch,
    description: "Search",
    category: "Outline",
  },
  {
    name: "SettingsSliders",
    file: TxIconOutline.IconSettingsSliders,
    description: "SettingsSliders",
    category: "Outline",
  },
  {
    name: "Settings",
    file: TxIconOutline.IconSettings,
    description: "Settings",
    category: "Outline",
  },
  {
    name: "Share",
    file: TxIconOutline.IconShare,
    description: "Share",
    category: "Outline",
  },
  {
    name: "ShieldCheck",
    file: TxIconOutline.IconShieldCheck,
    description: "ShieldCheck",
    category: "Outline",
  },
  {
    name: "ShieldExclamation",
    file: TxIconOutline.IconShieldExclamation,
    description: "ShieldExclamation",
    category: "Outline",
  },
  {
    name: "ShieldInterrogation",
    file: TxIconOutline.IconShieldInterrogation,
    description: "ShieldInterrogation",
    category: "Outline",
  },
  {
    name: "ShieldPlus",
    file: TxIconOutline.IconShieldPlus,
    description: "ShieldPlus",
    category: "Outline",
  },
  {
    name: "Shield",
    file: TxIconOutline.IconShield,
    description: "Shield",
    category: "Outline",
  },
  {
    name: "ShipSide",
    file: TxIconOutline.IconShipSide,
    description: "ShipSide",
    category: "Outline",
  },
  {
    name: "Ship",
    file: TxIconOutline.IconShip,
    description: "Ship",
    category: "Outline",
  },
  {
    name: "Shop",
    file: TxIconOutline.IconShop,
    description: "Shop",
    category: "Outline",
  },
  {
    name: "ShoppingBagAdd",
    file: TxIconOutline.IconShoppingBagAdd,
    description: "ShoppingBagAdd",
    category: "Outline",
  },
  {
    name: "ShoppingBag",
    file: TxIconOutline.IconShoppingBag,
    description: "ShoppingBag",
    category: "Outline",
  },
  {
    name: "ShoppingCartAdd",
    file: TxIconOutline.IconShoppingCartAdd,
    description: "ShoppingCartAdd",
    category: "Outline",
  },
  {
    name: "ShoppingCartCheck",
    file: TxIconOutline.IconShoppingCartCheck,
    description: "ShoppingCartCheck",
    category: "Outline",
  },
  {
    name: "ShoppingCart",
    file: TxIconOutline.IconShoppingCart,
    description: "ShoppingCart",
    category: "Outline",
  },
  {
    name: "Shuffle",
    file: TxIconOutline.IconShuffle,
    description: "Shuffle",
    category: "Outline",
  },
  {
    name: "SignInAlt",
    file: TxIconOutline.IconSignInAlt,
    description: "SignInAlt",
    category: "Outline",
  },
  {
    name: "SignIn",
    file: TxIconOutline.IconSignIn,
    description: "SignIn",
    category: "Outline",
  },
  {
    name: "SignOutAlt",
    file: TxIconOutline.IconSignOutAlt,
    description: "SignOutAlt",
    category: "Outline",
  },
  {
    name: "SignOut",
    file: TxIconOutline.IconSignOut,
    description: "SignOut",
    category: "Outline",
  },
  {
    name: "SignalAlt1",
    file: TxIconOutline.IconSignalAlt1,
    description: "SignalAlt1",
    category: "Outline",
  },
  {
    name: "SignalAlt2",
    file: TxIconOutline.IconSignalAlt2,
    description: "SignalAlt2",
    category: "Outline",
  },
  {
    name: "SignalAlt",
    file: TxIconOutline.IconSignalAlt,
    description: "SignalAlt",
    category: "Outline",
  },
  {
    name: "Skateboard",
    file: TxIconOutline.IconSkateboard,
    description: "Skateboard",
    category: "Outline",
  },
  {
    name: "Smartphone",
    file: TxIconOutline.IconSmartphone,
    description: "Smartphone",
    category: "Outline",
  },
  {
    name: "SmileWink",
    file: TxIconOutline.IconSmileWink,
    description: "SmileWink",
    category: "Outline",
  },
  {
    name: "Smile",
    file: TxIconOutline.IconSmile,
    description: "Smile",
    category: "Outline",
  },
  {
    name: "Snowflake",
    file: TxIconOutline.IconSnowflake,
    description: "Snowflake",
    category: "Outline",
  },
  {
    name: "Soap",
    file: TxIconOutline.IconSoap,
    description: "Soap",
    category: "Outline",
  },
  {
    name: "Soup",
    file: TxIconOutline.IconSoup,
    description: "Soup",
    category: "Outline",
  },
  {
    name: "Spa",
    file: TxIconOutline.IconSpa,
    description: "Spa",
    category: "Outline",
  },
  {
    name: "Speaker",
    file: TxIconOutline.IconSpeaker,
    description: "Speaker",
    category: "Outline",
  },
  {
    name: "Sphere",
    file: TxIconOutline.IconSphere,
    description: "Sphere",
    category: "Outline",
  },
  {
    name: "SpinnerAlt",
    file: TxIconOutline.IconSpinnerAlt,
    description: "SpinnerAlt",
    category: "Outline",
  },
  {
    name: "Spinner",
    file: TxIconOutline.IconSpinner,
    description: "Spinner",
    category: "Outline",
  },
  {
    name: "SquareRoot",
    file: TxIconOutline.IconSquareRoot,
    description: "SquareRoot",
    category: "Outline",
  },
  {
    name: "Square",
    file: TxIconOutline.IconSquare,
    description: "Square",
    category: "Outline",
  },
  {
    name: "StarOctogram",
    file: TxIconOutline.IconStarOctogram,
    description: "StarOctogram",
    category: "Outline",
  },
  {
    name: "Star",
    file: TxIconOutline.IconStar,
    description: "Star",
    category: "Outline",
  },
  {
    name: "Stats",
    file: TxIconOutline.IconStats,
    description: "Stats",
    category: "Outline",
  },
  {
    name: "Stethoscope",
    file: TxIconOutline.IconStethoscope,
    description: "Stethoscope",
    category: "Outline",
  },
  {
    name: "Sticker",
    file: TxIconOutline.IconSticker,
    description: "Sticker",
    category: "Outline",
  },
  {
    name: "Stop",
    file: TxIconOutline.IconStop,
    description: "Stop",
    category: "Outline",
  },
  {
    name: "Stopwatch",
    file: TxIconOutline.IconStopwatch,
    description: "Stopwatch",
    category: "Outline",
  },
  {
    name: "Subtitles",
    file: TxIconOutline.IconSubtitles,
    description: "Subtitles",
    category: "Outline",
  },
  {
    name: "Sun",
    file: TxIconOutline.IconSun,
    description: "Sun",
    category: "Outline",
  },
  {
    name: "Sunrise",
    file: TxIconOutline.IconSunrise,
    description: "Sunrise",
    category: "Outline",
  },
  {
    name: "Surfing",
    file: TxIconOutline.IconSurfing,
    description: "Surfing",
    category: "Outline",
  },
  {
    name: "Sword",
    file: TxIconOutline.IconSword,
    description: "Sword",
    category: "Outline",
  },
  {
    name: "Syringe",
    file: TxIconOutline.IconSyringe,
    description: "Syringe",
    category: "Outline",
  },
  {
    name: "Tablet",
    file: TxIconOutline.IconTablet,
    description: "Tablet",
    category: "Outline",
  },
  {
    name: "Target",
    file: TxIconOutline.IconTarget,
    description: "Target",
    category: "Outline",
  },
  {
    name: "Taxi",
    file: TxIconOutline.IconTaxi,
    description: "Taxi",
    category: "Outline",
  },
  {
    name: "Tennis",
    file: TxIconOutline.IconTennis,
    description: "Tennis",
    category: "Outline",
  },
  {
    name: "Terrace",
    file: TxIconOutline.IconTerrace,
    description: "Terrace",
    category: "Outline",
  },
  {
    name: "TestTube",
    file: TxIconOutline.IconTestTube,
    description: "TestTube",
    category: "Outline",
  },
  {
    name: "Test",
    file: TxIconOutline.IconTest,
    description: "Test",
    category: "Outline",
  },
  {
    name: "TextCheck",
    file: TxIconOutline.IconTextCheck,
    description: "TextCheck",
    category: "Outline",
  },
  {
    name: "Text",
    file: TxIconOutline.IconText,
    description: "Text",
    category: "Outline",
  },
  {
    name: "ThermometerHalf",
    file: TxIconOutline.IconThermometerHalf,
    description: "ThermometerHalf",
    category: "Outline",
  },
  {
    name: "ThumbsDown",
    file: TxIconOutline.IconThumbsDown,
    description: "ThumbsDown",
    category: "Outline",
  },
  {
    name: "ThumbsUp",
    file: TxIconOutline.IconThumbsUp,
    description: "ThumbsUp",
    category: "Outline",
  },
  {
    name: "Thumbtack",
    file: TxIconOutline.IconThumbtack,
    description: "Thumbtack",
    category: "Outline",
  },
  {
    name: "Ticket",
    file: TxIconOutline.IconTicket,
    description: "Ticket",
    category: "Outline",
  },
  {
    name: "TimeAdd",
    file: TxIconOutline.IconTimeAdd,
    description: "TimeAdd",
    category: "Outline",
  },
  {
    name: "TimeCheck",
    file: TxIconOutline.IconTimeCheck,
    description: "TimeCheck",
    category: "Outline",
  },
  {
    name: "TimeDelete",
    file: TxIconOutline.IconTimeDelete,
    description: "TimeDelete",
    category: "Outline",
  },
  {
    name: "TimeFast",
    file: TxIconOutline.IconTimeFast,
    description: "TimeFast",
    category: "Outline",
  },
  {
    name: "TimeForwardSixty",
    file: TxIconOutline.IconTimeForwardSixty,
    description: "TimeForwardSixty",
    category: "Outline",
  },
  {
    name: "TimeForwardTen",
    file: TxIconOutline.IconTimeForwardTen,
    description: "TimeForwardTen",
    category: "Outline",
  },
  {
    name: "TimeForward",
    file: TxIconOutline.IconTimeForward,
    description: "TimeForward",
    category: "Outline",
  },
  {
    name: "TimeHalfPast",
    file: TxIconOutline.IconTimeHalfPast,
    description: "TimeHalfPast",
    category: "Outline",
  },
  {
    name: "TimeOclock",
    file: TxIconOutline.IconTimeOclock,
    description: "TimeOclock",
    category: "Outline",
  },
  {
    name: "TimePast",
    file: TxIconOutline.IconTimePast,
    description: "TimePast",
    category: "Outline",
  },
  {
    name: "TimeQuarterPast",
    file: TxIconOutline.IconTimeQuarterPast,
    description: "TimeQuarterPast",
    category: "Outline",
  },
  {
    name: "TimeQuarterTo",
    file: TxIconOutline.IconTimeQuarterTo,
    description: "TimeQuarterTo",
    category: "Outline",
  },
  {
    name: "TimeTwentyFour",
    file: TxIconOutline.IconTimeTwentyFour,
    description: "TimeTwentyFour",
    category: "Outline",
  },
  {
    name: "ToolCrop",
    file: TxIconOutline.IconToolCrop,
    description: "ToolCrop",
    category: "Outline",
  },
  {
    name: "ToolMarquee",
    file: TxIconOutline.IconToolMarquee,
    description: "ToolMarquee",
    category: "Outline",
  },
  {
    name: "Tooth",
    file: TxIconOutline.IconTooth,
    description: "Tooth",
    category: "Outline",
  },
  {
    name: "Tornado",
    file: TxIconOutline.IconTornado,
    description: "Tornado",
    category: "Outline",
  },
  {
    name: "TrainSide",
    file: TxIconOutline.IconTrainSide,
    description: "TrainSide",
    category: "Outline",
  },
  {
    name: "Train",
    file: TxIconOutline.IconTrain,
    description: "Train",
    category: "Outline",
  },
  {
    name: "Transform",
    file: TxIconOutline.IconTransform,
    description: "Transform",
    category: "Outline",
  },
  {
    name: "Trash",
    file: TxIconOutline.IconTrash,
    description: "Trash",
    category: "Outline",
  },
  {
    name: "Treatment",
    file: TxIconOutline.IconTreatment,
    description: "Treatment",
    category: "Outline",
  },
  {
    name: "TreeChristmas",
    file: TxIconOutline.IconTreeChristmas,
    description: "TreeChristmas",
    category: "Outline",
  },
  {
    name: "Tree",
    file: TxIconOutline.IconTree,
    description: "Tree",
    category: "Outline",
  },
  {
    name: "Triangle",
    file: TxIconOutline.IconTriangle,
    description: "Triangle",
    category: "Outline",
  },
  {
    name: "Trophy",
    file: TxIconOutline.IconTrophy,
    description: "Trophy",
    category: "Outline",
  },
  {
    name: "TruckSide",
    file: TxIconOutline.IconTruckSide,
    description: "TruckSide",
    category: "Outline",
  },
  {
    name: "Umbrella",
    file: TxIconOutline.IconUmbrella,
    description: "Umbrella",
    category: "Outline",
  },
  {
    name: "Underline",
    file: TxIconOutline.IconUnderline,
    description: "Underline",
    category: "Outline",
  },
  {
    name: "UndoAlt",
    file: TxIconOutline.IconUndoAlt,
    description: "UndoAlt",
    category: "Outline",
  },
  {
    name: "Undo",
    file: TxIconOutline.IconUndo,
    description: "Undo",
    category: "Outline",
  },
  {
    name: "Unlock",
    file: TxIconOutline.IconUnlock,
    description: "Unlock",
    category: "Outline",
  },
  {
    name: "Upload",
    file: TxIconOutline.IconUpload,
    description: "Upload",
    category: "Outline",
  },
  {
    name: "UsbPendrive",
    file: TxIconOutline.IconUsbPendrive,
    description: "UsbPendrive",
    category: "Outline",
  },
  {
    name: "UserAdd",
    file: TxIconOutline.IconUserAdd,
    description: "UserAdd",
    category: "Outline",
  },
  {
    name: "UserDelete",
    file: TxIconOutline.IconUserDelete,
    description: "UserDelete",
    category: "Outline",
  },
  {
    name: "UserRemove",
    file: TxIconOutline.IconUserRemove,
    description: "UserRemove",
    category: "Outline",
  },
  {
    name: "UserTime",
    file: TxIconOutline.IconUserTime,
    description: "UserTime",
    category: "Outline",
  },
  {
    name: "User",
    file: TxIconOutline.IconUser,
    description: "User",
    category: "Outline",
  },
  {
    name: "Utensils",
    file: TxIconOutline.IconUtensils,
    description: "Utensils",
    category: "Outline",
  },
  {
    name: "VectorAlt",
    file: TxIconOutline.IconVectorAlt,
    description: "VectorAlt",
    category: "Outline",
  },
  {
    name: "Vector",
    file: TxIconOutline.IconVector,
    description: "Vector",
    category: "Outline",
  },
  {
    name: "VenusDouble",
    file: TxIconOutline.IconVenusDouble,
    description: "VenusDouble",
    category: "Outline",
  },
  {
    name: "VenusMars",
    file: TxIconOutline.IconVenusMars,
    description: "VenusMars",
    category: "Outline",
  },
  {
    name: "Venus",
    file: TxIconOutline.IconVenus,
    description: "Venus",
    category: "Outline",
  },
  {
    name: "VideoCamera",
    file: TxIconOutline.IconVideoCamera,
    description: "VideoCamera",
    category: "Outline",
  },
  {
    name: "Volleyball",
    file: TxIconOutline.IconVolleyball,
    description: "Volleyball",
    category: "Outline",
  },
  {
    name: "Volume",
    file: TxIconOutline.IconVolume,
    description: "Volume",
    category: "Outline",
  },
  {
    name: "Wheelchair",
    file: TxIconOutline.IconWheelchair,
    description: "Wheelchair",
    category: "Outline",
  },
  {
    name: "WifiAlt",
    file: TxIconOutline.IconWifiAlt,
    description: "WifiAlt",
    category: "Outline",
  },
  {
    name: "Wind",
    file: TxIconOutline.IconWind,
    description: "Wind",
    category: "Outline",
  },
  {
    name: "WomanHead",
    file: TxIconOutline.IconWomanHead,
    description: "WomanHead",
    category: "Outline",
  },
  {
    name: "World",
    file: TxIconOutline.IconWorld,
    description: "World",
    category: "Outline",
  },
  {
    name: "Yen",
    file: TxIconOutline.IconYen,
    description: "Yen",
    category: "Outline",
  },
  {
    name: "ZoomIn",
    file: TxIconOutline.IconZoomIn,
    description: "ZoomIn",
    category: "Outline",
  },
  {
    name: "ZoomOut",
    file: TxIconOutline.IconZoomOut,
    description: "ZoomOut",
    category: "Outline",
  },
];

function IconListTemplate({ variant = "outline" }) {
  const [searchQuery, setSearchQuery] = useState("");

  const filteredIcons = iconData.filter(
    icon =>
      icon.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      icon.description.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div style={{ margin: "0 auto" }}>
      {/* Search Input */}
      <div style={{ marginBottom: "24px" }}>
        <input
          type="text"
          placeholder={`Search ${iconData.length} icons by name...`}
          value={searchQuery}
          onChange={e => setSearchQuery(e.target.value)}
          style={{
            width: "100%",
            padding: "14px 18px",
            border: "1px solid #e0e0e0",
            borderRadius: "8px",
            fontSize: "15px",
            outline: "none",
            transition: "border-color 0.2s",
          }}
          onFocus={e => {
            e.target.style.borderColor = "#00bcff";
          }}
          onBlur={e => {
            e.target.style.borderColor = "#e0e0e0";
          }}
        />
      </div>

      {/* Results count */}
      <div style={{ marginBottom: "16px", fontSize: "14px", color: "#666" }}>
        Showing {filteredIcons.length} of {iconData.length} icons
      </div>

      {/* Icons Grid */}
      {filteredIcons.length > 0 ? (
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fill, minmax(110px, 1fr))",
            gap: "8px",
          }}
        >
          {filteredIcons.map(icon => (
            <div
              key={icon.name}
              style={{
                display: "flex",
                flexDirection: "column",
                alignItems: "center",
                gap: "8px",
                padding: "12px",
                background: "#ffffff",
                border: "1px solid #e0e0e0",
                borderRadius: "12px",
                transition: "all 0.2s",
                cursor: "pointer",
              }}
              onMouseEnter={e => {
                e.currentTarget.style.transform = "translateY(-4px)";
                e.currentTarget.style.boxShadow = "0 8px 16px rgba(0, 0, 0, 0.1)";
                e.currentTarget.style.borderColor = "#00bcff";
              }}
              onMouseLeave={e => {
                e.currentTarget.style.transform = "translateY(0)";
                e.currentTarget.style.boxShadow = "none";
                e.currentTarget.style.borderColor = "#e0e0e0";
              }}
            >
              {/* Icon Display */}
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "center",
                  width: "40px",
                  height: "40px",
                  background: "#f5f5f5",
                  borderRadius: "12px",
                  marginBottom: "4px",
                }}
              >
                <img src={icon.file} alt={icon.name} style={{ width: "16px", height: "16px", objectFit: "contain" }} />
              </div>

              {/* Icon Info */}
              <div style={{ textAlign: "center", width: "100%" }}>
                <span
                  style={{
                    display: "block",
                    marginBottom: "4px",
                    fontSize: "11px",
                    color: "#1a1a1a",
                    lineHeight: "1.2",
                    fontWeight: "500",
                  }}
                >
                  {icon.name}
                </span>
              </div>
            </div>
          ))}
        </div>
      ) : (
        <div style={{ textAlign: "center", padding: "60px", color: "#888" }}>
          <p style={{ fontSize: "16px" }}>No icons found matching "{searchQuery}"</p>
          <p style={{ fontSize: "14px", marginTop: "8px" }}>Try a different search term</p>
        </div>
      )}
    </div>
  );
}

// Story for Outline icons
export const Outline = {
  render: () => <IconListTemplate variant="outline" />,
};

// Story for Filled icons (placeholder)
export const Filled = {
  render: () => (
    <div style={{ padding: "60px", textAlign: "center", color: "#888", fontFamily: "sans-serif" }}>
      <p style={{ fontSize: "16px" }}>Filled icons coming soon...</p>
    </div>
  ),
};
